# Generated by Django 5.2.9 on 2026-01-04 23:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lineas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Indicador",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=20, unique=True, verbose_name="Código"),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("GESTION", "Gestión de Mantenimiento"),
                            ("EJECUCION", "Ejecución de Mantenimiento"),
                            ("AMBIENTAL", "Gestión Ambiental"),
                            ("SEGURIDAD", "Seguridad Industrial"),
                            ("CALIDAD", "Calidad de Información"),
                        ],
                        max_length=20,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "formula",
                    models.TextField(
                        help_text="Descripción de cómo se calcula el indicador",
                        verbose_name="Fórmula",
                    ),
                ),
                (
                    "unidad",
                    models.CharField(default="%", max_length=20, verbose_name="Unidad"),
                ),
                (
                    "meta",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor objetivo del indicador",
                        max_digits=6,
                        verbose_name="Meta",
                    ),
                ),
                (
                    "umbral_alerta",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor por debajo del cual se genera alerta",
                        max_digits=6,
                        verbose_name="Umbral de alerta",
                    ),
                ),
                (
                    "peso_ponderacion",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Peso para cálculo de indicador global",
                        max_digits=4,
                        verbose_name="Peso ponderación",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Indicador",
                "verbose_name_plural": "Indicadores",
                "db_table": "indicadores",
                "ordering": ["categoria", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="ActaSeguimiento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                ("anio", models.PositiveIntegerField(verbose_name="Año")),
                ("mes", models.PositiveIntegerField(verbose_name="Mes")),
                ("fecha_reunion", models.DateField(verbose_name="Fecha de reunión")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("PENDIENTE_FIRMA", "Pendiente Firma"),
                            ("FIRMADA", "Firmada"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "asistentes_instelec",
                    models.TextField(blank=True, verbose_name="Asistentes Instelec"),
                ),
                (
                    "asistentes_cliente",
                    models.TextField(blank=True, verbose_name="Asistentes Cliente"),
                ),
                (
                    "resumen_indicadores",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Resumen de indicadores"
                    ),
                ),
                (
                    "compromisos",
                    models.TextField(blank=True, verbose_name="Compromisos"),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "url_acta_firmada",
                    models.URLField(blank=True, verbose_name="URL acta firmada"),
                ),
                (
                    "linea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actas_seguimiento",
                        to="lineas.linea",
                        verbose_name="Línea",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acta de Seguimiento",
                "verbose_name_plural": "Actas de Seguimiento",
                "db_table": "actas_seguimiento",
                "ordering": ["-anio", "-mes"],
                "unique_together": {("linea", "anio", "mes")},
            },
        ),
        migrations.CreateModel(
            name="MedicionIndicador",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                ("anio", models.PositiveIntegerField(verbose_name="Año")),
                ("mes", models.PositiveIntegerField(verbose_name="Mes")),
                (
                    "valor_numerador",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Numerador",
                    ),
                ),
                (
                    "valor_denominador",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Denominador",
                    ),
                ),
                (
                    "valor_calculado",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valor calculado",
                    ),
                ),
                (
                    "cumple_meta",
                    models.BooleanField(default=False, verbose_name="Cumple meta"),
                ),
                (
                    "en_alerta",
                    models.BooleanField(default=False, verbose_name="En alerta"),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "indicador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mediciones",
                        to="indicadores.indicador",
                        verbose_name="Indicador",
                    ),
                ),
                (
                    "linea",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mediciones_indicador",
                        to="lineas.linea",
                        verbose_name="Línea",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medición de Indicador",
                "verbose_name_plural": "Mediciones de Indicador",
                "db_table": "mediciones_indicador",
                "ordering": ["-anio", "-mes", "indicador"],
                "unique_together": {("indicador", "linea", "anio", "mes")},
            },
        ),
    ]
