# Generated by Django 5.1.15 on 2026-05-26 03:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0002_alter_actaseguimiento_resumen_indicadores'),
        ('lineas', '0011_b21_vano_semestre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorANSContractual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha', models.DateField(verbose_name='Fecha de corte')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='Anio')),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mes')),
                ('cumplimiento_programacion', models.DecimalField(decimal_places=2, default=0, help_text='Peso 30 %. Meta >= 95 %.', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Cumplimiento programacion (%)')),
                ('cumplimiento_ejecucion', models.DecimalField(decimal_places=2, default=0, help_text='Peso 30 %. Meta >= 95 %.', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Cumplimiento ejecucion (%)')),
                ('cumplimiento_informacion_contractual', models.DecimalField(decimal_places=2, default=0, help_text='Peso 15 %. Meta >= 100 %.', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Cumplimiento informacion contractual (%)')),
                ('cumplimiento_informacion_ambiental', models.DecimalField(decimal_places=2, default=0, help_text='Peso 15 %. Meta >= 100 %.', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Cumplimiento informacion ambiental (%)')),
                ('cumplimiento_disponibilidad_circuitos', models.DecimalField(decimal_places=2, default=0, help_text='Peso 10 %. Meta >= 98 %.', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Disponibilidad circuitos (%)')),
                ('puntaje_total_ans', models.DecimalField(decimal_places=2, default=0, help_text='Suma ponderada. Meta >= 90 %.', max_digits=6, verbose_name='Puntaje total ANS (%)')),
                ('estado_ans', models.CharField(choices=[('CUMPLE', 'Cumple'), ('PARCIAL', 'Cumplimiento parcial'), ('NO_CUMPLE', 'No cumple')], default='NO_CUMPLE', max_length=16, verbose_name='Estado ANS')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicadores_ans', to='lineas.linea', verbose_name='Linea')),
            ],
            options={
                'verbose_name': 'Indicador ANS Contractual',
                'verbose_name_plural': 'Indicadores ANS Contractual',
                'db_table': 'indicadores_ans_contractual',
                'ordering': ['-anio', '-mes', '-fecha'],
                'constraints': [models.UniqueConstraint(fields=('linea', 'anio', 'mes'), name='uniq_ans_linea_periodo')],
            },
        ),
        migrations.CreateModel(
            name='IndicadorMantenimientoFinanciero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha', models.DateField(verbose_name='Fecha de corte')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='Anio')),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mes')),
                ('ingresos_ejecutados', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Ingresos ejecutados')),
                ('costos_directos', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Costos directos')),
                ('gastos', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Gastos')),
                ('costo_real', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Costo real')),
                ('costo_presupuestado', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Costo presupuestado')),
                ('margen_operativo', models.DecimalField(decimal_places=2, default=0, help_text='(IE - (CD + G)) / IE x 100. Meta >= 20 %.', max_digits=8, verbose_name='Margen operativo (%)')),
                ('desviacion_presupuestal', models.DecimalField(decimal_places=2, default=0, help_text='(CR - CP) / CP x 100. Meta <= 25 %.', max_digits=8, verbose_name='Desviacion presupuestal (%)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('linea', models.ForeignKey(blank=True, help_text='Linea asociada (opcional, agregado por proyecto si vacio).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicadores_mant_financiero', to='lineas.linea', verbose_name='Linea')),
            ],
            options={
                'verbose_name': 'Indicador Mantenimiento Financiero',
                'verbose_name_plural': 'Indicadores Mantenimiento Financiero',
                'db_table': 'indicadores_mant_financiero',
                'ordering': ['-anio', '-mes', '-fecha'],
                'constraints': [models.UniqueConstraint(fields=('linea', 'anio', 'mes'), name='uniq_mant_fin_linea_periodo')],
            },
        ),
        migrations.CreateModel(
            name='IndicadorMantenimientoTecnico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha', models.DateField(verbose_name='Fecha de corte')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='Anio')),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mes')),
                ('facturacion_real', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Facturacion real')),
                ('meta_facturacion', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Meta facturacion')),
                ('produccion_real', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Produccion real')),
                ('meta_produccion', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Meta produccion')),
                ('valor_facturado', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Valor facturado')),
                ('costo_cuadrilla', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Costo cuadrilla')),
                ('ejecucion_presupuestal', models.DecimalField(decimal_places=4, default=0, help_text='FR / MF x 100. Meta 2.95 %.', max_digits=10, verbose_name='Ejecucion presupuestal (%)')),
                ('produccion_cuadrillas', models.DecimalField(decimal_places=4, default=0, help_text='PR / MP x 100. Meta >= 2.95 %.', max_digits=10, verbose_name='Produccion cuadrillas (%)')),
                ('rentabilidad_costo_fijo', models.DecimalField(decimal_places=4, default=0, help_text='VF / CC. Meta >= 12.', max_digits=10, verbose_name='Rentabilidad costo fijo (ratio)')),
                ('meta_facturacion_general', models.DecimalField(decimal_places=4, default=0, help_text='FR / MF x 100. Meta >= 100 %.', max_digits=10, verbose_name='Meta facturacion general (%)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicadores_mant_tecnico', to='lineas.linea', verbose_name='Linea')),
            ],
            options={
                'verbose_name': 'Indicador Mantenimiento Tecnico',
                'verbose_name_plural': 'Indicadores Mantenimiento Tecnico',
                'db_table': 'indicadores_mant_tecnico',
                'ordering': ['-anio', '-mes', '-fecha'],
                'constraints': [models.UniqueConstraint(fields=('linea', 'anio', 'mes'), name='uniq_mant_tec_linea_periodo')],
            },
        ),
    ]
