# Generated by Django 5.2.9 on 2026-01-04 23:16

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Linea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código único de la línea (ej: L-838)",
                        max_length=20,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre descriptivo de la línea",
                        max_length=150,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "cliente",
                    models.CharField(
                        choices=[
                            ("TRANSELCA", "Transelca"),
                            ("INTERCOLOMBIA", "Intercolombia"),
                        ],
                        default="TRANSELCA",
                        max_length=20,
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "longitud_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Longitud (km)",
                    ),
                ),
                (
                    "tension_kv",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Tensión nominal en kilovoltios",
                        null=True,
                        verbose_name="Tensión (kV)",
                    ),
                ),
                (
                    "municipios",
                    models.CharField(
                        blank=True,
                        help_text="Municipios por donde pasa la línea",
                        max_length=500,
                        verbose_name="Municipios",
                    ),
                ),
                (
                    "departamento",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Departamento"
                    ),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
            ],
            options={
                "verbose_name": "Línea",
                "verbose_name_plural": "Líneas",
                "db_table": "lineas",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Torre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        help_text="Número o código de la torre",
                        max_length=20,
                        verbose_name="Número",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("SUSPENSION", "Suspensión"),
                            ("ANCLAJE", "Anclaje"),
                            ("TERMINAL", "Terminal"),
                            ("REMATE", "Remate"),
                            ("DERIVACION", "Derivación"),
                        ],
                        default="SUSPENSION",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BUENO", "Bueno"),
                            ("REGULAR", "Regular"),
                            ("MALO", "Malo"),
                            ("CRITICO", "Crítico"),
                        ],
                        default="BUENO",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "latitud",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Latitud en grados decimales",
                        max_digits=10,
                        verbose_name="Latitud",
                    ),
                ),
                (
                    "longitud",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Longitud en grados decimales",
                        max_digits=11,
                        verbose_name="Longitud",
                    ),
                ),
                (
                    "altitud",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Altitud (msnm)",
                    ),
                ),
                (
                    "geometria",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        null=True,
                        srid=4326,
                        verbose_name="Ubicación geográfica",
                    ),
                ),
                (
                    "altura_estructura",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Altura estructura (m)",
                    ),
                ),
                (
                    "propietario_predio",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Propietario del predio",
                    ),
                ),
                (
                    "vereda",
                    models.CharField(blank=True, max_length=100, verbose_name="Vereda"),
                ),
                (
                    "municipio",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Municipio"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "linea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="torres",
                        to="lineas.linea",
                        verbose_name="Línea",
                    ),
                ),
            ],
            options={
                "verbose_name": "Torre",
                "verbose_name_plural": "Torres",
                "db_table": "torres",
                "ordering": ["linea", "numero"],
                "unique_together": {("linea", "numero")},
            },
        ),
        migrations.CreateModel(
            name="PoligonoServidumbre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(blank=True, max_length=100, verbose_name="Nombre"),
                ),
                (
                    "geometria",
                    django.contrib.gis.db.models.fields.PolygonField(
                        srid=4326, verbose_name="Geometría"
                    ),
                ),
                (
                    "area_hectareas",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="Área (hectáreas)",
                    ),
                ),
                (
                    "ancho_franja",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Ancho de franja (m)",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "linea",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poligonos",
                        to="lineas.linea",
                        verbose_name="Línea",
                    ),
                ),
                (
                    "torre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poligonos",
                        to="lineas.torre",
                        verbose_name="Torre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Polígono de Servidumbre",
                "verbose_name_plural": "Polígonos de Servidumbre",
                "db_table": "poligonos_servidumbre",
            },
        ),
    ]
