# Generated by Django 5.1.15 on 2026-04-01 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        ('lineas', '0004_linea_kmz_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='linea',
            name='cantidad_postes',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad de postes (si aplica)', null=True, verbose_name='Cantidad de postes'),
        ),
        migrations.AddField(
            model_name='linea',
            name='cantidad_torres',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad total de torres en la línea', null=True, verbose_name='Cantidad de torres'),
        ),
        migrations.AddField(
            model_name='linea',
            name='contrato',
            field=models.ForeignKey(blank=True, help_text='Contrato o proyecto al que pertenece esta línea', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas', to='contratos.contrato', verbose_name='Contrato/Proyecto'),
        ),
        migrations.AddField(
            model_name='linea',
            name='tipo_estructura',
            field=models.CharField(choices=[('TORRES', 'Torres'), ('POSTES', 'Postes'), ('MIXTO', 'Mixto')], default='TORRES', help_text='Tipo de estructura predominante en la línea', max_length=20, verbose_name='Tipo de estructura'),
        ),
    ]
