# Generated by Django 5.1.15 on 2026-04-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineas', '0005_linea_cantidad_postes_linea_cantidad_torres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linea',
            name='cantidad_vanos',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad total de vanos entre torres', null=True, verbose_name='Cantidad de vanos'),
        ),
    ]
