# Generated by Django 5.1.15 on 2026-04-23 18:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineas', '0006_linea_cantidad_vanos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vano',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('numero', models.CharField(help_text='Número o identificador del vano', max_length=20, verbose_name='Número de vano')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vanos', to='lineas.linea', verbose_name='Línea')),
                ('torre_fin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vanos_fin', to='lineas.torre', verbose_name='Torre fin')),
                ('torre_inicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vanos_inicio', to='lineas.torre', verbose_name='Torre inicio')),
            ],
            options={
                'verbose_name': 'Vano',
                'verbose_name_plural': 'Vanos',
                'db_table': 'vanos',
                'ordering': ['linea', 'numero'],
                'unique_together': {('linea', 'numero')},
            },
        ),
    ]
