# Generated by Django 5.1.15 on 2026-04-23 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineas', '0007_vano'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vano',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('ejecutado', 'Ejecutado'), ('sin_permiso', 'Sin Permiso'), ('no_ejecutado', 'No Ejecutado'), ('en_espera', 'En Espera')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='vano',
            name='fecha_marcado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha marcado'),
        ),
        migrations.AddField(
            model_name='vano',
            name='marcado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vanos_linea_marcados', to=settings.AUTH_USER_MODEL, verbose_name='Marcado por'),
        ),
    ]
