# Generated by Django 5.1.15 on 2026-04-23 23:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineas', '0008_vano_estado_vano_fecha_marcado_vano_marcado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendienteVano',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('descripcion', models.TextField(help_text='Descripción de la tarea pendiente', verbose_name='Descripción')),
                ('fecha_vencimiento', models.DateField(help_text='Fecha límite para completar la tarea', verbose_name='Fecha de vencimiento')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha completado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendientes_vanos', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('vano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendientes', to='lineas.vano', verbose_name='Vano')),
            ],
            options={
                'verbose_name': 'Pendiente de Vano',
                'verbose_name_plural': 'Pendientes de Vanos',
                'db_table': 'pendientes_vanos',
                'ordering': ['fecha_vencimiento', 'vano'],
                'indexes': [models.Index(fields=['vano', 'completado'], name='pendientes__vano_id_51edb1_idx'), models.Index(fields=['fecha_vencimiento'], name='pendientes__fecha_v_a1d6d7_idx')],
            },
        ),
    ]
