# Generated by Django 5.1.15 on 2026-05-26 01:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineas', '0010_linea_torre_inspection_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VanoSemestre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('semestre', models.CharField(choices=[('S1', 'Semestre 1 (Ene–Jun)'), ('S2', 'Semestre 2 (Jul–Dic)'), ('TA', 'Todo el año')], db_index=True, max_length=2, verbose_name='Semestre')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('ejecutado', 'Ejecutado'), ('sin_permiso', 'Sin Permiso'), ('no_ejecutado', 'No Ejecutado'), ('en_espera', 'En Espera')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_inicio', models.DateField(blank=True, help_text='Inicio del trabajo en este semestre (opcional).', null=True, verbose_name='Fecha inicio del período')),
                ('fecha_fin', models.DateField(blank=True, help_text='Fin previsto del trabajo en este semestre (opcional).', null=True, verbose_name='Fecha fin del período')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vano_semestres_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Última actualización por')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vano_semestres_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('vano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestres', to='lineas.vano', verbose_name='Vano')),
            ],
            options={
                'verbose_name': 'Vano · Semestre',
                'verbose_name_plural': 'Vanos · Semestres',
                'db_table': 'vano_semestres',
                'ordering': ['vano__linea__codigo', 'vano__numero', 'semestre'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoVanoSemestre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha', models.DateField(verbose_name='Fecha de seguimiento')),
                ('porcentaje_avance', models.FloatField(default=0, verbose_name='Porcentaje avance (0–100)')),
                ('horas', models.FloatField(default=0, verbose_name='Horas trabajadas')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_vano_semestre', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('vano_semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='lineas.vanosemestre', verbose_name='Vano · Semestre')),
            ],
            options={
                'verbose_name': 'Seguimiento Vano · Semestre',
                'verbose_name_plural': 'Seguimientos Vanos · Semestres',
                'db_table': 'seguimientos_vano_semestre',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vanosemestre',
            index=models.Index(fields=['semestre', 'estado'], name='vano_semest_semestr_c8a70b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vanosemestre',
            unique_together={('vano', 'semestre')},
        ),
        migrations.AddIndex(
            model_name='seguimientovanosemestre',
            index=models.Index(fields=['vano_semestre', '-fecha'], name='seguimiento_vano_se_8e0d91_idx'),
        ),
    ]
