# Generated by Django 5.1.15 on 2026-06-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineas', '0011_b21_vano_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea',
            name='last_inspection_date',
            field=models.DateField(blank=True, help_text='Calculada a partir de RegistroCampo / HistorialIntervencion', null=True, verbose_name='Última inspección'),
        ),
    ]
