# Generated by Django 5.1.15 on 2026-06-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineas', '0012_alter_linea_last_inspection_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vano',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='campo/vanos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='vano',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('ejecutado', 'Ejecutado'), ('sin_permiso', 'Sin Permiso'), ('no_ejecutado', 'No Ejecutado'), ('en_espera', 'Parcial')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='vanosemestre',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('ejecutado', 'Ejecutado'), ('sin_permiso', 'Sin Permiso'), ('no_ejecutado', 'No Ejecutado'), ('en_espera', 'Parcial')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
