# Generated by Django 5.1.15 on 2026-07-03 13:37
# Issue #177 (sub-item A1) — Vano.Estado ampliado a 7 choices (aditivo).
# Solo AlterField sobre `choices`, sin mutar ningún dato existente.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineas', '0013_vano_foto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vano',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('ejecutado', 'Ejecutado'), ('sin_permiso', 'Sin Permiso'), ('no_ejecutado', 'No Ejecutado'), ('en_espera', 'Parcial'), ('seccionado', 'Seccionado'), ('especial', 'Especial')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
