# Generated by Django 5.1.15 on 2026-07-03 13:37
# Issue #177 (sub-item A2) — Modelos VanoHistorialEstado + VanoHistorialFoto
# (patrón FotoDano/ReporteDano, HistorialIntervencion). Solo CreateModel,
# sin mutar datos existentes.

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lineas', '0014_vano_estado_7_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='VanoHistorialEstado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('ejecutado', 'Ejecutado'), ('sin_permiso', 'Sin Permiso'), ('no_ejecutado', 'No Ejecutado'), ('en_espera', 'Parcial'), ('seccionado', 'Seccionado'), ('especial', 'Especial')], max_length=20, verbose_name='Estado')),
                ('nota', models.TextField(blank=True, verbose_name='Nota')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_vanos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('vano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='lineas.vano', verbose_name='Vano')),
            ],
            options={
                'verbose_name': 'Historial de estado de Vano',
                'verbose_name_plural': 'Historial de estados de Vano',
                'db_table': 'vanos_historial_estado',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='VanoHistorialFoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('imagen', models.ImageField(upload_to='campo/vanos/historial/', verbose_name='Imagen')),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='lineas.vanohistorialestado', verbose_name='Historial de estado')),
            ],
            options={
                'verbose_name': 'Foto de historial de Vano',
                'verbose_name_plural': 'Fotos de historial de Vano',
                'db_table': 'vanos_historial_fotos',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vanohistorialestado',
            index=models.Index(fields=['vano', '-fecha'], name='vanos_histo_vano_id_74046e_idx'),
        ),
    ]
