# Generated by Django 5.2.9 on 2026-01-04 23:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lineas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "placa",
                    models.CharField(max_length=10, unique=True, verbose_name="Placa"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CAMIONETA", "Camioneta"),
                            ("CAMION", "Camión"),
                            ("GRUA", "Grúa"),
                            ("OTRO", "Otro"),
                        ],
                        default="CAMIONETA",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "marca",
                    models.CharField(blank=True, max_length=50, verbose_name="Marca"),
                ),
                (
                    "modelo",
                    models.CharField(blank=True, max_length=50, verbose_name="Modelo"),
                ),
                (
                    "ano",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Año"
                    ),
                ),
                (
                    "capacidad_personas",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Capacidad (personas)"
                    ),
                ),
                (
                    "costo_dia",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Costo por día",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
            ],
            options={
                "verbose_name": "Vehículo",
                "verbose_name_plural": "Vehículos",
                "db_table": "vehiculos",
                "ordering": ["placa"],
            },
        ),
        migrations.CreateModel(
            name="Cuadrilla",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código único de la cuadrilla (ej: CUA-001)",
                        max_length=20,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("activa", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "linea_asignada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cuadrillas",
                        to="lineas.linea",
                        verbose_name="Línea asignada",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"rol": "supervisor"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cuadrillas_supervisadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Supervisor",
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cuadrillas",
                        to="cuadrillas.vehiculo",
                        verbose_name="Vehículo asignado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuadrilla",
                "verbose_name_plural": "Cuadrillas",
                "db_table": "cuadrillas",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="CuadrillaMiembro",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "rol_cuadrilla",
                    models.CharField(
                        choices=[
                            ("SUPERVISOR", "Supervisor"),
                            ("LINIERO", "Liniero"),
                            ("AYUDANTE", "Ayudante"),
                        ],
                        default="LINIERO",
                        max_length=20,
                        verbose_name="Rol en cuadrilla",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de inicio")),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de fin"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "cuadrilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="miembros",
                        to="cuadrillas.cuadrilla",
                        verbose_name="Cuadrilla",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones_cuadrilla",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Miembro de Cuadrilla",
                "verbose_name_plural": "Miembros de Cuadrilla",
                "db_table": "cuadrilla_miembros",
                "ordering": ["cuadrilla", "rol_cuadrilla", "usuario__first_name"],
                "unique_together": {("cuadrilla", "usuario", "activo")},
            },
        ),
        migrations.CreateModel(
            name="TrackingUbicacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "latitud",
                    models.DecimalField(
                        decimal_places=8, max_digits=10, verbose_name="Latitud"
                    ),
                ),
                (
                    "longitud",
                    models.DecimalField(
                        decimal_places=8, max_digits=11, verbose_name="Longitud"
                    ),
                ),
                (
                    "precision_metros",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Precisión (metros)",
                    ),
                ),
                (
                    "velocidad",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Velocidad (km/h)",
                    ),
                ),
                (
                    "bateria",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Nivel batería (%)"
                    ),
                ),
                (
                    "cuadrilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ubicaciones",
                        to="cuadrillas.cuadrilla",
                        verbose_name="Cuadrilla",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ubicaciones_tracking",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tracking de Ubicación",
                "verbose_name_plural": "Tracking de Ubicaciones",
                "db_table": "tracking_ubicacion",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["cuadrilla", "-created_at"],
                        name="tracking_ub_cuadril_9cf3bf_idx",
                    ),
                    models.Index(
                        fields=["usuario", "-created_at"],
                        name="tracking_ub_usuario_b414fe_idx",
                    ),
                ],
            },
        ),
    ]
