# Generated by Django 5.1.15 on 2026-02-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0008_asistencia_detailed_overtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadrillamiembro',
            name='es_conductor_interno',
            field=models.BooleanField(default=True, help_text='Si es conductor: True=empleado Instelec, False=externo/subcontratado', verbose_name='Conductor interno'),
        ),
    ]
