# Generated by Django 5.1.15 on 2026-03-05 12:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0009_add_conductor_interno'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalCuadrilla',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('documento', models.CharField(max_length=30, unique=True, verbose_name='Documento')),
                ('rol_cuadrilla', models.CharField(choices=[('SUPERVISOR', 'Supervisor'), ('LINIERO_I', 'Liniero I'), ('LINIERO_II', 'Liniero II'), ('AYUDANTE', 'Ayudante'), ('CONDUCTOR', 'Conductor'), ('ADMINISTRADOR_OBRA', 'Administrador de Obra'), ('PROFESIONAL_SST', 'Profesional SST'), ('ING_RESIDENTE', 'Ingeniero Residente'), ('SERVICIO_GENERAL', 'Servicio General'), ('ALMACENISTA', 'Almacenista'), ('SUPERVISOR_FOREST', 'Supervisor Forestal'), ('ASISTENTE_FOREST', 'Asistente Forestal')], default='LINIERO_I', max_length=20, verbose_name='Cargo / Rol')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Personal de Cuadrilla',
                'verbose_name_plural': 'Personal de Cuadrillas',
                'db_table': 'personal_cuadrilla',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='tipo_novedad',
            field=models.CharField(choices=[('PRESENTE', 'Presente'), ('VACACIONES', 'Vacaciones'), ('INCAPACIDAD', 'Incapacidad'), ('PERMISO', 'Permiso'), ('AUSENTE', 'Ausente'), ('LICENCIA', 'Licencia'), ('CAPACITACION', 'Capacitación'), ('COMPENSATORIO', 'Compensatorio'), ('DESCANSO', 'Descanso')], default='PRESENTE', max_length=20, verbose_name='Tipo de novedad'),
        ),
    ]
