# Generated by Django 5.1.15 on 2026-06-11 21:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0034_actividad_final_aplica'),
        ('cuadrillas', '0011_cuadrilla_auditoria_desactivacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramacionSemanalCuadrilla',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('anio', models.PositiveIntegerField(help_text='Año ISO de la programación (ej: 2026)', verbose_name='Año')),
                ('semana', models.PositiveSmallIntegerField(help_text='Número de semana ISO (1-53)', verbose_name='Semana ISO')),
                ('torres_programadas', models.PositiveIntegerField(default=0, help_text='Cantidad de torres planeadas para la semana', verbose_name='Torres programadas')),
                ('actividades_programadas', models.TextField(blank=True, help_text='Descripción de las actividades planeadas para la semana', verbose_name='Actividades programadas')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('cuadrilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones_semanales', to='cuadrillas.cuadrilla', verbose_name='Cuadrilla')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programaciones_cuadrilla', to='construccion.proyectoconstruccion', verbose_name='Proyecto de construcción')),
            ],
            options={
                'verbose_name': 'Programación Semanal de Cuadrilla',
                'verbose_name_plural': 'Programaciones Semanales de Cuadrilla',
                'db_table': 'programacion_semanal_cuadrilla',
                'ordering': ['-anio', '-semana', 'cuadrilla'],
            },
        ),
        migrations.CreateModel(
            name='EjecucionSemanalCuadrilla',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('torres_ejecutadas', models.PositiveIntegerField(default=0, help_text='Cantidad de torres realmente ejecutadas en la semana', verbose_name='Torres ejecutadas')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('programacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ejecucion', to='cuadrillas.programacionsemanalcuadrilla', verbose_name='Programación')),
            ],
            options={
                'verbose_name': 'Ejecución Semanal de Cuadrilla',
                'verbose_name_plural': 'Ejecuciones Semanales de Cuadrilla',
                'db_table': 'ejecucion_semanal_cuadrilla',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='programacionsemanalcuadrilla',
            index=models.Index(fields=['anio', 'semana'], name='programacio_anio_d230bf_idx'),
        ),
        migrations.AddIndex(
            model_name='programacionsemanalcuadrilla',
            index=models.Index(fields=['cuadrilla', 'anio', 'semana'], name='programacio_cuadril_19ac26_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='programacionsemanalcuadrilla',
            unique_together={('cuadrilla', 'anio', 'semana')},
        ),
    ]
