# Generated by Django 5.2.3 on 2026-06-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0012_programacion_ejecucion_semanal'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacionsemanalcuadrilla',
            name='bloque',
            field=models.CharField(blank=True, choices=[('obra_civil', 'Obra civil'), ('montaje', 'Montaje'), ('tendido', 'Tendido')], help_text='Macro-bloque del proyecto (obra civil / montaje / tendido). Opcional: las programaciones sin bloque quedan "sin asignar".', max_length=20, null=True, verbose_name='Bloque'),
        ),
    ]
