# Generated by Django 5.1.15 on 2026-07-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0013_programacion_bloque'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcuadrilla',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AddField(
            model_name='personalcuadrilla',
            name='fecha_salida',
            field=models.DateField(blank=True, help_text='Al registrarla, el colaborador se marca automáticamente como inactivo', null=True, verbose_name='Fecha de salida'),
        ),
        migrations.AddField(
            model_name='personalcuadrilla',
            name='salario_base',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Salario mensual base del colaborador (permite calcular costo/día en reportes de cuadrilla semanal)', max_digits=12, verbose_name='Salario base'),
        ),
    ]
