# Generated by Django 5.1.15 on 2026-07-04 21:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0014_personalcuadrilla_campos_nuevos'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovedadPersonalSemana',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('cedula', models.CharField(max_length=20, verbose_name='Cédula')),
                ('nombre', models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre')),
                ('cargo', models.CharField(blank=True, default='', max_length=100, verbose_name='Cargo')),
                ('semana', models.PositiveSmallIntegerField(verbose_name='Semana ISO')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('nota', models.CharField(blank=True, default='', help_text='Texto de la columna AVISOS en la fila de NOVEDADES (ej. "Vacaciones", "Incapacidad").', max_length=200, verbose_name='Nota')),
                ('hoja_origen', models.CharField(blank=True, default='', max_length=50, verbose_name='Hoja de origen')),
            ],
            options={
                'verbose_name': 'Novedad de personal (semana)',
                'verbose_name_plural': 'Novedades de personal (semana)',
                'ordering': ['-anio', '-semana', 'nombre'],
                'indexes': [models.Index(fields=['anio', 'semana'], name='cuadrillas__anio_7bf99d_idx'), models.Index(fields=['cedula'], name='cuadrillas__cedula_c39a9a_idx')],
            },
        ),
    ]
