# Generated by Django 5.1.15 on 2026-07-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0015_novedad_personal_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadrillamiembro',
            name='rol_cuadrilla',
            field=models.CharField(choices=[('SUPERVISOR', 'Supervisor'), ('LINIERO_I', 'Liniero I'), ('LINIERO_II', 'Liniero II'), ('AYUDANTE', 'Ayudante'), ('CONDUCTOR', 'Conductor'), ('ADMINISTRADOR_OBRA', 'Administrador de Obra'), ('PROFESIONAL_SST', 'Profesional SST'), ('ING_RESIDENTE', 'Ingeniero Residente'), ('SERVICIO_GENERAL', 'Servicio General'), ('ALMACENISTA', 'Almacenista'), ('SUPERVISOR_FOREST', 'Supervisor Forestal'), ('ASISTENTE_FOREST', 'Asistente Forestal'), ('MALACATERO', 'Malacatero'), ('COORDINADOR_HSQ', 'Coordinador HSQ')], default='LINIERO_I', max_length=20, verbose_name='Rol en cuadrilla'),
        ),
    ]
