# Generated by Django 5.1.15 on 2026-07-10 15:16

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cuadrillas", "0017_personalcuadrilla_malacatero_coordinador_hsq"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Fecha de actualización"),
                ),
                ("codigo", models.CharField(max_length=20, unique=True, verbose_name="Código")),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Cargo",
                "verbose_name_plural": "Cargos",
                "db_table": "cargos",
                "ordering": ["nombre"],
            },
        ),
    ]
