# Generated by Django 5.1.15 on 2026-07-19 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0009_costos_presupuesto'),
        ('cuadrillas', '0021_cuadrillamiembro_rol_cuadrilla_fk'),
        ('lineas', '0016_vano_historial_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadrilla',
            name='tipo_actividad',
            field=models.ForeignKey(blank=True, help_text='Issue #188 (A1): tipo de actividad del bloque, cabeza de la cascada Tipo de actividad → Línea → Tramo del grid editable de programación semanal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuadrillas_bloque', to='actividades.tipoactividad', verbose_name='Tipo de actividad'),
        ),
        migrations.AddField(
            model_name='cuadrilla',
            name='tramo',
            field=models.ForeignKey(blank=True, help_text='Issue #188 (A1): tramo de la línea asignada (cascada Línea → Tramo). La tabla tramos puede estar vacía hasta que el cliente la cargue — el campo admite None sin romper el bloque.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuadrillas_bloque', to='lineas.tramo', verbose_name='Tramo'),
        ),
        migrations.AddField(
            model_name='cuadrillamiembro',
            name='placa_vehiculo',
            field=models.CharField(blank=True, help_text='Issue #188 (A1/A5): placa manual del vehículo cuando el rol del miembro es CONDUCTOR (el grid la exige en ese caso; para el resto queda vacía).', max_length=10, verbose_name='Placa del vehículo'),
        ),
        migrations.AddField(
            model_name='personalcuadrilla',
            name='celular',
            field=models.CharField(blank=True, help_text='Issue #188 (A1): celular del colaborador, expuesto en el autocompletado de PersonalCuadrillaAPIView para el grid editable de programación semanal.', max_length=20, verbose_name='Celular'),
        ),
    ]
