# Generated by Django 5.1.15 on 2026-07-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0021_cuadrillamiembro_rol_cuadrilla_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='salario_base',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Salario mensual sugerido para este cargo (default/sugerencia al autocompletar el salario de un Colaborador; el valor efectivo para costos/reportes sigue siendo PersonalCuadrilla.salario_base, issue #176 A1).', max_digits=12, verbose_name='Salario base'),
        ),
    ]
