# Generated by Django 5.1.15 on 2026-07-26 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0023_bloque_tipo_tramo_celular_placa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadrilla',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Issue #178 (M1/A1): fecha de fin real del bloque, ya se parseaba del Excel S18 pero se descartaba. Nullable — filas legacy importadas antes de A1 quedan en None sin romper.', null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AddField(
            model_name='cuadrilla',
            name='hora_fin_planeada',
            field=models.TimeField(blank=True, help_text='Issue #178 (M1/D1): hora de fin PLANEADA del bloque (distinta de la asistencia real registrada por miembro). Nullable — no todos los bloques la traen.', null=True, verbose_name='Hora de fin planeada'),
        ),
        migrations.AddField(
            model_name='cuadrilla',
            name='hora_inicio_planeada',
            field=models.TimeField(blank=True, help_text='Issue #178 (M1/D1): hora de inicio PLANEADA del bloque (distinta de la asistencia real registrada por miembro). Nullable — no todos los bloques la traen.', null=True, verbose_name='Hora de inicio planeada'),
        ),
        migrations.AddField(
            model_name='cuadrilla',
            name='reprogramado_desde',
            field=models.ForeignKey(blank=True, help_text='Issue #178 (M1/C1): si este bloque nació de reprogramar un bloque existente (botón Reprogramar, pedido C), apunta al bloque origen. El bloque origen NO se borra ni pierde su personal histórico — queda como registro truncado. SET_NULL: si el bloque origen se elimina, esta referencia no rompe.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reprogramaciones', to='cuadrillas.cuadrilla', verbose_name='Reprogramado desde'),
        ),
        migrations.AddField(
            model_name='trackingubicacion',
            name='origen',
            field=models.CharField(choices=[('auto', 'Automático (GPS)'), ('manual', 'Manual')], default='auto', help_text='Issue #178 (M1/F2): distingue una ubicación reportada automáticamente (GPS del dispositivo) de una entrada MANUAL del usuario (pedido F, parte 2 — sitios sin señal). Default auto preserva el comportamiento de todas las filas existentes (tracking hoy siempre viene de GPS).', max_length=10, verbose_name='Origen'),
        ),
    ]
