# Generated by Django 5.1.15 on 2026-07-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0024_migraciones_aditivas_m1_178'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcuadrilla',
            name='area',
            field=models.CharField(blank=True, choices=[('CONSTRUCCION', 'Construcción'), ('MANTENIMIENTO', 'Mantenimiento'), ('FINANCIERO', 'Financiero')], default='', help_text='Área del colaborador (Construcción/Mantenimiento/Financiero) -- issue #186 (186-M4), mismo catálogo que Usuario.area (apps.core.permissions.AREA_CHOICES). blank/default vacío para no romper colaboradores legacy sin área asignada.', max_length=20, verbose_name='Área'),
        ),
    ]
