# Generated by Django 5.1.15 on 2026-08-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0026_asistencia_dia_ganado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadrilla',
            name='tramo_libre',
            field=models.CharField(blank=True, default='', help_text='Issue #223 (A1): descripción libre del tramo operativo. Conserva el FK `tramo` para que las cuadrillas legacy sigan mostrando su catálogo histórico.', max_length=200, verbose_name='Tramo libre'),
        ),
    ]
