# Generated by Django 5.1.15 on 2026-08-16 13:41

from django.db import migrations, models


def sincronizar_estado_legacy(apps, schema_editor):
    """Preserva el significado de las filas creadas antes del catálogo."""
    Vehiculo = apps.get_model('cuadrillas', 'Vehiculo')
    Vehiculo.objects.filter(activo=False).update(estado='INACTIVO')


def reversa_sin_perdida(apps, schema_editor):
    """El booleano legacy no se modifica; eliminar la columna es suficiente."""


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0027_issue_223_tramo_libre'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='descripcion',
            field=models.TextField(blank=True, default='', help_text='Descripción operativa opcional del vehículo.', verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('EN_MANTENIMIENTO', 'En Mantenimiento')], default='ACTIVO', help_text='Catálogo operativo del vehículo. `activo` se conserva como puente compatible para los consumidores legacy.', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('CAMIONETA', 'Camioneta'), ('MOTO', 'Moto'), ('CAMION', 'Camión'), ('GRUA', 'Grúa'), ('OTRO', 'Otro')], default='CAMIONETA', max_length=20, verbose_name='Tipo'),
        ),
        migrations.RunPython(sincronizar_estado_legacy, reversa_sin_perdida),
    ]
