# Generated by Django 5.1.15 on 2026-09-02 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0010_ampliar_aviso_sap_legacy'),
        ('cuadrillas', '0029_asistencia_festivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadrilla',
            name='actividad',
            field=models.ForeignKey(blank=True, help_text='Issue #240 (A1): actividad real seleccionada al programar el bloque. Nullable para conservar bloques históricos que solo tienen una categoría; SET_NULL evita que borrar una actividad invalide su bloque histórico.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloques_programacion_semanal', to='actividades.actividad', verbose_name='Actividad programada'),
        ),
    ]
