"""Issue #237: reemplazo total del catálogo de Colaboradores (PersonalCuadrilla).

Autorizado por el cliente (Indunnova, 2026-09-02) tras confirmar el archivo
normalizado att_09.xlsx: elimina el catálogo completo (484 registros legacy,
con datos Nombre/Documento cruzados y una fila corrupta) y lo reemplaza por
228 filas fuente, excluyendo:
- La fila 2 corrupta (Nombre="1", Documento="2026").
- Los 3 documentos duplicados con datos contradictorios entre sí (cada uno
  aparece 2 veces con el nombre en orden distinto): 71674541, 71002534,
  1063295634 — ambas copias se descartan, quedan 221 filas válidas.

Verificado antes de aplicar (RUN_2026-09-07_0213):
- 0 filas de `construccion_asignacion_personal_proyecto`,
  `construccion_programacion_semanal_personal` o
  `construccion_programacion_semanal_vehiculo` referencian a los 482
  colaboradores legacy que se eliminan (sin impacto CASCADE/SET_NULL real).
- 2 códigos de cargo del archivo (`COORDINADOR_INGENIERIA`,
  `COORDINADOR_TOPOGRAFIA`) exceden los 20 caracteres de `Cargo.codigo` y
  se normalizan a los códigos truncados ya existentes en el catálogo
  (`COORDINADOR_INGENIE`, `COORDINADOR_TOPOGRAF`).
- `documento` se guarda como dígitos planos (sin separador de miles); el
  filtro de plantilla `intcomma` ya formatea ambos estilos sin duplicar
  separadores.
"""

from django.db import migrations

COLABORADORES = [
    {
        "nombre": "ABRAHAM PAYARES JIMENEZ",
        "documento": "1090434209",
        "cargo": "LINIERO_I",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "ADOLFO JUNIOR CASTRO PINTO",
        "documento": "1083020533",
        "cargo": "LINIERO_I",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "ALBERTO ARTETA JIMENEZ",
        "documento": "1044393356",
        "cargo": "LINIERO_I",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "ALEXANDER HEREIRA FONTALVO",
        "documento": "8573829",
        "cargo": "LINIERO_I",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "ALFONSO LOPEZ SARMIENTO",
        "documento": "1042438483",
        "cargo": "LINIERO_I",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "Andrea",
        "documento": "43482087",
        "cargo": "LINIERO_I",
        "area": "Mantenimiento",
        "salario_base": 15000.0,
        "fecha_ingreso": "2026-07-01",
        "fecha_salida": "2026-07-31",
    },
    {
        "nombre": "AUGUSTO CONRADO LUGO",
        "documento": "72099572",
        "cargo": "LINIERO_I",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "BORIS ELIAS PACHON RAMOS",
        "documento": "72186195",
        "cargo": "CONDUCTOR",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "CAMILO BUELVAS ARRIETA",
        "documento": "1043662512",
        "cargo": "LINIERO_I",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "CARLOS ALBERTO VELEZ SALAZAR",
        "documento": "10180923",
        "cargo": "LINIERO_I",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "CARLOS JIMENEZ GUERRERO",
        "documento": "1129576586",
        "cargo": "LINIERO_I",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "CASIMIRO PALOMINO ARMESTO",
        "documento": "72015917",
        "cargo": "SUPERVISOR",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "CESAR FABIAN GUARIN",
        "documento": "1005327412",
        "cargo": "LINIERO_II",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "DAGOBERTO PINEDA OSPINO",
        "documento": "72307057",
        "cargo": "LINIERO_II",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "DANIEL MARTINEZ BARRETO",
        "documento": "1005584828",
        "cargo": "LINIERO_I",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "DINAEL NAVARRO ROMERO",
        "documento": "72144884",
        "cargo": "LINIERO_II",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "ELKIN CASTRO VEGA",
        "documento": "1143455447",
        "cargo": "CONDUCTOR",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "GUSTAVO ENRIQUE SOLANO MARTINEZ",
        "documento": "72250933",
        "cargo": "LINIERO_I",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "HECTOR CARVAJAL RODRIGUEZ",
        "documento": "1118469059",
        "cargo": "LINIERO_I",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "IVAN RAFAEL CRUZATE SARABIA",
        "documento": "73266972",
        "cargo": "LINIERO_I",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "JAIRO MANUEL RIVERO BELTRAN",
        "documento": "1067286264",
        "cargo": "LINIERO_II",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "JEFERSON YAHIR JEREZ BELTRAN",
        "documento": "1125758102",
        "cargo": "LINIERO_I",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "JEISON JAVIER PALOMINO SERRANO",
        "documento": "1048214031",
        "cargo": "LINIERO_II",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "JESUS DAVID CUESTA OROZCO",
        "documento": "1192768532",
        "cargo": "CONDUCTOR",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "JHERFERSON VIDALES CENTENO",
        "documento": "1050065012",
        "cargo": "LINIERO_I",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "JHONATHAN MORALES DIAZ",
        "documento": "1045744006",
        "cargo": "CONDUCTOR",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "JHON JAIRO JIMENEZ",
        "documento": "1143246675",
        "cargo": "LINIERO_I",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "JOAQUIN IGNACIO LEONES CARRILLO",
        "documento": "8648652",
        "cargo": "LINIERO_I",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "JOEL LOBO MENDOZA",
        "documento": "1042995759",
        "cargo": "LINIERO_II",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "JORGE ELIECER MARTINEZ MAESTRE",
        "documento": "84103590",
        "cargo": "CONDUCTOR",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "JORGE LUIS FUENTES RIOBO",
        "documento": "1066085217",
        "cargo": "LINIERO_I",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "JORGE LUIS LANS SULBARAN",
        "documento": "8642314",
        "cargo": "LINIERO_I",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "JUAN CARLOS DAZA GARCIA",
        "documento": "1065564564",
        "cargo": "CONDUCTOR",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "JUAN CARLOS TELLES HERRERA",
        "documento": "72145205",
        "cargo": "CONDUCTOR",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "JUAN PABLO OCHOA BARRIOS",
        "documento": "1134330035",
        "cargo": "LINIERO_I",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "JUAN PAULO PARADA URBINA",
        "documento": "1093413680",
        "cargo": "LINIERO_II",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "JULIO CESAR PICHON RAMOS",
        "documento": "1042417022",
        "cargo": "CONDUCTOR",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "KEINER JULIANO SERRANO PALLARES",
        "documento": "1004487321",
        "cargo": "LINIERO_II",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "KENNEDY GONZALEZ OSPINO",
        "documento": "85437704",
        "cargo": "LINIERO_I",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "LUIS ALFREDO PERTUZ CANTILLO",
        "documento": "1004381641",
        "cargo": "LINIERO_II",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "LUIS DIAZ GODOY",
        "documento": "1042999479",
        "cargo": "LINIERO_I",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "MANUEL ANTONIO BEGAMBRE BASIL",
        "documento": "15612373",
        "cargo": "LINIERO_I",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "MANUEL ANTONIO ZARZA GALVAN",
        "documento": "1037472307",
        "cargo": "LINIERO_I",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "MANUEL ENRIQUE DITA LOBO",
        "documento": "8641082",
        "cargo": "LINIERO_I",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "NILSON MARE NAVARO",
        "documento": "1064800051",
        "cargo": "LINIERO_I",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "NOLMER MANUEL LOPEZ DIAZ",
        "documento": "1045435016",
        "cargo": "LINIERO_I",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "OBEIRO MEJIA JIMENEZ",
        "documento": "1148438067",
        "cargo": "LINIERO_I",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "OCTAVIO ANTONIO BAÑOS ARIAS",
        "documento": "72095171",
        "cargo": "CONDUCTOR",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "OMAR ALFREDO MANTILLA CABALLERO",
        "documento": "8649005",
        "cargo": "LINIERO_II",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "PEDRO ANTONIO SANMARTIN BLANCO",
        "documento": "98687561",
        "cargo": "LINIERO_I",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "RAFAEL ENRIQUE PACHECO ROMERO",
        "documento": "72132633",
        "cargo": "CONDUCTOR",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "RAFAEL IGNACIO PARRA VALLE",
        "documento": "1002237248",
        "cargo": "CONDUCTOR",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": "2026-08-03",
        "fecha_salida": None,
    },
    {
        "nombre": "SAMITH RAFAEL MERCADO DE LA HOZ",
        "documento": "1043027776",
        "cargo": "CONDUCTOR",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "SNEYDER ELISEO JEREZ BELTRAN",
        "documento": "1093293706",
        "cargo": "LINIERO_II",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "TAIRO MIGUEL CUESTA MORRIS",
        "documento": "1143457338",
        "cargo": "CONDUCTOR",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "WALDY SMITH FONSECA NIEBLES",
        "documento": "72435608",
        "cargo": "LINIERO_II",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "WILLIAM ESTRADA MALDONADO",
        "documento": "1129526934",
        "cargo": "LINIERO_I",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "YEISON CRUZ NAVARRO",
        "documento": "1123405494",
        "cargo": "LINIERO_I",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "YESID ALFONSO BARRIOS ALANDETE",
        "documento": "72135975",
        "cargo": "LINIERO_II",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "YESID DAVID BARRIOS ARIZA",
        "documento": "1048210222",
        "cargo": "LINIERO_II",
        "area": "Mantenimiento",
        "salario_base": 0,
        "fecha_ingreso": None,
        "fecha_salida": None,
    },
    {
        "nombre": "OLARTE NUÑEZ LUIS GONZALO",
        "documento": "93369300",
        "cargo": "COORDINADOR_SOCIAL",
        "area": "Construcción",
        "salario_base": 6000000.0,
        "fecha_ingreso": "2024-08-07",
        "fecha_salida": "2026-02-18",
    },
    {
        "nombre": "MARTINEZ SANTANA JOSE DEL CARMEN",
        "documento": "79165072",
        "cargo": "SUPERVISOR_TECNICO",
        "area": "Construcción",
        "salario_base": 3500000.0,
        "fecha_ingreso": "2024-08-07",
        "fecha_salida": "2025-11-23",
    },
    {
        "nombre": "ZEA CARDENAS OSCAR JAVIER",
        "documento": "91074638",
        "cargo": "COORDINADOR_TOPOGRAF",
        "area": "Construcción",
        "salario_base": 4000000.0,
        "fecha_ingreso": "2024-08-08",
        "fecha_salida": "2025-11-30",
    },
    {
        "nombre": "ARCINIEGAS PINTO WILLIAM JESUS",
        "documento": "13460866",
        "cargo": "GESTOR_SOCIAL",
        "area": "Construcción",
        "salario_base": 3500000.0,
        "fecha_ingreso": "2024-08-26",
        "fecha_salida": "2024-11-07",
    },
    {
        "nombre": "GUTIERREZ GARCIA RODRIGO ADOLFO",
        "documento": "1018458319",
        "cargo": "ING_CIVIL_GEOTECNIA",
        "area": "Construcción",
        "salario_base": 5000000.0,
        "fecha_ingreso": "2024-09-23",
        "fecha_salida": "2025-08-02",
    },
    {
        "nombre": "SALINAS JIMENEZ LUIS GONZALO",
        "documento": "93438647",
        "cargo": "BIOLOGO",
        "area": "Construcción",
        "salario_base": 4000000.0,
        "fecha_ingreso": "2024-11-25",
        "fecha_salida": "2025-08-22",
    },
    {
        "nombre": "MARTINEZ ECHAVARRIA LUIS DARIO",
        "documento": "98464834",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1500000.0,
        "fecha_ingreso": "2024-11-25",
        "fecha_salida": "2026-03-21",
    },
    {
        "nombre": "RIVAS HURTADO JOSE AVILES",
        "documento": "11636466",
        "cargo": "OFICIAL_2",
        "area": "Construcción",
        "salario_base": 2000000.0,
        "fecha_ingreso": "2024-11-25",
        "fecha_salida": None,
    },
    {
        "nombre": "MORA TABORDA FREDY EDUARDO",
        "documento": "8154171",
        "cargo": "OFICIAL_2",
        "area": "Construcción",
        "salario_base": 2000000.0,
        "fecha_ingreso": "2024-11-25",
        "fecha_salida": None,
    },
    {
        "nombre": "MACIAS BELLIDO WILSON ENRIQUE",
        "documento": "78305192",
        "cargo": "SUPERVISOR_SST",
        "area": "Construcción",
        "salario_base": 2500000.0,
        "fecha_ingreso": "2024-11-25",
        "fecha_salida": "2025-03-04",
    },
    {
        "nombre": "RIVERA LORA HAMILTON DANIEL",
        "documento": "1048017764",
        "cargo": "CONDUCTOR",
        "area": "Construcción",
        "salario_base": 1300000.0,
        "fecha_ingreso": "2024-11-25",
        "fecha_salida": None,
    },
    {
        "nombre": "TRIVIÑO RIOS GALY ALEXANDER",
        "documento": "1043001163",
        "cargo": "CONDUCTOR",
        "area": "Construcción",
        "salario_base": 1300000.0,
        "fecha_ingreso": "2024-11-25",
        "fecha_salida": None,
    },
    {
        "nombre": "ZAPATA DAZA OLIVERIO",
        "documento": "71002240",
        "cargo": "OFICIAL_2",
        "area": "Construcción",
        "salario_base": 2000000.0,
        "fecha_ingreso": "2024-11-25",
        "fecha_salida": None,
    },
    {
        "nombre": "GIRALDO DELGADO JOHAN SEBASTIAN",
        "documento": "1053833357",
        "cargo": "ARQUEOLOGO",
        "area": "Construcción",
        "salario_base": 3000000.0,
        "fecha_ingreso": "2024-11-25",
        "fecha_salida": "2025-11-23",
    },
    {
        "nombre": "RUEDA RUEDA ANGELICA",
        "documento": "37581017",
        "cargo": "PROFESIONAL_CALIDAD",
        "area": "Construcción",
        "salario_base": 2938289.0,
        "fecha_ingreso": "2020-03-16",
        "fecha_salida": "2026-03-21",
    },
    {
        "nombre": "LOPEZ HERNANDEZ ANDRES FELIPE",
        "documento": "1097037991",
        "cargo": "TOPOGRAFO",
        "area": "Construcción",
        "salario_base": 3000000.0,
        "fecha_ingreso": "2024-11-25",
        "fecha_salida": "2025-11-24",
    },
    {
        "nombre": "PULGARIN PALACIO DALADIER",
        "documento": "71189647",
        "cargo": "SUPERVISOR_TECNICO",
        "area": "Construcción",
        "salario_base": 3000000.0,
        "fecha_ingreso": "2024-11-25",
        "fecha_salida": "2025-04-26",
    },
    {
        "nombre": "GUERRA DIAZ DEIMER JOSE",
        "documento": "1108762978",
        "cargo": "CADENERO",
        "area": "Construcción",
        "salario_base": 1350000.0,
        "fecha_ingreso": "2024-11-27",
        "fecha_salida": "2025-11-30",
    },
    {
        "nombre": "FLOREZ GALLEGO EDISON JULIAN",
        "documento": "70729628",
        "cargo": "ALMACENISTA",
        "area": "Construcción",
        "salario_base": 2000000.0,
        "fecha_ingreso": "2024-10-07",
        "fecha_salida": "2026-01-18",
    },
    {
        "nombre": "BOCANEGRA HENAO HELY",
        "documento": "93337680",
        "cargo": "CONDUCTOR",
        "area": "Construcción",
        "salario_base": 1300000.0,
        "fecha_ingreso": "2024-12-02",
        "fecha_salida": "2025-10-15",
    },
    {
        "nombre": "BRAVO GOMEZ ORLANDO",
        "documento": "98575135",
        "cargo": "ADMINISTRADOR_OBRA",
        "area": "Construcción",
        "salario_base": 3000000.0,
        "fecha_ingreso": "2024-11-25",
        "fecha_salida": "2026-03-21",
    },
    {
        "nombre": "GOMEZ MACIAS IVAN DARIO",
        "documento": "70135861",
        "cargo": "CONDUCTOR_MAQUINARIA",
        "area": "Construcción",
        "salario_base": 1800000.0,
        "fecha_ingreso": "2024-11-25",
        "fecha_salida": "2025-11-04",
    },
    {
        "nombre": "VALENCIA SANTAMARIA GABRIEL",
        "documento": "91109552",
        "cargo": "COORDINADOR_INGENIE",
        "area": "Construcción",
        "salario_base": 6000000.0,
        "fecha_ingreso": "2024-12-02",
        "fecha_salida": "2026-03-21",
    },
    {
        "nombre": "ARRIETA ARRIETA YULIETH SUSANA",
        "documento": "1071351112",
        "cargo": "AUXILIAR_SERVICIOS",
        "area": "Construcción",
        "salario_base": 1300000.0,
        "fecha_ingreso": "2024-12-10",
        "fecha_salida": "2025-11-18",
    },
    {
        "nombre": "HERNANDEZ NAVARRO JAIRO ANTONIO",
        "documento": "1082867878",
        "cargo": "GESTOR_AMBIENTAL",
        "area": "Construcción",
        "salario_base": 3000000.0,
        "fecha_ingreso": "2025-01-07",
        "fecha_salida": "2025-01-07",
    },
    {
        "nombre": "NUÑEZ MUNEVAR JUAN SEBASTIAN",
        "documento": "1106334389",
        "cargo": "CONDUCTOR",
        "area": "Construcción",
        "salario_base": 1300000.0,
        "fecha_ingreso": "2025-01-07",
        "fecha_salida": "2025-12-11",
    },
    {
        "nombre": "CARVAJAL GARCIA SOFIA ALEJANDRA",
        "documento": "1095812596",
        "cargo": "GESTOR_SOCIAL",
        "area": "Construcción",
        "salario_base": 3500000.0,
        "fecha_ingreso": "2025-01-07",
        "fecha_salida": "2025-12-15",
    },
    {
        "nombre": "RAMIREZ TINOCO OSCAR ENRIQUE",
        "documento": "14320944",
        "cargo": "CONDUCTOR",
        "area": "Construcción",
        "salario_base": 1300000.0,
        "fecha_ingreso": "2024-11-25",
        "fecha_salida": "2025-01-13",
    },
    {
        "nombre": "EDILBERTO GALLEGO CARDENAS",
        "documento": "10175516",
        "cargo": "CONDUCTOR",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-01-13",
        "fecha_salida": "2025-12-10",
    },
    {
        "nombre": "CALLE EUSE WILSON DE JESUS",
        "documento": "76703015",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2024-11-25",
        "fecha_salida": "2026-03-04",
    },
    {
        "nombre": "OSORIO GUAPACHA JOHN SEBASTIAN",
        "documento": "1096038607",
        "cargo": "TOPOGRAFO",
        "area": "Construcción",
        "salario_base": 3000000.0,
        "fecha_ingreso": "2025-01-15",
        "fecha_salida": "2025-02-07",
    },
    {
        "nombre": "GARCIA MARIN JORGE IVAN",
        "documento": "70950516",
        "cargo": "CONDUCTOR_GRUA",
        "area": "Construcción",
        "salario_base": 2000000.0,
        "fecha_ingreso": "2024-11-25",
        "fecha_salida": "2026-03-21",
    },
    {
        "nombre": "RESTREPO YARCE SANTIAGO ALONSO",
        "documento": "1007114556",
        "cargo": "OFICIAL_2",
        "area": "Construcción",
        "salario_base": 1500000.0,
        "fecha_ingreso": "2025-01-24",
        "fecha_salida": "2025-08-25",
    },
    {
        "nombre": "GUARIN LOPEZ WILTON ARIEL",
        "documento": "1001452638",
        "cargo": "OFICIAL_2",
        "area": "Construcción",
        "salario_base": 1500000.0,
        "fecha_ingreso": "2025-01-24",
        "fecha_salida": "2025-06-30",
    },
    {
        "nombre": "GUARIN LOPEZ LEONARDO",
        "documento": "1001452344",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-01-24",
        "fecha_salida": "2025-03-28",
    },
    {
        "nombre": "ZAPATA ARDILA EDWIN ALEXANDER",
        "documento": "1037072295",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1500000.0,
        "fecha_ingreso": "2025-01-24",
        "fecha_salida": None,
    },
    {
        "nombre": "BOLAÑOS MARTINEZ JAIRO",
        "documento": "12749841",
        "cargo": "APAREJADOR",
        "area": "Construcción",
        "salario_base": 1600000.0,
        "fecha_ingreso": "2025-01-27",
        "fecha_salida": "2025-08-21",
    },
    {
        "nombre": "HERNANDEZ GONZALEZ JOAQUIN ELADIO",
        "documento": "98601774",
        "cargo": "CONDUCTOR",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-02-06",
        "fecha_salida": "2026-03-21",
    },
    {
        "nombre": "MEJIA TORRES LUIS ENRIQUE",
        "documento": "9977173",
        "cargo": "CADENERO",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-02-03",
        "fecha_salida": "2025-12-02",
    },
    {
        "nombre": "BERMUDEZ MORENO YULIANA",
        "documento": "1042065209",
        "cargo": "GESTOR_AMBIENTAL",
        "area": "Construcción",
        "salario_base": 3500000.0,
        "fecha_ingreso": "2025-02-03",
        "fecha_salida": "2025-03-14",
    },
    {
        "nombre": "MAHECHA MORENO CARLOS ALBERTO",
        "documento": "91441268",
        "cargo": "PATIERO",
        "area": "Construcción",
        "salario_base": 5000000.0,
        "fecha_ingreso": "2025-02-06",
        "fecha_salida": "2025-11-15",
    },
    {
        "nombre": "ARDILA CORREA JOSE ALEJANDRO",
        "documento": "1001218082",
        "cargo": "OFICIAL_PODA",
        "area": "Construcción",
        "salario_base": 2047000.0,
        "fecha_ingreso": "2025-02-03",
        "fecha_salida": "2025-03-09",
    },
    {
        "nombre": "CONTRERAS DURAN YAN CARLOS",
        "documento": "19708758",
        "cargo": "CONDUCTOR",
        "area": "Construcción",
        "salario_base": 1600000.0,
        "fecha_ingreso": "2025-02-03",
        "fecha_salida": "2026-01-18",
    },
    {
        "nombre": "MONTALVO VERA JOSE ANGEL",
        "documento": "1038116760",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-02-03",
        "fecha_salida": "2025-05-02",
    },
    {
        "nombre": "ACEVEDO PEREZ JHOAN SEBASTIAN",
        "documento": "1097038257",
        "cargo": "TOPOGRAFO",
        "area": "Construcción",
        "salario_base": 3000000.0,
        "fecha_ingreso": "2025-02-07",
        "fecha_salida": "2025-07-28",
    },
    {
        "nombre": "BERNAL BARRERA JONATHAN",
        "documento": "1116555394",
        "cargo": "SUPERVISOR_SST",
        "area": "Construcción",
        "salario_base": 2500000.0,
        "fecha_ingreso": "2025-02-06",
        "fecha_salida": "2025-10-18",
    },
    {
        "nombre": "PAVA SUAREZ PAULA ANDREA",
        "documento": "1111204522",
        "cargo": "AUXILIAR_SOCIAL",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-01-30",
        "fecha_salida": "2025-10-30",
    },
    {
        "nombre": "ROMERO FALLA HANER ADRIAN",
        "documento": "12208828",
        "cargo": "SUPERVISOR_SST",
        "area": "Construcción",
        "salario_base": 2500000.0,
        "fecha_ingreso": "2025-02-18",
        "fecha_salida": "2025-03-02",
    },
    {
        "nombre": "VALENCIA BUSTOS MAYCOL GUSTAVO",
        "documento": "1005777013",
        "cargo": "CONDUCTOR",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-02-21",
        "fecha_salida": "2025-03-28",
    },
    {
        "nombre": "ACOSTA ACERO ANDERSON ELIAS",
        "documento": "1110458422",
        "cargo": "CONDUCTOR",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-02-21",
        "fecha_salida": "2026-02-04",
    },
    {
        "nombre": "PEÑA SEGURA JONATHAN ANDRES",
        "documento": "1110521948",
        "cargo": "SUPERVISOR_SST",
        "area": "Construcción",
        "salario_base": 1800000.0,
        "fecha_ingreso": "2025-02-21",
        "fecha_salida": "2025-12-10",
    },
    {
        "nombre": "JIMENEZ GOMEZ MIGUEL ANGEL",
        "documento": "71659631",
        "cargo": "OFICIAL_PATIO",
        "area": "Construcción",
        "salario_base": 2300000.0,
        "fecha_ingreso": "2025-02-24",
        "fecha_salida": "2025-12-01",
    },
    {
        "nombre": "TERNERA JIMENEZ ANGEL ALFREDO",
        "documento": "1081820966",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-02-24",
        "fecha_salida": "2025-12-01",
    },
    {
        "nombre": "OVALLOS CALDERON MARYORI ESMERALDA",
        "documento": "1091183144",
        "cargo": "SUPERVISOR_SST",
        "area": "Construcción",
        "salario_base": 2500000.0,
        "fecha_ingreso": "2025-03-10",
        "fecha_salida": "2025-04-12",
    },
    {
        "nombre": "VARGAS RIVADENEIRA CARLOS DAVID",
        "documento": "1118826988",
        "cargo": "GEOTECNISTA",
        "area": "Construcción",
        "salario_base": 4000000.0,
        "fecha_ingreso": "2025-03-10",
        "fecha_salida": "2025-04-20",
    },
    {
        "nombre": "MOYA LOPEZ NATALIA",
        "documento": "1115092570",
        "cargo": "ARQUEOLOGO",
        "area": "Construcción",
        "salario_base": 3000000.0,
        "fecha_ingreso": "2025-03-14",
        "fecha_salida": "2025-09-12",
    },
    {
        "nombre": "OSPINA RODRIGUEZ HECTOR MANUEL",
        "documento": "2235472",
        "cargo": "SUPERVISOR_SST",
        "area": "Construcción",
        "salario_base": 2500000.0,
        "fecha_ingreso": "2025-03-17",
        "fecha_salida": "2025-09-12",
    },
    {
        "nombre": "RODRIGUEZ PEÑA ORLANDO ENRIQUE",
        "documento": "8642053",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-03-05",
        "fecha_salida": "2025-06-30",
    },
    {
        "nombre": "MARTINEZ PARDO JHON EDWARD",
        "documento": "1006148375",
        "cargo": "TOPOGRAFO",
        "area": "Construcción",
        "salario_base": 2000000.0,
        "fecha_ingreso": "2025-03-25",
        "fecha_salida": "2025-08-20",
    },
    {
        "nombre": "DAZA GONZALEZ SANDRA MILENA",
        "documento": "52784478",
        "cargo": "GESTOR_AMBIENTAL",
        "area": "Construcción",
        "salario_base": 3500000.0,
        "fecha_ingreso": "2025-04-01",
        "fecha_salida": "2025-11-10",
    },
    {
        "nombre": "RINCON QUINTERO JOHNY JAIR",
        "documento": "13271327",
        "cargo": "MECANICO_CONDUCTOR",
        "area": "Construcción",
        "salario_base": 2000000.0,
        "fecha_ingreso": "2025-04-07",
        "fecha_salida": "2025-10-11",
    },
    {
        "nombre": "MOTTA GARCIA CARLOS ALBERTO",
        "documento": "1069175133",
        "cargo": "CONDUCTOR_MAQUINARIA",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-04-08",
        "fecha_salida": "2025-12-02",
    },
    {
        "nombre": "SERNA CARDONA MARIA ALEJANDRA",
        "documento": "1036610452",
        "cargo": "SUPERVISOR_SST",
        "area": "Construcción",
        "salario_base": 2500000.0,
        "fecha_ingreso": "2025-04-08",
        "fecha_salida": "2025-12-01",
    },
    {
        "nombre": "ROJAS CONTRERAS MISAEL",
        "documento": "74754883",
        "cargo": "SUPERVISOR_TECNICO",
        "area": "Construcción",
        "salario_base": 3000000.0,
        "fecha_ingreso": "2025-04-07",
        "fecha_salida": "2025-12-01",
    },
    {
        "nombre": "MEJIA URIBE ANGEL DE DIOS",
        "documento": "98464013",
        "cargo": "ENCARGADO_CUADRILLA",
        "area": "Construcción",
        "salario_base": 2300000.0,
        "fecha_ingreso": "2025-04-09",
        "fecha_salida": "2025-12-04",
    },
    {
        "nombre": "MURILLO BENITEZ ANGEL MIGUEL",
        "documento": "15682225",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-04-08",
        "fecha_salida": "2025-12-02",
    },
    {
        "nombre": "MURILLO TRONCOSO CARLOS ALBERTO",
        "documento": "1003367904",
        "cargo": "CADENERO",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-04-08",
        "fecha_salida": "2025-06-27",
    },
    {
        "nombre": "GONZALEZ HERRERA JOSE HIDALGO",
        "documento": "1066092279",
        "cargo": "CONDUCTOR",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-04-08",
        "fecha_salida": "2025-09-30",
    },
    {
        "nombre": "RUDA CARLOS ALBERTO",
        "documento": "98452457",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-04-14",
        "fecha_salida": "2025-07-02",
    },
    {
        "nombre": "RIVERA BARBA SAMUEL",
        "documento": "1007410178",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-04-14",
        "fecha_salida": "2025-07-29",
    },
    {
        "nombre": "HERRERA POBRE DANIEL EDUARDO",
        "documento": "1079508223",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-04-10",
        "fecha_salida": "2025-06-18",
    },
    {
        "nombre": "HERRAN ZARATE JORGE ELIECER",
        "documento": "93436530",
        "cargo": "CONDUCTOR",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-04-08",
        "fecha_salida": "2025-09-15",
    },
    {
        "nombre": "ECHEVERRI DIAZ JORGE ELIECER",
        "documento": "79959066",
        "cargo": "CONDUCTOR",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-04-10",
        "fecha_salida": "2025-12-01",
    },
    {
        "nombre": "CARMONA OROZCO CRISTIAN ALEXIS",
        "documento": "1140841628",
        "cargo": "SUPERVISOR_SST",
        "area": "Construcción",
        "salario_base": 2500000.0,
        "fecha_ingreso": "2025-04-16",
        "fecha_salida": "2026-02-23",
    },
    {
        "nombre": "LIZARAZO PRADA CAMILO ANDRES - piolin CONTE",
        "documento": "1005147225",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-04-15",
        "fecha_salida": "2025-11-30",
    },
    {
        "nombre": "PERDOMO TRUJILLO RUBVER ANDREY",
        "documento": "1079409283",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-04-15",
        "fecha_salida": "2025-12-02",
    },
    {
        "nombre": "DIAZ RODRIGUEZ EDINSON",
        "documento": "1090453314",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-04-15",
        "fecha_salida": "2025-10-31",
    },
    {
        "nombre": "HURTADO VASQUEZ YON FREDY",
        "documento": "9993178",
        "cargo": "MALACATERO",
        "area": "Construcción",
        "salario_base": 2500000.0,
        "fecha_ingreso": "2025-04-22",
        "fecha_salida": "2025-11-28",
    },
    {
        "nombre": "FERIA MORENO ELIAN CAMILO",
        "documento": "1007950198",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-04-15",
        "fecha_salida": "2025-05-01",
    },
    {
        "nombre": "FONTECHA AMESQUITA JOHN JAIRO",
        "documento": "1000352481",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-04-15",
        "fecha_salida": "2025-06-06",
    },
    {
        "nombre": "JAIMES AYALA JOSE MANUEL",
        "documento": "1005450223",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-04-22",
        "fecha_salida": "2025-07-05",
    },
    {
        "nombre": "GARCIA PUELLO YERFRY MANUEL",
        "documento": "1003115234",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-04-22",
        "fecha_salida": "2025-07-30",
    },
    {
        "nombre": "CRUZ EDGAR OVIDIO",
        "documento": "76276573",
        "cargo": "SUPERVISOR_TECNICO",
        "area": "Construcción",
        "salario_base": 3000000.0,
        "fecha_ingreso": "2025-04-17",
        "fecha_salida": "2025-10-30",
    },
    {
        "nombre": "CARVAJALINO TELLEZ RAMON EUCLIDES",
        "documento": "77032033",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-04-22",
        "fecha_salida": "2025-12-04",
    },
    {
        "nombre": "AGUIRRE GONZALEZ YACSON CALER",
        "documento": "1037972892",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-04-15",
        "fecha_salida": "2025-06-18",
    },
    {
        "nombre": "CANO ALVAREZ JAHIR RODRIGO",
        "documento": "7919697",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1600000.0,
        "fecha_ingreso": "2025-04-22",
        "fecha_salida": "2025-07-06",
    },
    {
        "nombre": "OSORIO MORA MAICOL JOSE",
        "documento": "1005512378",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-04-22",
        "fecha_salida": "2025-06-08",
    },
    {
        "nombre": "HERNANDEZ MEZA ABIMAEL",
        "documento": "92549439",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1600000.0,
        "fecha_ingreso": "2025-04-22",
        "fecha_salida": "2025-07-31",
    },
    {
        "nombre": "QUINTANA JIMENEZ JAIRO",
        "documento": "16216809",
        "cargo": "TOPOGRAFO",
        "area": "Construcción",
        "salario_base": 3000000.0,
        "fecha_ingreso": "2025-04-22",
        "fecha_salida": "2025-08-31",
    },
    {
        "nombre": "CANTUCA BLANDON WILMAR ALEXANDER",
        "documento": "1085264218",
        "cargo": "GEOTECNISTA",
        "area": "Construcción",
        "salario_base": 5000000.0,
        "fecha_ingreso": "2025-04-23",
        "fecha_salida": "2025-09-10",
    },
    {
        "nombre": "LOPEZ TORDECILLA NAFER JOSE",
        "documento": "1040369908",
        "cargo": "SUPERVISOR_SST",
        "area": "Construcción",
        "salario_base": 2500000.0,
        "fecha_ingreso": "2025-04-25",
        "fecha_salida": "2025-11-24",
    },
    {
        "nombre": "BONET MORENO LUIS ALFONSO",
        "documento": "1091532387",
        "cargo": "SUPERVISOR_TECNICO",
        "area": "Construcción",
        "salario_base": 3500000.0,
        "fecha_ingreso": "2025-05-09",
        "fecha_salida": "2025-12-17",
    },
    {
        "nombre": "CARDENAS MARTINEZ JAIR ARIEL",
        "documento": "1019051730",
        "cargo": "ING_RESIDENTE",
        "area": "Construcción",
        "salario_base": 6000000.0,
        "fecha_ingreso": "2025-04-29",
        "fecha_salida": "2025-12-19",
    },
    {
        "nombre": "DIAZ ROSSINE ROBERTO JOSE",
        "documento": "1052077225",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-04-22",
        "fecha_salida": "2025-12-02",
    },
    {
        "nombre": "SUAREZ VANEGAS ANDRES FELIPE",
        "documento": "1110538379",
        "cargo": "CONDUCTOR",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-04-29",
        "fecha_salida": "2025-10-31",
    },
    {
        "nombre": "GARCIA CONTRERAS CAMILO",
        "documento": "14326396",
        "cargo": "CONDUCTOR",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-04-29",
        "fecha_salida": "2025-05-16",
    },
    {
        "nombre": "COLMENARES VEGA JHON ANGEL",
        "documento": "9692582",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-05-10",
        "fecha_salida": "2025-12-01",
    },
    {
        "nombre": "SALAZAR BENAVIDES EDUARDO (conte)",
        "documento": "1007785762",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-04-25",
        "fecha_salida": "2025-12-01",
    },
    {
        "nombre": "MONTILLA JOJOA ANDERSON OSWALDO (entrega)",
        "documento": "1084227024",
        "cargo": "OFICIAL_2",
        "area": "Construcción",
        "salario_base": 2400000.0,
        "fecha_ingreso": "2025-05-06",
        "fecha_salida": "2025-11-24",
    },
    {
        "nombre": "DIAZ ALCAZAR SANDRA PATRICIA",
        "documento": "65811365",
        "cargo": "SUPERVISOR_SST",
        "area": "Construcción",
        "salario_base": 2800000.0,
        "fecha_ingreso": "2025-05-12",
        "fecha_salida": "2025-10-19",
    },
    {
        "nombre": "SULBARAN DIAZ NILSON GUILLERMO",
        "documento": "8650201",
        "cargo": "CONDUCTOR",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-05-13",
        "fecha_salida": "2025-09-30",
    },
    {
        "nombre": "TORO COTERA MIGUEL EMIRO",
        "documento": "11052312",
        "cargo": "ENCARGADO_CUADRILLA",
        "area": "Construcción",
        "salario_base": 2900000.0,
        "fecha_ingreso": "2025-05-12",
        "fecha_salida": "2025-11-10",
    },
    {
        "nombre": "CASTILLO ALFONSO GERMAN",
        "documento": "1048846382",
        "cargo": "ENCARGADO_CUADRILLA",
        "area": "Construcción",
        "salario_base": 2500000.0,
        "fecha_ingreso": "2025-05-12",
        "fecha_salida": "2025-06-30",
    },
    {
        "nombre": "FORERO VELEZ ORLANDO",
        "documento": "1096197262",
        "cargo": "SUPERVISOR_SST",
        "area": "Construcción",
        "salario_base": 2500000.0,
        "fecha_ingreso": "2025-05-16",
        "fecha_salida": "2025-07-04",
    },
    {
        "nombre": "DE ARCOS RENTERIA LUIS EDUARDO",
        "documento": "1047424191",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-04-30",
        "fecha_salida": "2025-07-18",
    },
    {
        "nombre": "GARCIA ORTIZ DIEGO ANDRES",
        "documento": "1083559598",
        "cargo": "SUPERVISOR_SST",
        "area": "Construcción",
        "salario_base": 2500000.0,
        "fecha_ingreso": "2025-05-16",
        "fecha_salida": "2025-07-04",
    },
    {
        "nombre": "LONDOÑO VARGAS ALFONSO",
        "documento": "5904982",
        "cargo": "CONDUCTOR",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-05-13",
        "fecha_salida": "2025-12-05",
    },
    {
        "nombre": "JIMENEZ ROA CESAR MANUEL",
        "documento": "79720698",
        "cargo": "CONDUCTOR",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-05-22",
        "fecha_salida": "2025-11-20",
    },
    {
        "nombre": "ZAPATA MAZO JORGE ELI",
        "documento": "1035128748",
        "cargo": "AUXILIAR_SERVICIOS",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-05-21",
        "fecha_salida": "2025-07-19",
    },
    {
        "nombre": "CAMARGO LOPEZ LEIVER MANUEL",
        "documento": "1038646033",
        "cargo": "AUXILIAR_SERVICIOS",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-05-21",
        "fecha_salida": "2025-07-19",
    },
    {
        "nombre": "CORREA MAZO RUBIEL OTILIO",
        "documento": "98614856",
        "cargo": "AUXILIAR_SERVICIOS",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-05-21",
        "fecha_salida": "2025-07-19",
    },
    {
        "nombre": "ZAPATA MAZO JHON JAIME",
        "documento": "1035129175",
        "cargo": "AUXILIAR_SERVICIOS",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-05-21",
        "fecha_salida": "2025-07-19",
    },
    {
        "nombre": "RAMIREZ CEBALLOS NERIS DE JESUS",
        "documento": "21592403",
        "cargo": "AUXILIAR_SERVICIOS",
        "area": "Construcción",
        "salario_base": 1500000.0,
        "fecha_ingreso": "2025-02-17",
        "fecha_salida": "2026-03-21",
    },
    {
        "nombre": "JARAMILLO OCAMPO DANIEL",
        "documento": "1047971212",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-05-20",
        "fecha_salida": "2025-12-01",
    },
    {
        "nombre": "SUAREZ RAGA LUIS GUILLERMO",
        "documento": "93436846",
        "cargo": "SUPERVISOR_SST",
        "area": "Construcción",
        "salario_base": 2500000.0,
        "fecha_ingreso": "2025-05-23",
        "fecha_salida": "2025-11-24",
    },
    {
        "nombre": "MADRID MUNDOY DAVID ENRIQUE",
        "documento": "1044917818",
        "cargo": "OFICIAL_2",
        "area": "Construcción",
        "salario_base": 2000000.0,
        "fecha_ingreso": "2025-05-20",
        "fecha_salida": "2025-08-25",
    },
    {
        "nombre": "TORRES PATIÑO HEIVER CAMILO",
        "documento": "71386987",
        "cargo": "SUPERVISOR_SST",
        "area": "Construcción",
        "salario_base": 2500000.0,
        "fecha_ingreso": "2025-05-29",
        "fecha_salida": "2025-06-06",
    },
    {
        "nombre": "PASTRANA PAUL ANTONIO",
        "documento": "1007578294",
        "cargo": "OFICIAL_2",
        "area": "Construcción",
        "salario_base": 2000000.0,
        "fecha_ingreso": "2025-05-27",
        "fecha_salida": "2025-08-02",
    },
    {
        "nombre": "PALMERA CANTILLO WELLFREY MANUEL",
        "documento": "1003198934",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-05-27",
        "fecha_salida": "2025-08-04",
    },
    {
        "nombre": "RANGEL MORENO HENRY GIOVANNY",
        "documento": "88225871",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-05-27",
        "fecha_salida": "2025-11-10",
    },
    {
        "nombre": "MENA GOMEZ ADRIAN DANILO",
        "documento": "1003248967",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-05-26",
        "fecha_salida": "2025-12-19",
    },
    {
        "nombre": "ASCANIO SARABIA EDINSON FERNEL",
        "documento": "1003088908",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-05-27",
        "fecha_salida": "2025-07-26",
    },
    {
        "nombre": "GUIO CASTAÑO JHON JAIRO",
        "documento": "1111198528",
        "cargo": "CONDUCTOR",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-06-03",
        "fecha_salida": "2025-12-09",
    },
    {
        "nombre": "VARON LONDOÑO RIGOBERTO",
        "documento": "14325039",
        "cargo": "CONDUCTOR",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-05-30",
        "fecha_salida": "2025-11-07",
    },
    {
        "nombre": "PEREZ VANEGAS ROBERTO CARLOS",
        "documento": "77188843",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-05-26",
        "fecha_salida": "2025-11-10",
    },
    {
        "nombre": "GUTIERREZ BOLAÑOS JOSE CARLOS",
        "documento": "1007712252",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-05-26",
        "fecha_salida": "2025-08-30",
    },
    {
        "nombre": "ABAD GOMEZ ISAAC DAVID",
        "documento": "1066722258",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-06-03",
        "fecha_salida": "2025-12-02",
    },
    {
        "nombre": "PATERNINA CASARRUBIA MIGUEL ANGEL",
        "documento": "1192761906",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-05-27",
        "fecha_salida": "2025-12-01",
    },
    {
        "nombre": "GUERRA HERRERA DANIEL",
        "documento": "1003397341",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-05-27",
        "fecha_salida": "2025-07-24",
    },
    {
        "nombre": "GUTIERREZ MARTINEZ JOSE LUIS",
        "documento": "1096215153",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-06-03",
        "fecha_salida": "2025-06-17",
    },
    {
        "nombre": "CHAVERRA GONZALEZ JHON JAIR",
        "documento": "1102349190",
        "cargo": "ENCARGADO_CUADRILLA",
        "area": "Construcción",
        "salario_base": 2900000.0,
        "fecha_ingreso": "2025-06-12",
        "fecha_salida": "2025-06-27",
    },
    {
        "nombre": "SALAZAR GUERRERO JOSE CARLOS",
        "documento": "1007247166",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-06-14",
        "fecha_salida": "2025-09-30",
    },
    {
        "nombre": "SUAREZ OROZCO MIGUEL ANTONIO",
        "documento": "1048600236",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-05-27",
        "fecha_salida": "2025-07-11",
    },
    {
        "nombre": "MORENO CHAVARRIA EFRAIN",
        "documento": "1002084388",
        "cargo": "AUXILIAR_SERVICIOS",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-06-17",
        "fecha_salida": "2025-07-16",
    },
    {
        "nombre": "GALLEGO GALLEGO FABIAN ARGEMIRO",
        "documento": "1037500453",
        "cargo": "OFICIAL_2",
        "area": "Construcción",
        "salario_base": 2000000.0,
        "fecha_ingreso": "2025-07-08",
        "fecha_salida": "2026-01-28",
    },
    {
        "nombre": "IJAJI LOPEZ CRISTIAN ALBEIRO",
        "documento": "1084220964",
        "cargo": "ENCARGADO_OBRA",
        "area": "Construcción",
        "salario_base": 2900000.0,
        "fecha_ingreso": "2025-07-22",
        "fecha_salida": "2025-10-30",
    },
    {
        "nombre": "ALVARES VELASCO BENJAMIN",
        "documento": "1061787446",
        "cargo": "ARQUEOLOGO",
        "area": "Construcción",
        "salario_base": 3000000.0,
        "fecha_ingreso": "2025-08-11",
        "fecha_salida": "2025-10-12",
    },
    {
        "nombre": "CARRILLO BLANCO LUIS ALBERTO",
        "documento": "1003246285",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-08-07",
        "fecha_salida": "2025-12-04",
    },
    {
        "nombre": "QUIROGA CHAVES CAMILO ORLANDO",
        "documento": "80845662",
        "cargo": "ARQUEOLOGO",
        "area": "Construcción",
        "salario_base": 4000000.0,
        "fecha_ingreso": "2025-08-13",
        "fecha_salida": "2025-10-19",
    },
    {
        "nombre": "SAMBONI MUÑOZ IVONNE VALENTINA",
        "documento": "1061818338",
        "cargo": "ARQUEOLOGO",
        "area": "Construcción",
        "salario_base": 3000000.0,
        "fecha_ingreso": "2025-08-14",
        "fecha_salida": "2025-10-31",
    },
    {
        "nombre": "MUÑOZ ISAZA NATALIA",
        "documento": "1054995177",
        "cargo": "ARQUEOLOGO",
        "area": "Construcción",
        "salario_base": 3000000.0,
        "fecha_ingreso": "2025-08-23",
        "fecha_salida": "2025-10-26",
    },
    {
        "nombre": "DE LA CRUZ CAMACHO RAFAEL DAVID",
        "documento": "1083459834",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1423500.0,
        "fecha_ingreso": "2025-09-19",
        "fecha_salida": "2025-12-02",
    },
    {
        "nombre": "JIMENEZ CASTAÑO JOHN HAUAR",
        "documento": "71183911",
        "cargo": "TOPOGRAFO",
        "area": "Construcción",
        "salario_base": 3000000.0,
        "fecha_ingreso": "2025-09-25",
        "fecha_salida": "2025-10-23",
    },
    {
        "nombre": "AMU BANGUERA MARCOS",
        "documento": "76339938",
        "cargo": "TOPOGRAFO",
        "area": "Construcción",
        "salario_base": 4000000.0,
        "fecha_ingreso": "2025-10-02",
        "fecha_salida": "2025-10-27",
    },
    {
        "nombre": "HERNANDEZ CUADRADO HIBERT CORNELIO",
        "documento": "15048697",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1300000.0,
        "fecha_ingreso": "2024-11-25",
        "fecha_salida": None,
    },
    {
        "nombre": "ORREGO MARÍN YONI ALEXANDER",
        "documento": "1000638462",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 1300000.0,
        "fecha_ingreso": "2024-11-25",
        "fecha_salida": None,
    },
    {
        "nombre": "ESPINOSA ALVEIRO ENRIQUE",
        "documento": "98674197",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 0,
        "fecha_ingreso": "2025-02-03",
        "fecha_salida": None,
    },
    {
        "nombre": "SOLANO GOMEZ AURELIO JOSE",
        "documento": "98618151",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 0,
        "fecha_ingreso": "2025-02-03",
        "fecha_salida": None,
    },
    {
        "nombre": "AGUDELO GARCIA HORACIO ANTONIO",
        "documento": "98659306",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 0,
        "fecha_ingreso": "2025-02-03",
        "fecha_salida": None,
    },
    {
        "nombre": "AMAGUAÑA CONDE JUAN PABLO",
        "documento": "98326937",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 0,
        "fecha_ingreso": "2025-02-03",
        "fecha_salida": None,
    },
    {
        "nombre": "MUÑOZ DIAZ GUSTAVO ELIAS",
        "documento": "14271580",
        "cargo": "AYUDANTE",
        "area": "Construcción",
        "salario_base": 0,
        "fecha_ingreso": "2025-03-20",
        "fecha_salida": "2025-03-31",
    },
    {
        "nombre": "MORENO MORALES YEISON",
        "documento": "1111199483",
        "cargo": "AYUDANTE",
        "area": "Construcción",
        "salario_base": 0,
        "fecha_ingreso": "2025-03-21",
        "fecha_salida": "2025-03-28",
    },
    {
        "nombre": "SEPULVEDA GOMEZ YOVAN JAVIER",
        "documento": "88213762",
        "cargo": "LINIERO_I",
        "area": "Construcción",
        "salario_base": 0,
        "fecha_ingreso": "2025-04-22",
        "fecha_salida": "2025-04-30",
    },
    {
        "nombre": "HERRERA ENRIQUE CARLOS ANDRES",
        "documento": "1002314870",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 0,
        "fecha_ingreso": "2025-04-22",
        "fecha_salida": "2025-05-19",
    },
    {
        "nombre": "BOLAÑOS RODRIGUEZ LUZ ENEIDA",
        "documento": "1104127157",
        "cargo": "SUPERVISOR_SST",
        "area": "Construcción",
        "salario_base": 0,
        "fecha_ingreso": "2025-04-30",
        "fecha_salida": "2025-05-15",
    },
    {
        "nombre": "BARBOSA BARBOSA KEVIN FABIAN",
        "documento": "1064840578",
        "cargo": "LINIERO_II",
        "area": "Construcción",
        "salario_base": 0,
        "fecha_ingreso": "2025-05-12",
        "fecha_salida": "2025-06-01",
    },
    {
        "nombre": "RUIZ COSSIO OMAR ALEJANDRO",
        "documento": "1039686973",
        "cargo": "LINIERO_I",
        "area": "Construcción",
        "salario_base": 0,
        "fecha_ingreso": "2025-05-19",
        "fecha_salida": "2025-05-30",
    },
    {
        "nombre": "SOLARTE LOAIZA ERWIN JULIAN",
        "documento": "1084221728",
        "cargo": "LINIERO_I",
        "area": "Construcción",
        "salario_base": 0,
        "fecha_ingreso": "2025-07-03",
        "fecha_salida": "2025-07-03",
    },
    {
        "nombre": "BALDOVINO CARBONERO VICTOR ALFONSO",
        "documento": "92278033",
        "cargo": "OFICIAL_3",
        "area": "Construcción",
        "salario_base": 0,
        "fecha_ingreso": "2025-07-04",
        "fecha_salida": "2025-07-04",
    },
    {
        "nombre": "ARIAS RODRIGUEZ DUVAN ALEXIS",
        "documento": "1090497603",
        "cargo": "LINIERO_I",
        "area": "Construcción",
        "salario_base": 0,
        "fecha_ingreso": "2025-07-01",
        "fecha_salida": "2025-07-01",
    },
    {
        "nombre": "ZAMBRANO JURADO BERNER",
        "documento": "1084227801",
        "cargo": "LINIERO_I",
        "area": "Construcción",
        "salario_base": 0,
        "fecha_ingreso": "2025-09-10",
        "fecha_salida": "2025-09-10",
    },
]


def reemplazar_catalogo(apps, schema_editor):
    PersonalCuadrilla = apps.get_model("cuadrillas", "PersonalCuadrilla")
    PersonalCuadrilla.objects.all().delete()
    nuevos = [
        PersonalCuadrilla(
            nombre=fila["nombre"],
            documento=fila["documento"],
            rol_cuadrilla_id=fila["cargo"],
            area=fila["area"],
            salario_base=fila["salario_base"],
            fecha_ingreso=fila["fecha_ingreso"],
            fecha_salida=fila["fecha_salida"],
            activo=fila["fecha_salida"] is None,
            celular="",
        )
        for fila in COLABORADORES
    ]
    PersonalCuadrilla.objects.bulk_create(nuevos)


def restaurar_no_reversible(apps, schema_editor):
    raise RuntimeError(
        "Migración de datos no reversible (issue #237): el catálogo previo "
        "(484 filas legacy, con datos cruzados/corruptos) fue reemplazado a "
        "propósito y no se conserva su estado exacto en la migración. "
        "Restaurar desde el backup: SPRINTS/RUN_2026-09-07_0213/backups/"
        "personal_cuadrilla_backup_2026-09-07_pre_reload.sql"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("cuadrillas", "0030_bloque_actividad"),
    ]

    operations = [
        migrations.RunPython(reemplazar_catalogo, restaurar_no_reversible),
    ]
