# Generated by Django 6.0.7 on 2026-09-08 17:49

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0032_normaliza_area_choice_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduccionDiaria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha', models.DateField(verbose_name='Fecha de producción')),
                ('calidad_trabajo', models.CharField(choices=[('BUENA', 'Buena'), ('NORMAL', 'Normal'), ('MALA', 'Mala')], default='NORMAL', max_length=10, verbose_name='Calidad del trabajo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('programacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producciones_diarias', to='cuadrillas.programacionsemanalcuadrilla', verbose_name='Programación semanal')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producciones_diarias_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Producción diaria',
                'verbose_name_plural': 'Producciones diarias',
                'db_table': 'produccion_diaria',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NovedadProduccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('tipo', models.CharField(choices=[('LLUVIA', 'Lluvia'), ('ACCIDENTE_LESION', 'Accidente/Lesión'), ('CAMBIO_ORDEN', 'Cambio orden'), ('MATERIAL_FALTANTE', 'Material faltante'), ('HERRAMIENTA_DANADA', 'Herramienta dañada'), ('OTRO', 'Otro')], max_length=25, verbose_name='Tipo de novedad')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('foto', models.FileField(blank=True, upload_to='produccion_diaria/', verbose_name='Foto')),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='cuadrillas.producciondiaria', verbose_name='Producción diaria')),
            ],
            options={
                'verbose_name': 'Novedad de producción',
                'verbose_name_plural': 'Novedades de producción',
                'db_table': 'novedad_produccion',
            },
        ),
        migrations.CreateModel(
            name='MaterialProduccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Material')),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Cantidad')),
                ('costo_unitario_estimado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Costo unitario estimado')),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='cuadrillas.producciondiaria', verbose_name='Producción diaria')),
            ],
            options={
                'verbose_name': 'Material de producción',
                'verbose_name_plural': 'Materiales de producción',
                'db_table': 'material_produccion',
            },
        ),
        migrations.CreateModel(
            name='AlertaProduccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('desviacion_pct', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Desviación (%)')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('notificada_en', models.DateTimeField(blank=True, null=True, verbose_name='Notificada en')),
                ('produccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alerta_desviacion', to='cuadrillas.producciondiaria', verbose_name='Producción diaria')),
            ],
            options={
                'verbose_name': 'Alerta de producción',
                'verbose_name_plural': 'Alertas de producción',
                'db_table': 'alertas_produccion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActividadProduccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Actividad')),
                ('avance_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Avance (%)')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='cuadrillas.producciondiaria', verbose_name='Producción diaria')),
            ],
            options={
                'verbose_name': 'Actividad de producción',
                'verbose_name_plural': 'Actividades de producción',
                'db_table': 'actividad_produccion',
            },
        ),
        migrations.CreateModel(
            name='RegistroPersonalProduccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Horas trabajadas')),
                ('motivo_ausencia', models.CharField(blank=True, choices=[('NO_INFORMO', 'No informó'), ('ENFERMEDAD', 'Enfermedad'), ('PERMISO', 'Permiso'), ('CAMBIO_ORDEN', 'Cambio de orden'), ('OTRO', 'Otro')], max_length=20, verbose_name='Motivo de ausencia')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_produccion_diaria', to='cuadrillas.personalcuadrilla', verbose_name='Personal')),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_personal', to='cuadrillas.producciondiaria', verbose_name='Producción diaria')),
            ],
            options={
                'verbose_name': 'Registro de personal en producción',
                'verbose_name_plural': 'Registros de personal en producción',
                'db_table': 'registro_personal_produccion',
            },
        ),
        migrations.AddIndex(
            model_name='producciondiaria',
            index=models.Index(fields=['fecha'], name='produccion__fecha_54945a_idx'),
        ),
        migrations.AddConstraint(
            model_name='producciondiaria',
            constraint=models.UniqueConstraint(fields=('programacion', 'fecha'), name='produccion_diaria_programacion_fecha_unica'),
        ),
        migrations.AddConstraint(
            model_name='registropersonalproduccion',
            constraint=models.UniqueConstraint(fields=('produccion', 'personal'), name='registro_personal_produccion_unico'),
        ),
    ]
