# Generated by Django 6.0.7 on 2026-09-15 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0033_produccion_diaria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producciondiaria',
            name='importada_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Importada desde asistencia'),
        ),
        migrations.AddField(
            model_name='producciondiaria',
            name='ultima_edicion_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última edición'),
        ),
        migrations.AddField(
            model_name='producciondiaria',
            name='ultima_edicion_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producciones_diarias_editadas', to=settings.AUTH_USER_MODEL, verbose_name='Última edición por'),
        ),
        migrations.AddField(
            model_name='registropersonalproduccion',
            name='asistencia_origen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registro_produccion_diaria', to='cuadrillas.asistencia', verbose_name='Asistencia de origen'),
        ),
    ]
