# Generated by Django 6.0.7 on 2026-09-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0034_asistencia_origen_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacionsemanalcuadrilla',
            name='horas_planeadas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Horas de trabajo planeadas para la semana', max_digits=8, null=True, verbose_name='Horas planeadas'),
        ),
    ]
