# Generated by Django 6.0.7 on 2026-09-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0052_psc_presupuesto_snapshots'),
        ('cuadrillas', '0035_horas_planeadas_programacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacionsemanalcuadrilla',
            name='torres',
            field=models.ManyToManyField(blank=True, help_text='Torres reales del proyecto incluidas en esta programación (selección informativa/trazabilidad; no reemplaza "Torres programadas", que sigue siendo el conteo manual editable).', related_name='programaciones_cuadrilla', to='construccion.torreconstruccion', verbose_name='Torres'),
        ),
    ]
