# Generated by Django 6.0.7 on 2026-09-22 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0036_programacion_torres_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejecucionsemanalcuadrilla',
            name='vehiculo',
            field=models.ForeignKey(blank=True, help_text='Vehículo asignado a la ejecución de esta semana (editable/reasignable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejecuciones_semanales_cuadrilla', to='cuadrillas.vehiculo', verbose_name='Vehículo asignado'),
        ),
    ]
