# Generated by Django 6.0.7 on 2026-09-22 20:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0037_ejecucion_vehiculo_270'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjecucionSemanalPersonal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('costo_dia', models.DecimalField(decimal_places=2, default=0, help_text='Costo diario de esta persona para la semana ejecutada (snapshot editable, tomado del cargo al agregar).', max_digits=12, verbose_name='Costo por día')),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_asignado', to='cuadrillas.ejecucionsemanalcuadrilla', verbose_name='Ejecución')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones_semanales_personal', to='cuadrillas.personalcuadrilla', verbose_name='Personal')),
            ],
            options={
                'verbose_name': 'Personal de Ejecución Semanal',
                'verbose_name_plural': 'Personal de Ejecución Semanal',
                'db_table': 'ejecucion_semanal_personal',
                'ordering': ['personal__nombre'],
                'unique_together': {('ejecucion', 'personal')},
            },
        ),
    ]
