# Generated by Django 6.0.7 on 2026-09-22 21:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0038_ejecucion_personal_270'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaEjecucionSemanal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha', models.DateField(help_text='Día (dentro de la semana ISO de la programación) al que corresponde este registro.', verbose_name='Fecha')),
                ('tipo_novedad', models.CharField(choices=[('PRESENTE', 'Presente'), ('VACACIONES', 'Vacaciones'), ('INCAPACIDAD', 'Incapacidad'), ('PERMISO', 'Permiso'), ('AUSENTE', 'Ausente'), ('LICENCIA', 'Licencia'), ('CAPACITACION', 'Capacitación'), ('COMPENSATORIO', 'Compensatorio'), ('DESCANSO', 'Descanso'), ('DIA_GANADO', 'Día ganado'), ('FESTIVO', 'Festivo')], default='PRESENTE', help_text='Reusa el vocabulario de novedades de Asistencia (PRESENTE/VACACIONES/INCAPACIDAD/PERMISO/...).', max_length=20, verbose_name='Tipo de novedad')),
                ('horas_trabajadas', models.DecimalField(decimal_places=1, default=0, help_text='Horas trabajadas ese día. Se fuerza a 0 cuando tipo_novedad != PRESENTE (ver docstring de la clase).', max_digits=4, verbose_name='Horas trabajadas')),
                ('horas_extra', models.DecimalField(decimal_places=1, default=0, help_text='Horas extra del día (puede existir sin horas_trabajadas, ver docstring de la clase).', max_digits=4, verbose_name='Horas extra')),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='cuadrillas.ejecucionsemanalcuadrilla', verbose_name='Ejecución')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_ejecucion_semanal', to='cuadrillas.personalcuadrilla', verbose_name='Personal')),
            ],
            options={
                'verbose_name': 'Asistencia de Ejecución Semanal',
                'verbose_name_plural': 'Asistencias de Ejecución Semanal',
                'db_table': 'asistencia_ejecucion_semanal',
                'ordering': ['fecha', 'personal__nombre'],
                'indexes': [models.Index(fields=['ejecucion', 'fecha'], name='asistencia__ejecuci_6988a4_idx')],
                'unique_together': {('ejecucion', 'personal', 'fecha')},
            },
        ),
    ]
