# Generated by Django 6.0.7 on 2026-09-22 22:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0052_psc_presupuesto_snapshots'),
        ('cuadrillas', '0039_asistencia_ejecucion_semanal_270'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjecucionSemanalTorre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('ejecutada', models.BooleanField(default=True, help_text='False = estaba programada pero NO se ejecutó esta semana (requiere motivo_cambio).', verbose_name='Ejecutada')),
                ('motivo_cambio', models.TextField(blank=True, help_text='Obligatorio cuando ejecutada=False (torre programada que no se ejecutó). Opcional/informativo si es una torre ejecutada que no estaba programada (sobre-ejecución).', verbose_name='Motivo del cambio')),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torres_detalle', to='cuadrillas.ejecucionsemanalcuadrilla', verbose_name='Ejecución')),
                ('torre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones_semanales_cuadrilla', to='construccion.torreconstruccion', verbose_name='Torre')),
            ],
            options={
                'verbose_name': 'Torre de Ejecución Semanal',
                'verbose_name_plural': 'Torres de Ejecución Semanal',
                'db_table': 'ejecucion_semanal_torre',
                'ordering': ['torre__numero'],
                'unique_together': {('ejecucion', 'torre')},
            },
        ),
    ]
