# Generated by Django 5.1.15 on 2026-07-19 01:50
#
# Issue #186 (A1): primera migración real de apps.core (antes solo tenía
# BaseModel abstracto). Esquema ADITIVO puro — no toca Usuario.rol ni
# ninguna tabla existente. Ver apps/core/models_roles.py.

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('nivel', models.CharField(choices=[('admin', 'Administrador'), ('operario', 'Operario')], max_length=10, verbose_name='Nivel')),
                ('legacy', models.BooleanField(default=False, verbose_name='Legacy')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RoleModuloPermiso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('modulo', models.CharField(choices=[('MANTENIMIENTO', 'Mantenimiento'), ('CONSTRUCCION', 'Construcción'), ('CONFIG', 'Configuración')], max_length=20, verbose_name='Módulo')),
                ('submodulo', models.CharField(blank=True, max_length=40, null=True, verbose_name='Sub-módulo')),
                ('nivel_acceso', models.CharField(choices=[('sin_acceso', 'Sin acceso'), ('ver', 'Ver'), ('ver_editar', 'Ver y editar')], default='sin_acceso', max_length=12, verbose_name='Nivel de acceso')),
                ('role', models.ForeignKey(db_column='role_codigo', on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='core.role', to_field='codigo')),
            ],
            options={
                'verbose_name': 'Permiso de Rol',
                'verbose_name_plural': 'Permisos de Rol',
                'db_table': 'role_modulo_permisos',
                'ordering': ['role__nombre', 'modulo', 'submodulo'],
                'unique_together': {('role', 'modulo', 'submodulo')},
            },
        ),
    ]
