import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rbac_roles'),
        ('construccion', '0009_snapshot_avance'),
    ]

    operations = [
        # === Sub-detalles de Obra Civil (#53 iter 2) ===
        migrations.CreateModel(
            name='CerramientoDetalle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_madera', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad de madera (unidades)')),
                ('metros_lona_pua', models.FloatField(blank=True, null=True, verbose_name='Metros lona/alambre de púa')),
                ('senalizacion_ok', models.BooleanField(default=False, verbose_name='Señalización instalada')),
                ('punto_ecologico_ok', models.BooleanField(default=False, verbose_name='Punto ecológico instalado')),
                ('bano_ok', models.BooleanField(default=False, verbose_name='Baño instalado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('pata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cerramiento_detalle', to='construccion.pataobra')),
            ],
            options={'db_table': 'construccion_cerramiento_detalle', 'verbose_name': 'Detalle Cerramiento'},
        ),
        migrations.CreateModel(
            name='ExcavacionDetalle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('procedimiento_ft022_ok', models.BooleanField(default=False, verbose_name='FT-022 Procedimiento aprobado')),
                ('sst_ft023_ok', models.BooleanField(default=False, verbose_name='FT-023 Doc SST excavaciones')),
                ('prueba_penetrometro_ok', models.BooleanField(default=False, verbose_name='Prueba de penetrómetro')),
                ('entivado_ft058_ok', models.BooleanField(default=False, verbose_name='FT-058 Concepto entibado')),
                ('monitoreo_arqueologico_ok', models.BooleanField(default=False, verbose_name='Monitoreo arqueológico')),
                ('subcontratistas', models.CharField(blank=True, max_length=300, verbose_name='Subcontratistas involucrados')),
                ('ft925_carga_ok', models.BooleanField(default=False, verbose_name='FT-925 Carga pilotes')),
                ('ft926_marcacion_ok', models.BooleanField(default=False, verbose_name='FT-926 Marcación')),
                ('ft927_cantidades_ok', models.BooleanField(default=False, verbose_name='FT-927 Cantidades')),
                ('ft928_torques_ok', models.BooleanField(default=False, verbose_name='FT-928 Torques')),
                ('ft929_localizacion_ok', models.BooleanField(default=False, verbose_name='FT-929 Localización final')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('pata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='excavacion_detalle', to='construccion.pataobra')),
            ],
            options={'db_table': 'construccion_excavacion_detalle', 'verbose_name': 'Detalle Excavación'},
        ),
        migrations.CreateModel(
            name='SoladoDetalle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ingreso_materiales', models.CharField(blank=True, choices=[('VEHICULAR', 'Vehicular'), ('MANUAL', 'Manual'), ('MULAR', 'Mular'), ('TELEFERICO', 'Teleférico')], max_length=15, verbose_name='Ingreso de materiales')),
                ('agua_calc_m3', models.FloatField(blank=True, null=True, verbose_name='Agua calculada (m³)')),
                ('agua_util_m3', models.FloatField(blank=True, null=True, verbose_name='Agua utilizada (m³)')),
                ('arena_calc_m3', models.FloatField(blank=True, null=True, verbose_name='Arena calculada (m³)')),
                ('arena_util_m3', models.FloatField(blank=True, null=True, verbose_name='Arena utilizada (m³)')),
                ('grava_calc_m3', models.FloatField(blank=True, null=True, verbose_name='Grava calculada (m³)')),
                ('grava_util_m3', models.FloatField(blank=True, null=True, verbose_name='Grava utilizada (m³)')),
                ('cemento_calc_bultos', models.FloatField(blank=True, null=True, verbose_name='Cemento calculado (bultos)')),
                ('cemento_util_bultos', models.FloatField(blank=True, null=True, verbose_name='Cemento utilizado (bultos)')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('pata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solado_detalle', to='construccion.pataobra')),
            ],
            options={'db_table': 'construccion_solado_detalle', 'verbose_name': 'Detalle Solado'},
        ),
        migrations.CreateModel(
            name='AceroDetalle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('soldadura_prolongas_ok', models.BooleanField(default=False, verbose_name='Soldadura prolongas a stub')),
                ('ingreso_acero', models.CharField(blank=True, choices=[('VEHICULAR', 'Vehicular'), ('MULAR', 'Mular'), ('TELEFERICO', 'Teleférico')], max_length=15, verbose_name='Ingreso de acero')),
                ('it028_ok', models.BooleanField(default=False, verbose_name='IT-028 Instructivo instalación acero')),
                ('ft930_ok', models.BooleanField(default=False, verbose_name='FT-930 Revisión acero/formaleta/SPT')),
                ('corte_flejado_ok', models.BooleanField(default=False, verbose_name='Corte y flejado')),
                ('acero_armado_ok', models.BooleanField(default=False, verbose_name='Acero armado en sitio')),
                ('spt_base_completo_ok', models.BooleanField(default=False, verbose_name='SPT base: varilla+cable+conectores')),
                ('nivelacion_stub_ft916_ok', models.BooleanField(default=False, verbose_name='FT-916 Nivelación stub')),
                ('encofrado_ok', models.BooleanField(default=False, verbose_name='Encofrado / formaleteado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('pata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acero_detalle', to='construccion.pataobra')),
            ],
            options={'db_table': 'construccion_acero_detalle', 'verbose_name': 'Detalle Acero'},
        ),
        migrations.CreateModel(
            name='VaciadoDetalle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('it380_ok', models.BooleanField(default=False, verbose_name='IT-380 Instructivo cimentación')),
                ('ft056_ok', models.BooleanField(default=False, verbose_name='FT-056 Control fundaciones')),
                ('tipo_concreto', models.CharField(blank=True, choices=[('PREMEZCLADO', 'Premezclado'), ('OBRA', 'Hecho en obra')], max_length=15, verbose_name='Tipo de concreto')),
                ('agua_calc_m3', models.FloatField(blank=True, null=True, verbose_name='Agua calc (m³)')),
                ('agua_util_m3', models.FloatField(blank=True, null=True, verbose_name='Agua util (m³)')),
                ('arena_calc_m3', models.FloatField(blank=True, null=True, verbose_name='Arena calc (m³)')),
                ('arena_util_m3', models.FloatField(blank=True, null=True, verbose_name='Arena util (m³)')),
                ('grava_calc_m3', models.FloatField(blank=True, null=True, verbose_name='Grava calc (m³)')),
                ('grava_util_m3', models.FloatField(blank=True, null=True, verbose_name='Grava util (m³)')),
                ('cemento_calc_bultos', models.FloatField(blank=True, null=True, verbose_name='Cemento calc (bultos)')),
                ('cemento_util_bultos', models.FloatField(blank=True, null=True, verbose_name='Cemento util (bultos)')),
                ('prueba_slump_ok', models.BooleanField(default=False, verbose_name='Prueba de slump')),
                ('fecha_fabricacion_cilindros', models.DateField(blank=True, null=True, verbose_name='Fecha fabricación cilindros')),
                ('inspeccion_nivelacion_stub_post_ok', models.BooleanField(default=False, verbose_name='Inspección nivelación stub post-vaciado')),
                ('encargado_puntas_diamante', models.CharField(blank=True, max_length=200, verbose_name='Encargado puntas de diamante')),
                ('fecha_desencofrado', models.DateField(blank=True, null=True, verbose_name='Fecha desencofrado')),
                ('hidratacion_pedestales_ok', models.BooleanField(default=False, verbose_name='Hidratación de pedestales')),
                ('resane_pedestales_ok', models.BooleanField(default=False, verbose_name='Resane de pedestales')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('pata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vaciado_detalle', to='construccion.pataobra')),
            ],
            options={'db_table': 'construccion_vaciado_detalle', 'verbose_name': 'Detalle Vaciado'},
        ),
        migrations.CreateModel(
            name='CompactacionDetalle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ft914_ok', models.BooleanField(default=False, verbose_name='FT-914 Control compactación')),
                ('tipo_compactacion', models.CharField(blank=True, choices=[('NATURAL', 'Suelo natural'), ('CEMENTO', 'Suelo + cemento'), ('PRESTAMO', 'Suelo de préstamo')], max_length=15, verbose_name='Tipo de compactación')),
                ('volumen_m3', models.FloatField(blank=True, null=True, verbose_name='Volumen compactación (m³)')),
                ('proctor_ok', models.BooleanField(default=False, verbose_name='Prueba Proctor')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('pata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compactacion_detalle', to='construccion.pataobra')),
            ],
            options={'db_table': 'construccion_compactacion_detalle', 'verbose_name': 'Detalle Compactación'},
        ),

        # === #69 BD Contable + jerarquía ===
        migrations.AddField(
            model_name='categoriafinanciera',
            name='categoria_padre',
            field=models.ForeignKey(blank=True, help_text='Permite jerarquía: Ingresos → Operacionales, Egresos → CIF → Materiales', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='construccion.categoriafinanciera'),
        ),
        migrations.AddField(
            model_name='categoriafinanciera',
            name='nivel',
            field=models.PositiveSmallIntegerField(default=1, help_text='1 = raíz, 2 = sub-categoría, 3 = detalle', verbose_name='Nivel jerárquico'),
        ),
        migrations.CreateModel(
            name='TransaccionContable',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha de la transacción')),
                ('descripcion', models.CharField(max_length=400, verbose_name='Descripción')),
                ('nit_proveedor', models.CharField(blank=True, max_length=30, verbose_name='NIT proveedor')),
                ('nombre_proveedor', models.CharField(blank=True, max_length=200, verbose_name='Nombre proveedor')),
                ('numero_factura', models.CharField(blank=True, max_length=50, verbose_name='Número de factura')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Valor (COP)')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='IVA (COP)')),
                ('centro_costo', models.CharField(blank=True, max_length=50, verbose_name='Centro de costo')),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='construccion/transacciones/', verbose_name='Soporte (factura/comprobante)')),
                ('siigo_id', models.CharField(blank=True, help_text='Para evitar duplicados al sincronizar', max_length=50, verbose_name='ID externo SIIGO/Alegra')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('movimiento', models.ForeignKey(help_text='Movimiento mensual al que pertenece (real o presupuesto)', on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='construccion.movimientofinanciero')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_registradas', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'construccion_transaccion_contable',
                'verbose_name': 'Transacción Contable',
                'verbose_name_plural': 'Transacciones Contables',
                'ordering': ['-fecha', '-created_at'],
                'indexes': [
                    models.Index(fields=['fecha'], name='construccion_fecha_idx'),
                    models.Index(fields=['nit_proveedor'], name='construccion_nit_idx'),
                    models.Index(fields=['siigo_id'], name='construccion_siigo_idx'),
                ],
            },
        ),

        # === #65 MovimientoKit histórico ===
        migrations.CreateModel(
            name='MovimientoKit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accion', models.CharField(choices=[('ASIGNAR', 'Asignar a torre'), ('LIBERAR', 'Liberar de torre'), ('MOVER', 'Mover entre torres'), ('ESTADO', 'Cambio de estado')], max_length=10, verbose_name='Acción')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del movimiento')),
                ('estado_previo', models.CharField(blank=True, max_length=15, verbose_name='Estado previo')),
                ('estado_nuevo', models.CharField(blank=True, max_length=15, verbose_name='Estado nuevo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='construccion.kitcerramiento')),
                ('torre_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kits_origen', to='construccion.torreconstruccion')),
                ('torre_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kits_destino', to='construccion.torreconstruccion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_kit', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'construccion_movimiento_kit',
                'verbose_name': 'Movimiento de Kit',
                'verbose_name_plural': 'Movimientos de Kits',
                'ordering': ['-fecha'],
            },
        ),
    ]
