# Generated by Django 5.1.15 on 2026-05-24 16:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0010_deuda_tecnica'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraCivilTorre',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avance_cerramiento', models.DecimalField(decimal_places=4, default=0, help_text='0 a 1 (1 = 100% completado)', max_digits=5, verbose_name='Avance Cerramiento')),
                ('avance_excavacion', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='Avance Excavación')),
                ('avance_solado', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='Avance Solado')),
                ('avance_acero', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='Avance Acero')),
                ('avance_vaciado', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='Avance Vaciado')),
                ('avance_compactacion', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='Avance Compactación')),
                ('cuadrilla', models.CharField(blank=True, max_length=100, verbose_name='Cuadrilla / Encargado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Obra Civil — Torre',
                'verbose_name_plural': 'Obra Civil — Torres',
                'db_table': 'construccion_obra_civil_torre',
                'ordering': ['torre__numero'],
            },
        ),
        migrations.RenameIndex(
            model_name='transaccioncontable',
            new_name='construccio_fecha_d8e290_idx',
            old_name='construccion_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='transaccioncontable',
            new_name='construccio_nit_pro_3ed551_idx',
            old_name='construccion_nit_idx',
        ),
        migrations.RenameIndex(
            model_name='transaccioncontable',
            new_name='construccio_siigo_i_b1097b_idx',
            old_name='construccion_siigo_idx',
        ),
        migrations.AlterField(
            model_name='acerodetalle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='acerodetalle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='categoriafinanciera',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='categoriafinanciera',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='cerramientodetalle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='cerramientodetalle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='compactaciondetalle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='compactaciondetalle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='excavaciondetalle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='excavaciondetalle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='kitcerramiento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='kitcerramiento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='movimientokit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='movimientokit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='obraproteccion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='obraproteccion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='periodofinanciero',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='periodofinanciero',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='programacionfase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='programacionfase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='pruebatecnica',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='pruebatecnica',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='snapshotavance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='snapshotavance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='soladodetalle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='soladodetalle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='transaccioncontable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='transaccioncontable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='vaciadodetalle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='vaciadodetalle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='obraciviltorre',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obra_civil_torres', to='construccion.proyectoconstruccion'),
        ),
        migrations.AddField(
            model_name='obraciviltorre',
            name='torre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='obra_civil', to='construccion.torreconstruccion'),
        ),
    ]
