# Generated by Django 5.1.15 on 2026-05-24 16:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0011_obra_civil_torre'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectoconstruccion',
            name='peso_mont_estructura_sitio_pct',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Peso Estructura en sitio %'),
        ),
        migrations.AddField(
            model_name='proyectoconstruccion',
            name='peso_mont_prearamada_pct',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='Peso Prearmada %'),
        ),
        migrations.AddField(
            model_name='proyectoconstruccion',
            name='peso_mont_revisada_pct',
            field=models.PositiveSmallIntegerField(default=25, verbose_name='Peso Revisada %'),
        ),
        migrations.AddField(
            model_name='proyectoconstruccion',
            name='peso_mont_torre_montada_pct',
            field=models.PositiveSmallIntegerField(default=45, verbose_name='Peso Torre montada %'),
        ),
        migrations.CreateModel(
            name='MontajeEstructuraTorre',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avance_estructura_sitio', models.DecimalField(decimal_places=4, default=0, help_text='0 a 1 (1 = recibida en sitio)', max_digits=5, verbose_name='Estructura en sitio')),
                ('avance_prearamada', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='Prearmada')),
                ('avance_torre_montada', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='Torre Montada')),
                ('avance_revisada', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='Revisada (post-inspección)')),
                ('encargado_prearmado', models.CharField(blank=True, max_length=100, verbose_name='Cuadrilla prearmado')),
                ('encargado_montaje', models.CharField(blank=True, max_length=100, verbose_name='Cuadrilla montaje')),
                ('entregada_para_carga', models.BooleanField(default=False, verbose_name='Entregada para carga (habilita Tendido)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='montaje_torres', to='construccion.proyectoconstruccion')),
                ('torre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='montaje_estructura', to='construccion.torreconstruccion')),
            ],
            options={
                'verbose_name': 'Montaje — Estructura Torre',
                'verbose_name_plural': 'Montaje — Estructuras Torre',
                'db_table': 'construccion_montaje_estructura_torre',
                'ordering': ['torre__numero'],
            },
        ),
    ]
