# Generated by Django 5.1.15 on 2026-05-24 16:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0012_montaje_estructura_torre'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinturaAeronauticaTorre',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_espesor_micras', models.BooleanField(default=False, verbose_name='Revisión espesor en micras')),
                ('entrega_pintura', models.BooleanField(default=False, verbose_name='Entrega de pintura')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pintura_aero_torres', to='construccion.proyectoconstruccion')),
                ('torre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pintura_aeronautica', to='construccion.torreconstruccion')),
            ],
            options={
                'verbose_name': 'Pintura Aeronáutica — Torre',
                'verbose_name_plural': 'Pintura Aeronáutica — Torres',
                'db_table': 'construccion_pintura_aero_torre',
                'ordering': ['torre__numero'],
            },
        ),
        migrations.CreateModel(
            name='PinturaPatasTorre',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('control_espesor', models.BooleanField(default=False, verbose_name='FT-912 Control espesor')),
                ('torres_pintadas', models.BooleanField(default=False, verbose_name='Torres pintadas')),
                ('medicion_espesor', models.BooleanField(default=False, verbose_name='Medición de espesor')),
                ('entrega_pintura', models.BooleanField(default=False, verbose_name='Entrega de pintura')),
                ('cuadrilla', models.CharField(blank=True, max_length=100, verbose_name='Cuadrilla')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pintura_patas_torres', to='construccion.proyectoconstruccion')),
                ('torre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pintura_patas', to='construccion.torreconstruccion')),
            ],
            options={
                'verbose_name': 'Pintura Patas — Torre',
                'verbose_name_plural': 'Pintura Patas — Torres',
                'db_table': 'construccion_pintura_patas_torre',
                'ordering': ['torre__numero'],
            },
        ),
        migrations.CreateModel(
            name='SPTTorre',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('excavacion_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Excavación (m)')),
                ('cable_planos_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cable según planos (m)')),
                ('cable_instalado_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cable instalado (m)')),
                ('cuadrilla_spt', models.CharField(blank=True, max_length=100, verbose_name='Cuadrilla SPT')),
                ('observaciones_cable', models.TextField(blank=True, verbose_name='Observaciones cable')),
                ('cantidad_tiros', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cantidad de tiros')),
                ('polvora_teorica_cajas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Pólvora teórica (cajas)')),
                ('polvora_real_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Pólvora real (kg)')),
                ('observaciones_polvora', models.TextField(blank=True, verbose_name='Observaciones pólvora')),
                ('porcentaje_avance', models.PositiveSmallIntegerField(default=0, verbose_name='Avance SPT %')),
                ('control_compensacion', models.BooleanField(default=False, verbose_name='FT-068 Control compensación')),
                ('control_medicion', models.BooleanField(default=False, verbose_name='FT-029 Lectura medición')),
                ('informe_mediciones', models.BooleanField(default=False, verbose_name='Informe de mediciones entregado')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spt_torres', to='construccion.proyectoconstruccion')),
                ('torre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spt', to='construccion.torreconstruccion')),
            ],
            options={
                'verbose_name': 'SPT — Torre',
                'verbose_name_plural': 'SPT — Torres',
                'db_table': 'construccion_spt_torre',
                'ordering': ['torre__numero'],
            },
        ),
        migrations.CreateModel(
            name='PinturaFranja',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_franja', models.PositiveSmallIntegerField(choices=[(1, 'Franja 1'), (2, 'Franja 2'), (3, 'Franja 3'), (4, 'Franja 4'), (5, 'Franja 5'), (6, 'Franja 6'), (7, 'Franja 7')], verbose_name='Número de franja')),
                ('color', models.CharField(choices=[('NARANJA', 'Naranja'), ('BLANCO', 'Blanco')], max_length=10, verbose_name='Color')),
                ('porcentaje_base', models.PositiveSmallIntegerField(default=0, verbose_name='Avance base gris (%)')),
                ('cantidad_base_proyectada', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Base proyectada (L)')),
                ('cantidad_base_consumida', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Base consumida (L)')),
                ('observaciones_base', models.TextField(blank=True, verbose_name='Observaciones base')),
                ('porcentaje_color', models.PositiveSmallIntegerField(default=0, verbose_name='Avance color (%)')),
                ('cantidad_color_proyectada', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Color proyectado (L)')),
                ('cantidad_color_consumida', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Color consumido (L)')),
                ('observaciones_color', models.TextField(blank=True, verbose_name='Observaciones color')),
                ('pintura_aeronautica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='franjas', to='construccion.pinturaaeronauticatorre')),
            ],
            options={
                'verbose_name': 'Franja de pintura',
                'verbose_name_plural': 'Franjas de pintura',
                'db_table': 'construccion_pintura_franja',
                'ordering': ['numero_franja'],
                'unique_together': {('pintura_aeronautica', 'numero_franja')},
            },
        ),
    ]
