# Generated by Django 5.1.15 on 2026-05-24 17:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0013_spt_pintura'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectoconstruccion',
            name='peso_tend_accesorios_pct',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Tend. Accesorios/puentes %'),
        ),
        migrations.AddField(
            model_name='proyectoconstruccion',
            name='peso_tend_balizas_pct',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Tend. Balizas/desviadores %'),
        ),
        migrations.AddField(
            model_name='proyectoconstruccion',
            name='peso_tend_empalmes_opgw_pct',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='OPGW Empalmes %'),
        ),
        migrations.AddField(
            model_name='proyectoconstruccion',
            name='peso_tend_grapado_fibra_pct',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='OPGW Grapado/amarre fibra %'),
        ),
        migrations.AddField(
            model_name='proyectoconstruccion',
            name='peso_tend_grapado_pct',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Tend. Grapado/amarre %'),
        ),
        migrations.AddField(
            model_name='proyectoconstruccion',
            name='peso_tend_riega_guaya_opgw_pct',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='OPGW Riega guaya %'),
        ),
        migrations.AddField(
            model_name='proyectoconstruccion',
            name='peso_tend_riega_guaya_pct',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Tend. Riega guaya conductor %'),
        ),
        migrations.AddField(
            model_name='proyectoconstruccion',
            name='peso_tend_riega_manila_fibra_pct',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='OPGW Riega manila fibra %'),
        ),
        migrations.AddField(
            model_name='proyectoconstruccion',
            name='peso_tend_riega_manila_pct',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Tend. Riega manila %'),
        ),
        migrations.AddField(
            model_name='proyectoconstruccion',
            name='peso_tend_tendido_conductor_pct',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Tend. Tendido conductor %'),
        ),
        migrations.AddField(
            model_name='proyectoconstruccion',
            name='peso_tend_tendido_opgw_pct',
            field=models.PositiveSmallIntegerField(default=40, verbose_name='OPGW Tendido %'),
        ),
        migrations.CreateModel(
            name='TendidoTorre',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vestida_conductor', models.BooleanField(default=False, verbose_name='Vestida (conductor)')),
                ('riega_manila_conductor', models.BooleanField(default=False, verbose_name='Riega de manila')),
                ('riega_guaya_conductor', models.BooleanField(default=False, verbose_name='Riega guaya conductor')),
                ('tendido_conductor', models.BooleanField(default=False, verbose_name='Tendido de conductor')),
                ('grapado_amarre_conductor', models.BooleanField(default=False, verbose_name='Grapado / amarre')),
                ('accesorios_puentes', models.BooleanField(default=False, verbose_name='Accesorios y puentes')),
                ('balizas_desviadores', models.BooleanField(default=False, verbose_name='Balizas / desviadores de vuelo')),
                ('placas_senalizacion', models.BooleanField(default=False, verbose_name='Placas de señalización')),
                ('facturadas_hmv', models.BooleanField(default=False, verbose_name='Facturadas HMV')),
                ('vestida_fibra', models.BooleanField(default=False, verbose_name='Vestida (fibra)')),
                ('riega_manila_fibra', models.BooleanField(default=False, verbose_name='Riega manila (fibra)')),
                ('riega_guaya_opgw', models.BooleanField(default=False, verbose_name='Riega guaya OPGW')),
                ('tendido_opgw', models.BooleanField(default=False, verbose_name='Tendido OPGW')),
                ('grapado_amarre_fibra', models.BooleanField(default=False, verbose_name='Grapado / amarre fibra')),
                ('empalmes_opgw', models.BooleanField(default=False, verbose_name='Empalmes OPGW')),
                ('realizo_conductor', models.CharField(blank=True, max_length=100, verbose_name='Realizó (conductor)')),
                ('realizo_fibra', models.CharField(blank=True, max_length=100, verbose_name='Realizó (fibra)')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tendido_torres', to='construccion.proyectoconstruccion')),
                ('torre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tendido', to='construccion.torreconstruccion')),
            ],
            options={
                'verbose_name': 'Tendido — Torre',
                'verbose_name_plural': 'Tendido — Torres',
                'db_table': 'construccion_tendido_torre',
                'ordering': ['torre__numero'],
            },
        ),
    ]
