# Generated by Django 5.1.15 on 2026-05-24 17:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0014_cant_tendido'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrinchoCuneta',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medida_manejo', models.CharField(choices=[('CUNETA', 'Cuneta'), ('TRINCHO', 'Trincho'), ('AMBAS', 'Cuneta y Trincho')], max_length=10, verbose_name='Medida de manejo')),
                ('metros_trinchos', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Metros lineales trinchos')),
                ('metros_cunetas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Metros lineales cunetas')),
                ('notas', models.TextField(blank=True, verbose_name='Notas / especificaciones')),
                ('tubo_metalico', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tubo metálico 3mx3" (un)')),
                ('malla_eslabonada', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Malla eslabonada (un)')),
                ('alambre_galvanizado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Alambre galvanizado (kg)')),
                ('geotextil', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Geotextil (m)')),
                ('cemento', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cemento (bultos 50K)')),
                ('arena', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Arena (cuñetes)')),
                ('grava', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Grava (cuñetes)')),
                ('cuadrilla', models.CharField(blank=True, max_length=100, verbose_name='Cuadrilla / encargado')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trinchos_cunetas', to='construccion.proyectoconstruccion')),
                ('torre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trinchos_cunetas', to='construccion.torreconstruccion')),
            ],
            options={
                'verbose_name': 'Trincho / Cuneta',
                'verbose_name_plural': 'Trinchos y Cunetas',
                'db_table': 'construccion_trincho_cuneta',
                'ordering': ['torre__numero'],
                'unique_together': {('proyecto', 'torre')},
            },
        ),
    ]
