# Generated by Django 5.1.15 on 2026-05-24 17:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0015_trincho_cuneta'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAvanceSemanal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fase', models.CharField(choices=[('OOCC', 'Obra Civil'), ('MONTAJE', 'Montaje'), ('TENDIDO', 'Tendido')], max_length=10, verbose_name='Fase')),
                ('semana', models.DateField(verbose_name='Semana (lunes)')),
                ('torres_programadas_semana', models.PositiveSmallIntegerField(default=0, verbose_name='Torres programadas (semana)')),
                ('torres_programadas_acum', models.PositiveSmallIntegerField(default=0, verbose_name='Torres programadas (acum)')),
                ('pct_programado', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Programado')),
                ('torres_incluidas_prog', models.CharField(blank=True, help_text='Lista separada por coma, ej "1, 38, 39"', max_length=300, verbose_name='Torres incluidas (prog)')),
                ('torres_construidas_semana', models.PositiveSmallIntegerField(default=0, verbose_name='Torres ejecutadas (semana)')),
                ('torres_construidas_acum', models.PositiveSmallIntegerField(default=0, verbose_name='Torres ejecutadas (acum)')),
                ('pct_construido', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Ejecutado')),
                ('torres_incluidas_cons', models.CharField(blank=True, max_length=300, verbose_name='Torres incluidas (cons)')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards_semanales', to='construccion.proyectoconstruccion')),
            ],
            options={
                'verbose_name': 'Dashboard — Avance semanal',
                'verbose_name_plural': 'Dashboard — Avances semanales',
                'db_table': 'construccion_dashboard_semanal',
                'ordering': ['semana'],
                'unique_together': {('proyecto', 'fase', 'semana')},
            },
        ),
    ]
