# Generated by Django 5.1.15 on 2026-05-26 03:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0016_dashboard_curva_s'),
        ('cuadrillas', '0011_cuadrilla_auditoria_desactivacion'),
        ('lineas', '0011_b21_vano_semestre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorDesempenoLinea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('tipo_trabajo', models.CharField(choices=[('OBRA_CIVIL', 'Obra Civil'), ('MONTAJE', 'Montaje'), ('TENDIDO', 'Tendido'), ('TENDIDO_CONDUCTOR', 'Tendido Conductor')], max_length=30, verbose_name='Tipo de trabajo')),
                ('unidad', models.CharField(choices=[('und/día', 'Unidades por día'), ('torres/semana', 'Torres por semana'), ('km/semana', 'Kilómetros por semana'), ('km/día', 'Kilómetros por día')], max_length=20, verbose_name='Unidad')),
                ('rendimiento', models.FloatField(default=0.0, verbose_name='Rendimiento')),
                ('meta', models.FloatField(default=0.0, verbose_name='Meta')),
                ('actual', models.FloatField(default=0.0, verbose_name='Actual')),
                ('estado', models.CharField(choices=[('EN_META', 'En meta'), ('BAJO_META', 'Bajo meta'), ('SOBRE_META', 'Sobre meta'), ('SIN_DATOS', 'Sin datos')], default='SIN_DATOS', help_text='Auto-clasificado en save() según actual vs meta.', max_length=12, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicadores_desempeno_b2_actualizados', to=settings.AUTH_USER_MODEL)),
                ('cuadrilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicadores_desempeno_construccion_b2', to='cuadrillas.cuadrilla', verbose_name='Cuadrilla')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicadores_desempeno_construccion_b2', to='lineas.linea', verbose_name='Línea')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores_desempeno_b2', to='construccion.proyectoconstruccion', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Indicador Desempeño Línea',
                'verbose_name_plural': 'Indicadores Desempeño Línea',
                'db_table': 'construccion_indicador_desempeno_linea',
                'ordering': ['-fecha', 'linea', 'tipo_trabajo'],
                'indexes': [models.Index(fields=['proyecto', '-fecha'], name='construccio_proyect_5e674e_idx'), models.Index(fields=['linea', 'tipo_trabajo'], name='construccio_linea_i_9226ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='IndicadorFinancieroConstruccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('ingresos_ejecutados', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Ingresos ejecutados')),
                ('costos_directos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Costos directos')),
                ('gastos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Gastos')),
                ('costo_real', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Costo real')),
                ('costo_presupuestado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Costo presupuestado')),
                ('margen_operativo', models.FloatField(blank=True, help_text='(IE - (CD + G)) / IE × 100. Auto-calculado.', null=True, verbose_name='Margen operativo (%)')),
                ('desviacion_presupuestal', models.FloatField(blank=True, help_text='(CR - CP) / CP × 100. Auto-calculado.', null=True, verbose_name='Desviación presupuestal (%)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicadores_financieros_b2_actualizados', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores_financieros_b2', to='construccion.proyectoconstruccion', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Indicador Financiero de Construcción',
                'verbose_name_plural': 'Indicadores Financieros de Construcción',
                'db_table': 'construccion_indicador_financiero',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['proyecto', '-fecha'], name='construccio_proyect_da526d_idx')],
            },
        ),
        migrations.CreateModel(
            name='IndicadorTecnicoConstruccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('presupuesto_ejecutado_pct', models.FloatField(default=0.0, verbose_name='% Presupuesto ejecutado')),
                ('presupuesto_planeado_pct', models.FloatField(default=0.0, verbose_name='% Presupuesto planeado')),
                ('obra_ejecutada', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Obra ejecutada')),
                ('obra_programada', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Obra programada')),
                ('actividades_completadas', models.IntegerField(default=0, verbose_name='Actividades completadas')),
                ('actividades_planificadas', models.IntegerField(default=0, verbose_name='Actividades planificadas')),
                ('cantidad_ejecutada', models.FloatField(default=0.0, verbose_name='Cantidad ejecutada')),
                ('horas_hombre', models.FloatField(default=0.0, verbose_name='Horas hombre')),
                ('ejecucion_presupuestal', models.FloatField(blank=True, null=True, verbose_name='Ejecución Presupuestal (%)')),
                ('avance_obra', models.FloatField(blank=True, null=True, verbose_name='Avance de Obra (%)')),
                ('cumplimiento_cronograma', models.FloatField(blank=True, null=True, verbose_name='Cumplimiento Cronograma (%)')),
                ('productividad', models.FloatField(blank=True, null=True, verbose_name='Productividad (%)')),
                ('rendimiento_cuadrillas', models.FloatField(blank=True, null=True, verbose_name='Rendimiento Cuadrillas (%)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicadores_tecnicos_b2_actualizados', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores_tecnicos_b2', to='construccion.proyectoconstruccion', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Indicador Técnico de Construcción',
                'verbose_name_plural': 'Indicadores Técnicos de Construcción',
                'db_table': 'construccion_indicador_tecnico',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['proyecto', '-fecha'], name='construccio_proyect_f81fd2_idx')],
            },
        ),
    ]
