# Generated by Django 5.1.15 on 2026-05-26 03:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0016_dashboard_curva_s'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadFinalTorre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('empalmes_subestacion', models.BooleanField(default=False, verbose_name='B. Empalme F.O. subestaciones')),
                ('empalmes_intermedios', models.BooleanField(default=False, verbose_name='C. Empalmes F.O. intermedios')),
                ('pruebas_comunicacion', models.BooleanField(default=False, verbose_name='D. Pruebas comunicación F.O.')),
                ('pruebas_electricas', models.BooleanField(default=False, verbose_name='E. Pruebas eléctricas LT 230kV')),
                ('visita_retie', models.BooleanField(default=False, verbose_name='F. Visita certificación RETIE')),
                ('certificado_retie', models.BooleanField(default=False, verbose_name='G. Certificado RETIE')),
                ('mediciones_paso_contacto', models.BooleanField(default=False, verbose_name='H. Mediciones paso/contacto')),
                ('reuniones_cierre', models.BooleanField(default=False, verbose_name='I. Reuniones cierre con comunidades')),
                ('cierre_actas', models.BooleanField(default=False, verbose_name='J. Cierre actas de vecindad')),
                ('paz_salvo_propietarios', models.BooleanField(default=False, verbose_name='K. Paz y salvo propietarios')),
                ('paz_salvo_proveedores', models.BooleanField(default=False, verbose_name='L. Paz y salvo proveedores')),
                ('informe_socioambiental', models.BooleanField(default=False, verbose_name='M. Informe final socioambiental')),
                ('dossier', models.BooleanField(default=False, verbose_name='N. Dossier final compilado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('torre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_finales', to='construccion.torreconstruccion', verbose_name='Torre')),
            ],
            options={
                'verbose_name': 'Actividad Final por Torre',
                'verbose_name_plural': 'Actividades Finales por Torre',
                'db_table': 'construccion_actividad_final_torre',
                'ordering': ['torre__numero'],
            },
        ),
    ]
