# Generated by Django 5.1.15 on 2026-06-09 12:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    """#132 — verbose_name de cerr_lona_m para incluir 'alambre de púa'.

    Cambio de metadata (verbose_name) únicamente; no altera schema ni datos.
    El AlterField sobre `id` absorbe un drift de estado preexistente en main
    (makemigrations --check lo reclamaba con árbol limpio); es no-op de schema.
    """

    dependencies = [
        ('construccion', '0023_financiero_construccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obraciviltorredetalle',
            name='cerr_lona_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Cerramiento — lona o alambre de púa (m)'),
        ),
        migrations.AlterField(
            model_name='obraciviltorredetalle',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
