# Generated by Django 5.1.15 on 2026-06-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0024_oc_cerr_lona_verbose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obraciviltorredetalle',
            name='sol_agua_calc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='m³', max_digits=8, null=True, verbose_name='Solado agua (calc)'),
        ),
        migrations.AlterField(
            model_name='obraciviltorredetalle',
            name='sol_agua_real',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='m³', max_digits=8, null=True, verbose_name='Solado agua (real)'),
        ),
        migrations.AlterField(
            model_name='obraciviltorredetalle',
            name='sol_arena_calc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='m³', max_digits=8, null=True, verbose_name='Solado arena (calc)'),
        ),
        migrations.AlterField(
            model_name='obraciviltorredetalle',
            name='sol_arena_real',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='m³', max_digits=8, null=True, verbose_name='Solado arena (real)'),
        ),
        migrations.AlterField(
            model_name='obraciviltorredetalle',
            name='sol_cemento_calc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='kg', max_digits=8, null=True, verbose_name='Solado cemento (calc)'),
        ),
        migrations.AlterField(
            model_name='obraciviltorredetalle',
            name='sol_cemento_real',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='kg', max_digits=8, null=True, verbose_name='Solado cemento (real)'),
        ),
        migrations.AlterField(
            model_name='obraciviltorredetalle',
            name='sol_grava_calc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='m³', max_digits=8, null=True, verbose_name='Solado grava (calc)'),
        ),
        migrations.AlterField(
            model_name='obraciviltorredetalle',
            name='sol_grava_real',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='m³', max_digits=8, null=True, verbose_name='Solado grava (real)'),
        ),
    ]
