# Generated by Django 5.1.15 on 2026-06-09 12:14
#
# #135 (absorbe #134) — Separa la CLASE de cimentación del MÉTODO de excavación.
# HELICOIDAL estaba mal ubicado en exc_tipo; se mueve a exc_clase_cimentacion.
#
# DATO DE PROD (verificado por el orquestador vía cloud-sql-proxy :5434 ANTES
# de escribir esta migración): construccion_oc_detalle tiene 137 filas con
# exc_tipo='HELICOIDAL', 107 MANUAL, 11 MAQUINA, 2 vacías. La RunPython mueve
# las 137 filas HELICOIDAL → exc_clase_cimentacion. NO es no-op.
#
# Orden seguro: AddField → AlterField → RunPython. Los choices NO son
# constraint a nivel DB, así que el AlterField de exc_tipo no rompe con las
# 137 filas HELICOIDAL aún presentes; la RunPython las limpia justo después.

from django.db import migrations, models


def mover_helicoidal_a_clase_cimentacion(apps, schema_editor):
    """Forward: exc_tipo='HELICOIDAL' → exc_clase_cimentacion='HELICOIDAL' + exc_tipo=''.

    Idempotente: solo afecta filas que aún tienen exc_tipo='HELICOIDAL'.
    Data-safe con 0 filas (el update no toca nada). No pisa una clase ya puesta
    (filtra por exc_tipo, no por clase).
    """
    ObraCivilTorreDetalle = apps.get_model('construccion', 'ObraCivilTorreDetalle')
    ObraCivilTorreDetalle.objects.filter(exc_tipo='HELICOIDAL').update(
        exc_clase_cimentacion='HELICOIDAL',
        exc_tipo='',
    )


def restaurar_helicoidal_a_exc_tipo(apps, schema_editor):
    """Reverse: exc_clase_cimentacion='HELICOIDAL' → exc_tipo='HELICOIDAL' + clase=''.

    Restaura el estado previo para las filas que esta migración movió.
    Idempotente y data-safe con 0 filas.
    """
    ObraCivilTorreDetalle = apps.get_model('construccion', 'ObraCivilTorreDetalle')
    ObraCivilTorreDetalle.objects.filter(
        exc_clase_cimentacion='HELICOIDAL'
    ).update(
        exc_tipo='HELICOIDAL',
        exc_clase_cimentacion='',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0025_oc_solado_unidades_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='obraciviltorredetalle',
            name='exc_clase_cimentacion',
            field=models.CharField(blank=True, choices=[('HELICOIDAL', 'Helicoidal'), ('ZAPATA', 'Zapata'), ('PARRILLA', 'Parrilla'), ('PARRILLA_PESADA', 'Parrilla pesada')], max_length=20, verbose_name='Clase de cimentación'),
        ),
        migrations.AlterField(
            model_name='obraciviltorredetalle',
            name='exc_tipo',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('MAQUINA', 'Con máquina')], max_length=20, verbose_name='Tipo excavación'),
        ),
        migrations.RunPython(
            mover_helicoidal_a_clase_cimentacion,
            restaurar_helicoidal_a_exc_tipo,
        ),
    ]
