# Generated by Django 5.1.15 on 2026-06-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0027_dashboards_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinturafranja',
            name='cantidad_base_consumida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Base consumida (gal)'),
        ),
        migrations.AlterField(
            model_name='pinturafranja',
            name='cantidad_base_proyectada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Base proyectada (gal)'),
        ),
        migrations.AlterField(
            model_name='pinturafranja',
            name='cantidad_color_consumida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Color consumido (gal)'),
        ),
        migrations.AlterField(
            model_name='pinturafranja',
            name='cantidad_color_proyectada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Color proyectado (gal)'),
        ),
        migrations.AlterField(
            model_name='spttorre',
            name='polvora_real_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Pólvora real (gramos)'),
        ),
        migrations.AlterField(
            model_name='spttorre',
            name='polvora_teorica_cajas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Pólvora teórica (gramos)'),
        ),
    ]
