# Generated by Django 5.1.15 on 2026-06-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0028_pintura_unidades_verbose_gramos_gal'),
    ]

    operations = [
        migrations.AddField(
            model_name='obraciviltorre',
            name='fecha_esperada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha esperada'),
        ),
        migrations.AddField(
            model_name='obraciviltorre',
            name='fecha_final',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha final'),
        ),
        migrations.AddField(
            model_name='obraciviltorre',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha inicio'),
        ),
    ]
