# Generated by Django 5.1.15 on 2026-06-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0029_oc_torre_fechas'),
    ]

    operations = [
        migrations.AddField(
            model_name='obraciviltorredetalle',
            name='exc_ft023_ok',
            field=models.BooleanField(default=False, verbose_name='FT-023 OK'),
        ),
        migrations.AddField(
            model_name='obraciviltorredetalle',
            name='exc_ft058_ok',
            field=models.BooleanField(default=False, verbose_name='FT-058 OK'),
        ),
        migrations.AddField(
            model_name='obraciviltorredetalle',
            name='exc_ft922_ok',
            field=models.BooleanField(default=False, verbose_name='FT-922 OK'),
        ),
    ]
