# Generated by Django 5.1.15 on 2026-06-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0030_oc_exc_ft_023_058_922'),
    ]

    operations = [
        migrations.AddField(
            model_name='fasetorre',
            name='circuito_2_aplica',
            field=models.BooleanField(default=True, verbose_name='Circuito 2 aplica'),
        ),
    ]
