# Generated by Django 5.1.15 on 2026-06-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0031_fase_torre_circuito_2_aplica'),
    ]

    operations = [
        migrations.AddField(
            model_name='obraciviltorre',
            name='aplica_obras_proteccion',
            field=models.BooleanField(default=True, help_text='Si False, la torre no aparece en el módulo de Obras de Protección (#149).', verbose_name='Aplica Obras de Protección'),
        ),
    ]
