# Generated by Django 5.1.15 on 2026-06-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0032_oc_torre_aplica_obras_proteccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='obraciviltorre',
            name='aplica_pintura_aeronautica',
            field=models.BooleanField(default=True, help_text='Si False, la torre no aparece en el módulo SPT/Pintura Aeronáutica (#153).', verbose_name='Aplica Pintura Aeronáutica'),
        ),
    ]
