# Generated by Django 5.1.15 on 2026-06-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0033_oc_torre_aplica_pintura_aeronautica'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadfinaltorre',
            name='aplica',
            field=models.BooleanField(default=True, help_text='Si False, la torre no cuenta para el avance (estado "No aplica").', verbose_name='Aplica esta torre'),
        ),
    ]
