# Generated by Django 5.1.15 on 2026-06-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0034_actividad_final_aplica'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadfinaltorre',
            name='certificado_retie_no_aplica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actividadfinaltorre',
            name='cierre_actas_no_aplica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actividadfinaltorre',
            name='dossier_no_aplica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actividadfinaltorre',
            name='empalmes_intermedios_no_aplica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actividadfinaltorre',
            name='empalmes_subestacion_no_aplica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actividadfinaltorre',
            name='informe_socioambiental_no_aplica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actividadfinaltorre',
            name='mediciones_paso_contacto_no_aplica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actividadfinaltorre',
            name='paz_salvo_propietarios_no_aplica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actividadfinaltorre',
            name='paz_salvo_proveedores_no_aplica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actividadfinaltorre',
            name='pruebas_comunicacion_no_aplica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actividadfinaltorre',
            name='pruebas_electricas_no_aplica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actividadfinaltorre',
            name='reuniones_cierre_no_aplica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actividadfinaltorre',
            name='visita_retie_no_aplica',
            field=models.BooleanField(default=False),
        ),
    ]
