# Generated by Django 5.1.15 on 2026-06-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0035_actividadfinaltorre_certificado_retie_no_aplica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torreconstruccion',
            name='aplica',
            field=models.BooleanField(default=True, help_text='Si está desmarcada, la torre se excluye de todos los módulos y del % de avance.', verbose_name='Aplica al proyecto'),
        ),
    ]
