# Generated by Django 5.1.15 on 2026-06-19 19:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0036_torreconstruccion_aplica'),
    ]

    operations = [
        migrations.AddField(
            model_name='fasetorre',
            name='fecha_riega_manila',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha riega de manila'),
        ),
        migrations.AddField(
            model_name='fasetorre',
            name='protecciones_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fasetorre',
            name='protecciones_no_aplica',
            field=models.BooleanField(default=False, verbose_name='Protecciones — No aplica'),
        ),
        migrations.AddField(
            model_name='fasetorre',
            name='protecciones_ok',
            field=models.BooleanField(default=False, verbose_name='Protecciones instaladas'),
        ),
        migrations.AddField(
            model_name='fasetorre',
            name='regulacion_flechado_c1_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fasetorre',
            name='regulacion_flechado_c1_ok',
            field=models.BooleanField(default=False, verbose_name='Regulación/flechado Circuito 1'),
        ),
        migrations.AddField(
            model_name='fasetorre',
            name='regulacion_flechado_c2_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fasetorre',
            name='regulacion_flechado_c2_ok',
            field=models.BooleanField(default=False, verbose_name='Regulación/flechado Circuito 2'),
        ),
        migrations.AddField(
            model_name='fasetorre',
            name='regulacion_flechado_guarda_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fasetorre',
            name='regulacion_flechado_guarda_ok',
            field=models.BooleanField(default=False, verbose_name='Regulación/flechado cable de guarda'),
        ),
        migrations.AlterField(
            model_name='fasetorre',
            name='regulacion_flechado_ok',
            field=models.BooleanField(default=False, verbose_name='Regulación y flechado (general)'),
        ),
        migrations.CreateModel(
            name='RiegaManilaTiro',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_tiro', models.PositiveSmallIntegerField(verbose_name='Número de tiro')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha del tiro')),
                ('flecha_tendido_m', models.FloatField(blank=True, null=True, verbose_name='F.T — Flecha de tendido (m)')),
                ('observaciones', models.CharField(blank=True, max_length=255, verbose_name='Observaciones')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiros_manila', to='construccion.fasetorre')),
            ],
            options={
                'verbose_name': 'Riega de manila — Tiro',
                'verbose_name_plural': 'Riega de manila — Tiros',
                'db_table': 'construccion_riega_manila_tiro',
                'ordering': ['numero_tiro'],
                'unique_together': {('fase', 'numero_tiro')},
            },
        ),
    ]
