# Generated by Django 5.1.15 on 2026-06-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0037_tendido_items_9_10_11'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectoconstruccion',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitud del proyecto (ej: 7.1193). Para el mapa de cuadrillas.', max_digits=10, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='proyectoconstruccion',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitud del proyecto (ej: -73.1227). Para el mapa de cuadrillas.', max_digits=10, null=True, verbose_name='Longitud'),
        ),
    ]
