# Generated by Django 5.1.15 on 2026-07-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0039_backfill_entrega_carga_tendido_147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torreconstruccion',
            name='numero',
            field=models.CharField(help_text='Acepta formato alfanumérico. Ej: T-1, T-1A, T-25B', max_length=20, verbose_name='Número de torre'),
        ),
    ]
