# Generated by Django 5.1.15 on 2026-07-01 12:58
"""#147 rediseño (mockup Gabriel Valencia 2026-06-29): 1 torre = 1 tiro.

Agrega FaseTorre.numero_tiro (editable, reemplaza al formset dinámico
RiegaManilaTiro) y FaseTorre.ft931_ok (check nuevo pedido explícitamente).

Backfill: para cada FaseTorre con filas en RiegaManilaTiro (related_name
'tiros_manila'), numero_tiro = MIN(numero_tiro) de esas filas (representa el
primer/único tiro real de esa torre). Verificado read-only contra prod
(SELECT fase_id, count(*) FROM construccion_riega_manila_tiro GROUP BY fase_id
HAVING count(*) > 1 → 0 filas): las 63 torres con tiro tienen exactamente 1
fila cada una, el backfill es 1:1 limpio, sin casos ambiguos.

RiegaManilaTiro (tabla) NO se borra — queda legacy de solo-lectura, sin FK
nueva apuntando a ella, sin exponerse en template/form nuevo. Preserva el
histórico de F.T (flecha_tendido_m) por si se necesita auditoría futura.
"""
from django.db import migrations, models


def backfill_numero_tiro(apps, schema_editor):
    FaseTorre = apps.get_model('construccion', 'FaseTorre')
    RiegaManilaTiro = apps.get_model('construccion', 'RiegaManilaTiro')

    fase_ids_con_tiros = (
        RiegaManilaTiro.objects.values_list('fase_id', flat=True).distinct()
    )
    for fase_id in fase_ids_con_tiros:
        minimo = (
            RiegaManilaTiro.objects.filter(fase_id=fase_id)
            .order_by('numero_tiro')
            .values_list('numero_tiro', flat=True)
            .first()
        )
        if minimo is not None:
            FaseTorre.objects.filter(pk=fase_id).update(numero_tiro=minimo)


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0040_alter_torreconstruccion_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='fasetorre',
            name='ft931_ok',
            field=models.BooleanField(default=False, verbose_name='FT-931 Control regulación cable de guarda'),
        ),
        migrations.AddField(
            model_name='fasetorre',
            name='numero_tiro',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='N° de tiro'),
        ),
        migrations.RunPython(backfill_numero_tiro, migrations.RunPython.noop),
    ]
