# Generated by Django 5.1.15
"""#147 Cambio 1 (Bloque 2, PLAN_2026-07-09_tendido_bloque2.md).

Agrega 6 campos additive a FaseTorre para que Circuito 2 tenga sus propios
checks (vestida + 4) ANTES de sus 3 fases, siguiendo el patrón `c2_*` ya
establecido (regulacion_flechado_c2_ok/fecha, tendido_conductor_c2_*).

Sin backfill: son campos nuevos sin equivalente legacy, todos arrancan en su
default (False / NULL).
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("construccion", "0041_tiro_unico_ft931"),
    ]

    operations = [
        migrations.AddField(
            model_name="fasetorre",
            name="c2_vestida_ok",
            field=models.BooleanField(default=False, verbose_name="Vestida de torres — Circuito 2"),
        ),
        migrations.AddField(
            model_name="fasetorre",
            name="c2_vestida_fecha",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fasetorre",
            name="c2_riega_manila_ok",
            field=models.BooleanField(default=False, verbose_name="Riega de manila — Circuito 2"),
        ),
        migrations.AddField(
            model_name="fasetorre",
            name="c2_riega_guaya_ok",
            field=models.BooleanField(default=False, verbose_name="Riega de guaya — Circuito 2"),
        ),
        migrations.AddField(
            model_name="fasetorre",
            name="c2_grapado_ok",
            field=models.BooleanField(
                default=False, verbose_name="Grapado / amarre final — Circuito 2"
            ),
        ),
        migrations.AddField(
            model_name="fasetorre",
            name="c2_accesorios_ok",
            field=models.BooleanField(
                default=False, verbose_name="Accesorios instalados — Circuito 2"
            ),
        ),
    ]
