# Generated by Django 5.1.15 on 2026-07-12 18:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0042_circuito2_checks_propios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torreconstruccion',
            name='tipo',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('AE', 'AE'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('TAE', 'TAE')], help_text='Dominio confirmado por leyenda "TIPO DE TORRE" del PDF Hochiminh del cliente (#171).', max_length=20, verbose_name='Tipo de estructura'),
        ),
        migrations.AlterField(
            model_name='torreconstruccion',
            name='tipo_cimentacion',
            field=models.CharField(blank=True, choices=[('ZAPATA', 'Exc. Zapata'), ('PARRILLA_PESADA', 'Parrilla pesada'), ('PARRILLA_LIVIANA', 'Parrilla liviana'), ('PILA_CAMPANA', 'Exc. Pila con campana'), ('PILA_DADO', 'Exc. Pila con dado'), ('MICROPILOTE', 'Micropilote')], help_text='#171 (2026-07-12): dominio de 6 valores del PDF Hochiminh del cliente. Reemplaza el dominio legacy (ZAPATA/HELICOIDAL/PARRILLA/PILOTE/MICROPILOTE) — verificado 0 filas con HELICOIDAL/PILOTE/PARRILLA en prod (F2).', max_length=20, verbose_name='Tipo de cimentación'),
        ),
        migrations.CreateModel(
            name='HochiminhMarcacionReplanteo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marcacion_a', models.BooleanField(default=False, verbose_name='Marcación pata A')),
                ('marcacion_b', models.BooleanField(default=False, verbose_name='Marcación pata B')),
                ('marcacion_c', models.BooleanField(default=False, verbose_name='Marcación pata C')),
                ('marcacion_d', models.BooleanField(default=False, verbose_name='Marcación pata D')),
                ('replanteo_a', models.BooleanField(default=False, verbose_name='Replanteo pata A')),
                ('replanteo_b', models.BooleanField(default=False, verbose_name='Replanteo pata B')),
                ('replanteo_c', models.BooleanField(default=False, verbose_name='Replanteo pata C')),
                ('replanteo_d', models.BooleanField(default=False, verbose_name='Replanteo pata D')),
                ('torre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hochiminh', to='construccion.torreconstruccion')),
            ],
            options={
                'verbose_name': 'Hochiminh — Marcación/Replanteo',
                'verbose_name_plural': 'Hochiminh — Marcación/Replanteo',
                'db_table': 'construccion_hochiminh',
            },
        ),
    ]
