# Generated by Django 5.1.15 on 2026-07-19 23:52
#
# #171 B2 — modelo ColumnaConfigurable (fundamento de columnas configurables
# por capítulo, sub-items B3-B7 futuros) + data migration que crea las 21
# filas "de fábrica" (es_sistema=True) para CADA ProyectoConstruccion
# existente en prod (hoy: 1, Puerta de Oro), con peso_pct = el valor REAL
# vigente de proyecto.peso_*_pct — NO un default hardcodeado — para que el
# refactor futuro de avance_ponderado/avance_conductor/avance_fibra (B3/B4)
# sea matemáticamente idéntico antes/después. Verificado contra BD prod
# (SOLO SELECT) por F2: PLAN_2026-07-19_171_sprint_final.md sección
# "Verificación BD prod".
#
# La especificación de columnas (clave/etiqueta/campo peso/tipo) está
# duplicada literal acá (no importada de apps.construccion.models) a
# propósito: las migraciones de datos deben quedar congeladas en el tiempo,
# independientes de que el código "actual" cambie las listas COLUMNAS más
# adelante (mismo criterio que 0039_backfill_entrega_carga_tendido_147.py).
#
# Reversible: reverse_code borra únicamente las filas es_sistema=True
# creadas por esta migración (en este punto de la historia no existen
# columnas custom todavía — esas llegan en B5/B6).

import django.db.models.deletion
import uuid
from django.db import migrations, models

# (capitulo, [(clave, etiqueta, peso_field, tipo_valor), ...]) — copiado
# literal de ObraCivilTorre.COLUMNAS / MontajeEstructuraTorre.COLUMNAS /
# TendidoTorre.COLUMNAS_CONDUCTOR / TendidoTorre.COLUMNAS_FIBRA vigentes al
# momento de esta migración (apps/construccion/models.py).
_COLUMNAS_ESPEC = [
    ('OBRA_CIVIL', [
        ('cerramiento', 'Cerramiento', 'peso_cerramiento_pct', 'DECIMAL'),
        ('excavacion', 'Excavación', 'peso_excavacion_pct', 'DECIMAL'),
        ('solado', 'Solado', 'peso_solado_pct', 'DECIMAL'),
        ('acero', 'Acero', 'peso_acero_pct', 'DECIMAL'),
        ('vaciado', 'Vaciado', 'peso_vaciado_pct', 'DECIMAL'),
        ('compactacion', 'Compactación', 'peso_compactacion_pct', 'DECIMAL'),
    ]),
    ('MONTAJE', [
        ('estructura_sitio', 'Estructura en sitio', 'peso_mont_estructura_sitio_pct', 'DECIMAL'),
        ('prearamada', 'Prearmada', 'peso_mont_prearamada_pct', 'DECIMAL'),
        ('torre_montada', 'Torre Montada', 'peso_mont_torre_montada_pct', 'DECIMAL'),
        ('revisada', 'Revisada', 'peso_mont_revisada_pct', 'DECIMAL'),
    ]),
    ('TENDIDO_CONDUCTOR', [
        ('riega_manila_conductor', 'Riega manila', 'peso_tend_riega_manila_pct', 'BOOLEAN'),
        ('riega_guaya_conductor', 'Riega guaya', 'peso_tend_riega_guaya_pct', 'BOOLEAN'),
        ('tendido_conductor', 'Tendido conductor', 'peso_tend_tendido_conductor_pct', 'BOOLEAN'),
        ('grapado_amarre_conductor', 'Grapado', 'peso_tend_grapado_pct', 'BOOLEAN'),
        ('accesorios_puentes', 'Accesorios', 'peso_tend_accesorios_pct', 'BOOLEAN'),
        ('balizas_desviadores', 'Balizas', 'peso_tend_balizas_pct', 'BOOLEAN'),
    ]),
    ('TENDIDO_FIBRA', [
        ('riega_manila_fibra', 'Riega manila fibra', 'peso_tend_riega_manila_fibra_pct', 'BOOLEAN'),
        ('riega_guaya_opgw', 'Riega guaya OPGW', 'peso_tend_riega_guaya_opgw_pct', 'BOOLEAN'),
        ('tendido_opgw', 'Tendido OPGW', 'peso_tend_tendido_opgw_pct', 'BOOLEAN'),
        ('grapado_amarre_fibra', 'Grapado fibra', 'peso_tend_grapado_fibra_pct', 'BOOLEAN'),
        ('empalmes_opgw', 'Empalmes OPGW', 'peso_tend_empalmes_opgw_pct', 'BOOLEAN'),
    ]),
]


def crear_columnas_fabrica(apps, schema_editor):
    """Forward: para CADA ProyectoConstruccion existente, crea las 21 filas
    ColumnaConfigurable es_sistema=True con peso_pct = el valor REAL vigente
    de proyecto.peso_*_pct (no un default). Idempotente (get_or_create)."""
    ProyectoConstruccion = apps.get_model('construccion', 'ProyectoConstruccion')
    ColumnaConfigurable = apps.get_model('construccion', 'ColumnaConfigurable')
    for proyecto in ProyectoConstruccion.objects.all():
        for capitulo, columnas in _COLUMNAS_ESPEC:
            for orden, (clave, etiqueta, peso_field, tipo_valor) in enumerate(columnas):
                ColumnaConfigurable.objects.get_or_create(
                    proyecto=proyecto,
                    capitulo=capitulo,
                    clave=clave,
                    defaults={
                        'etiqueta': etiqueta,
                        'orden': orden,
                        'peso_pct': getattr(proyecto, peso_field),
                        'tipo_valor': tipo_valor,
                        'es_sistema': True,
                        'activa': True,
                    },
                )


def borrar_columnas_fabrica(apps, schema_editor):
    """Reverse: borra únicamente las filas es_sistema=True (las de fábrica
    creadas por el forward de esta migración) — no toca columnas custom
    (no existen todavía en este punto de la historia, llegan en B5/B6)."""
    ColumnaConfigurable = apps.get_model('construccion', 'ColumnaConfigurable')
    ColumnaConfigurable.objects.filter(es_sistema=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0043_hochiminh_fase1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnaConfigurable',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capitulo', models.CharField(choices=[('OBRA_CIVIL', 'Obra Civil'), ('MONTAJE', 'Montaje'), ('TENDIDO_CONDUCTOR', 'Tendido — Conductor'), ('TENDIDO_FIBRA', 'Tendido — Fibra/OPGW')], max_length=20, verbose_name='Capítulo')),
                ('clave', models.SlugField(max_length=40, verbose_name='Clave interna')),
                ('etiqueta', models.CharField(max_length=100, verbose_name='Etiqueta visible')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('peso_pct', models.PositiveSmallIntegerField(default=0, verbose_name='Peso %')),
                ('tipo_valor', models.CharField(choices=[('DECIMAL', 'Avance % (0-100)'), ('BOOLEAN', 'Check (hecho/no hecho)')], max_length=10, verbose_name='Tipo de valor')),
                ('es_sistema', models.BooleanField(default=False, help_text='True = una de las columnas originales hardcodeadas (Cerramiento, Excavación, etc.) — no se puede ELIMINAR, solo desactivar (activa=False). False = columna nueva agregada por el cliente vía UI (B6), usa ColumnaConfigurableValor (EAV) para su dato.', verbose_name='Es de sistema')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columnas_configurables', to='construccion.proyectoconstruccion')),
            ],
            options={
                'verbose_name': 'Columna Configurable',
                'verbose_name_plural': 'Columnas Configurables',
                'db_table': 'construccion_columna_configurable',
                'ordering': ['proyecto', 'capitulo', 'orden'],
                'unique_together': {('proyecto', 'capitulo', 'clave')},
            },
        ),
        migrations.RunPython(crear_columnas_fabrica, borrar_columnas_fabrica),
    ]
