# Generated by Django 5.1.15 on 2026-07-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0044_columna_configurable'),
    ]

    operations = [
        migrations.AddField(
            model_name='torreconstruccion',
            name='anulada',
            field=models.BooleanField(default=False, help_text='Torre cancelada del alcance planeado del proyecto (ej. se decidió no construirla). Distinto de "No aplica" (aplica=False, que excluye del % de avance pero la torre sigue en alcance). NO afecta avance_ponderado ni ningún cálculo — solo informativo (#171 V3).', verbose_name='Torre anulada'),
        ),
    ]
