# Generated by Django 5.1.15 on 2026-07-20 00:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0045_torre_anulada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnaConfigurableValor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_decimal', models.DecimalField(blank=True, decimal_places=4, help_text='0 a 1 (1 = 100%) — usado si columna.tipo_valor=DECIMAL.', max_digits=5, null=True, verbose_name='Valor decimal')),
                ('valor_boolean', models.BooleanField(blank=True, help_text='Check hecho/no hecho — usado si columna.tipo_valor=BOOLEAN.', null=True, verbose_name='Valor boolean')),
                ('columna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='construccion.columnaconfigurable')),
                ('torre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_columnas_configurables', to='construccion.torreconstruccion')),
            ],
            options={
                'verbose_name': 'Valor de Columna Configurable',
                'verbose_name_plural': 'Valores de Columnas Configurables',
                'db_table': 'construccion_columna_configurable_valor',
                'unique_together': {('columna', 'torre')},
            },
        ),
    ]
