# Generated by Django 5.1.15 on 2026-07-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0046_columna_configurable_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tendidotorre',
            name='empalmes_opgw',
            field=models.BooleanField(default=False, verbose_name='Empalmes (cable de guarda)'),
        ),
        migrations.AlterField(
            model_name='tendidotorre',
            name='grapado_amarre_fibra',
            field=models.BooleanField(default=False, verbose_name='Grapado / amarre (cable de guarda)'),
        ),
        migrations.AlterField(
            model_name='tendidotorre',
            name='riega_guaya_opgw',
            field=models.BooleanField(default=False, verbose_name='Riega guaya (cable de guarda)'),
        ),
        migrations.AlterField(
            model_name='tendidotorre',
            name='riega_manila_fibra',
            field=models.BooleanField(default=False, verbose_name='Riega manila (cable de guarda)'),
        ),
        migrations.AlterField(
            model_name='tendidotorre',
            name='tendido_opgw',
            field=models.BooleanField(default=False, verbose_name='Tendido (cable de guarda)'),
        ),
    ]
