# Generated by Django 5.1.15 on 2026-08-16 15:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0049_sync_17_formatos_torre_backfill'),
        ('cuadrillas', '0028_vehiculo_catalogo_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionPersonalProyectoConstruccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de aprobación / inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones_proyecto_construccion', to='cuadrillas.personalcuadrilla', verbose_name='Personal')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones_personal_psc', to='construccion.proyectoconstruccion', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Aprobación de personal por proyecto',
                'verbose_name_plural': 'Aprobaciones de personal por proyecto',
                'db_table': 'construccion_asignacion_personal_proyecto',
                'ordering': ['proyecto', 'personal', 'fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ProgramacionSemanalConstruccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('tipo_actividad', models.CharField(choices=[('PRELIMINARES', 'Preliminares'), ('OBRA_CIVIL', 'Obra Civil'), ('MONTAJE', 'Montaje'), ('TENDIDO', 'Tendido'), ('COMPLEMENTARIAS', 'Actividades Complementarias')], max_length=20, verbose_name='Tipo de actividad')),
                ('subactividad', models.CharField(blank=True, max_length=150, verbose_name='Subactividad')),
                ('actividad_complementaria', models.TextField(blank=True, verbose_name='Actividad complementaria')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha fin')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora inicio')),
                ('hora_fin', models.TimeField(blank=True, null=True, verbose_name='Hora fin')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones_semanales_psc', to='construccion.proyectoconstruccion', verbose_name='Proyecto')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programaciones_semanales_psc_supervisadas', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Programación semanal de construcción',
                'verbose_name_plural': 'Programaciones semanales de construcción',
                'db_table': 'construccion_programacion_semanal',
                'ordering': ['fecha_inicio', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ProgramacionSemanalConstruccionPersonal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('categoria', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('ADMINISTRATIVO', 'Administrativo')], default='OPERATIVO', max_length=20, verbose_name='Categoría')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones_semanales_psc', to='cuadrillas.personalcuadrilla', verbose_name='Personal')),
                ('programacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_personal', to='construccion.programacionsemanalconstruccion', verbose_name='Programación')),
            ],
            options={
                'verbose_name': 'Personal programado de construcción',
                'verbose_name_plural': 'Personal programado de construcción',
                'db_table': 'construccion_programacion_semanal_personal',
                'constraints': [models.UniqueConstraint(fields=('programacion', 'personal'), name='psc_programacion_personal_unico')],
            },
        ),
        migrations.CreateModel(
            name='ProgramacionSemanalConstruccionVehiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_conducidos_psc', to='cuadrillas.personalcuadrilla', verbose_name='Conductor')),
                ('programacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_vehiculo', to='construccion.programacionsemanalconstruccion', verbose_name='Programación')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones_semanales_psc', to='cuadrillas.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Vehículo programado de construcción',
                'verbose_name_plural': 'Vehículos programados de construcción',
                'db_table': 'construccion_programacion_semanal_vehiculo',
                'constraints': [models.UniqueConstraint(fields=('programacion', 'vehiculo'), name='psc_programacion_vehiculo_unico')],
            },
        ),
    ]
