# Generated by Django 6.0.7 on 2026-09-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0050_s1_programacion_semanal_construccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacionsemanalconstruccion',
            name='cuadrilla',
            field=models.CharField(blank=True, help_text='Nombre de la cuadrilla según la programación histórica.', max_length=150, verbose_name='Cuadrilla'),
        ),
    ]
