# Generated by Django 6.0.7 on 2026-09-15 18:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0051_psc_cuadrilla'),
        ('cuadrillas', '0035_horas_planeadas_programacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramacionSemanalConstruccionPlanPresupuesto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('congelado_en', models.DateTimeField(verbose_name='Congelado en')),
                ('snapshot', models.JSONField(default=dict, help_text='Contrato serializado para conservar el comparativo aunque cambie el plan editable.', verbose_name='Snapshot del plan')),
            ],
            options={
                'verbose_name': 'Plan presupuestario congelado de construcción',
                'verbose_name_plural': 'Planes presupuestarios congelados de construcción',
                'db_table': 'construccion_programacion_semanal_plan_presupuesto',
            },
        ),
        migrations.AddField(
            model_name='programacionsemanalconstruccionpersonal',
            name='cargo_snapshot_codigo',
            field=models.CharField(blank=True, help_text='Cargo que respaldó la tarifa cuando la fuente fue CARGO.', max_length=20, verbose_name='Código de cargo snapshot'),
        ),
        migrations.AddField(
            model_name='programacionsemanalconstruccionpersonal',
            name='divisor_snapshot',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Divisor usado para calcular la tarifa diaria (actualmente 30).', null=True, verbose_name='Divisor snapshot'),
        ),
        migrations.AddField(
            model_name='programacionsemanalconstruccionpersonal',
            name='fuente_tarifa',
            field=models.CharField(blank=True, choices=[('PERSONAL', 'Salario individual'), ('CARGO', 'Salario del cargo')], max_length=10, verbose_name='Fuente de tarifa'),
        ),
        migrations.AddField(
            model_name='programacionsemanalconstruccionpersonal',
            name='rol_presupuesto',
            field=models.CharField(choices=[('SUPERVISOR', 'Supervisor presupuestario'), ('COLABORADOR', 'Colaborador presupuestario')], default='COLABORADOR', help_text='Rol de esta persona dentro del plan presupuestario; no reemplaza el supervisor legacy de la cabecera.', max_length=15, verbose_name='Rol en presupuesto'),
        ),
        migrations.AddField(
            model_name='programacionsemanalconstruccionpersonal',
            name='salario_mensual_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Salario mensual snapshot'),
        ),
        migrations.AddField(
            model_name='programacionsemanalconstruccionpersonal',
            name='snapshot_tomado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Snapshot tomado en'),
        ),
        migrations.AddField(
            model_name='programacionsemanalconstruccionpersonal',
            name='tarifa_diaria_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Tarifa diaria snapshot'),
        ),
        migrations.AddConstraint(
            model_name='programacionsemanalconstruccionpersonal',
            constraint=models.UniqueConstraint(condition=models.Q(('rol_presupuesto', 'SUPERVISOR')), fields=('programacion',), name='psc_un_supervisor_presupuestario'),
        ),
        migrations.AddField(
            model_name='programacionsemanalconstruccionplanpresupuesto',
            name='primer_real',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_presupuesto_psc_congelados', to='cuadrillas.producciondiaria', verbose_name='Primer real'),
        ),
        migrations.AddField(
            model_name='programacionsemanalconstruccionplanpresupuesto',
            name='programacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_presupuesto_congelado', to='construccion.programacionsemanalconstruccion', verbose_name='Programación'),
        ),
    ]
