# Generated by Django 6.0.7 on 2026-09-23 12:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0052_psc_presupuesto_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCargaPresupuestoConstruccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('anio', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año')),
                ('mes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mes')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('filas_procesadas', models.PositiveIntegerField(default=0, verbose_name='Filas procesadas')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Valor total')),
                ('estado', models.CharField(choices=[('PROCESADA', 'Procesada'), ('ERROR', 'Error')], default='ERROR', max_length=10, verbose_name='Estado')),
                ('archivo_nombre', models.CharField(blank=True, max_length=255, verbose_name='Archivo de origen')),
                ('detalle_errores', models.JSONField(blank=True, default=dict, verbose_name='Detalle de errores')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cargas_presupuesto', to='construccion.proyectoconstruccion', verbose_name='Proyecto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_cargas_presupuesto_construccion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Carga de Presupuesto',
                'verbose_name_plural': 'Historial de Cargas de Presupuesto',
                'db_table': 'construccion_historial_carga_presupuesto',
                'ordering': ['-fecha', '-created_at'],
                'indexes': [models.Index(fields=['proyecto', '-fecha'], name='idx_hist_carga_ppto_proyecto')],
            },
        ),
    ]
