# Generated by Django 6.0.7 on 2026-09-25 23:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion', '0053_historial_carga_presupuesto'),
        ('financiero', '0024_proveedor_linea_carga_268'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcargapresupuestoconstruccion',
            name='tipo',
            field=models.CharField(choices=[('PLANEADO', 'Planeado'), ('REAL', 'Real')], default='PLANEADO', max_length=10, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='GastoRealConstruccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('periodo', models.CharField(max_length=6, verbose_name='Periodo (AAAAMM)')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('mes', models.PositiveSmallIntegerField(verbose_name='Mes')),
                ('auxiliar', models.CharField(blank=True, max_length=50, verbose_name='Auxiliar')),
                ('desc_auxiliar', models.CharField(blank=True, max_length=255, verbose_name='Desc. auxiliar')),
                ('neto', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Neto')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('docto', models.CharField(blank=True, max_length=60, verbose_name='Docto.')),
                ('tercero_nit', models.CharField(blank=True, max_length=30, verbose_name='Tercero movto (NIT)')),
                ('tercero_razon_social', models.CharField(blank=True, max_length=255, verbose_name='Razón social tercero')),
                ('desc_co_movto', models.CharField(blank=True, max_length=255, verbose_name='Desc. C.O. movto')),
                ('usuario_creacion', models.CharField(blank=True, max_length=150, verbose_name='Usuario creación')),
                ('co_movto', models.CharField(blank=True, max_length=30, verbose_name='C.O. movto')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('centro_costo', models.CharField(blank=True, max_length=50, verbose_name='C.Costo')),
                ('desc_centro_costo', models.CharField(blank=True, max_length=255, verbose_name='Desc. C.Costo')),
                ('cuenta_equiv', models.CharField(blank=True, max_length=150, verbose_name='Cuenta Equiv')),
                ('cdec_equiv', models.CharField(blank=True, max_length=150, verbose_name='CdeC equiv')),
                ('cargo', models.CharField(blank=True, max_length=150, verbose_name='Cargo')),
                ('fijo', models.CharField(blank=True, max_length=30, verbose_name='Fijo')),
                ('rubro', models.CharField(blank=True, max_length=150, verbose_name='Rubro')),
                ('clasificacion', models.CharField(blank=True, max_length=10, verbose_name='Clasificación')),
                ('carga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_reales', to='construccion.historialcargapresupuestoconstruccion', verbose_name='Carga')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos_reales_construccion', to='financiero.proveedor', verbose_name='Proveedor (#262)')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_reales', to='construccion.proyectoconstruccion', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Gasto real de construcción',
                'verbose_name_plural': 'Gastos reales de construcción',
                'db_table': 'construccion_gasto_real',
                'ordering': ['periodo', 'cuenta_equiv', 'fecha'],
                'indexes': [models.Index(fields=['proyecto', 'periodo'], name='idx_gasto_real_proy_periodo'), models.Index(fields=['proyecto', 'proveedor'], name='idx_gasto_real_proy_prov')],
            },
        ),
    ]
