# Generated by Django 5.1.15 on 2026-05-07 16:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingenieria', '0002_ingenieriaestado_observacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadEstado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('categoria', models.CharField(choices=[('PREDIAL', 'Predial'), ('AMBIENTAL', 'Ambiental')], max_length=10, verbose_name='Categoría')),
                ('documento_codigo', models.CharField(max_length=50, verbose_name='Código documento')),
                ('estado', models.CharField(blank=True, choices=[('CUMPLE', 'Cumple'), ('NO_CUMPLE', 'No Cumple'), ('NO_APLICA', 'No Aplica')], max_length=10, null=True, verbose_name='Estado')),
                ('observacion', models.TextField(blank=True, default='', verbose_name='Observación')),
                ('torre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='act_estados', to='ingenieria.torrecontrato', verbose_name='Torre')),
            ],
            options={
                'db_table': 'preliminares_estados',
                'unique_together': {('torre', 'categoria', 'documento_codigo')},
            },
        ),
    ]
