# Generated by Django 5.1.15 on 2026-05-07 16:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieria', '0002_ingenieriaestado_observacion'),
        ('preliminares', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actividadestado',
            unique_together={('torre', 'documento_codigo')},
        ),
        migrations.CreateModel(
            name='PredialTorre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('departamento', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('municipio', models.CharField(blank=True, max_length=100, verbose_name='Municipio')),
                ('unidad_territorial', models.CharField(blank=True, max_length=200, verbose_name='Unidad Territorial')),
                ('predio', models.CharField(blank=True, max_length=200, verbose_name='Predio')),
                ('propietario', models.CharField(blank=True, max_length=200, verbose_name='Propietario')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('socializacion', models.DateField(blank=True, null=True, verbose_name='Socialización del proyecto')),
                ('acta_vecindad', models.DateField(blank=True, null=True, verbose_name='Actas de vecindad')),
                ('acta_acceso_com', models.DateField(blank=True, null=True, verbose_name='Acta acceso comunitario')),
                ('autorizacion_prop', models.DateField(blank=True, null=True, verbose_name='Autorización propietario')),
                ('acta_acceso_priv', models.DateField(blank=True, null=True, verbose_name='Acta acceso privado')),
                ('liberacion_predial', models.BooleanField(blank=True, null=True, verbose_name='Liberación predial')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('torre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='predial', to='ingenieria.torrecontrato', verbose_name='Torre')),
            ],
            options={
                'db_table': 'preliminares_predial',
            },
        ),
        migrations.RemoveField(
            model_name='actividadestado',
            name='categoria',
        ),
    ]
