# Generated by Django 5.1.15 on 2026-05-07 17:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieria', '0002_ingenieriaestado_observacion'),
        ('preliminares', '0002_alter_actividadestado_unique_together_predialtorre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbientalTorre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('ahuyentamiento', models.CharField(blank=True, max_length=10, verbose_name='Ahuyentamiento de especies')),
                ('conteo_epifitas', models.CharField(blank=True, max_length=10, verbose_name='Conteo de plantas epifitas')),
                ('traslado_vivero', models.CharField(blank=True, max_length=10, verbose_name='Traslado a vivero de plantas')),
                ('reubicacion_epifitas', models.CharField(blank=True, max_length=10, verbose_name='Reubicación de plantas epifitas')),
                ('aprov_sitio', models.CharField(blank=True, max_length=10, verbose_name='Aprov. forestal sitio de torre')),
                ('arqueologia_poligonos', models.CharField(blank=True, choices=[('', '—'), ('OK', 'Ok'), ('NO_OK', 'No Ok'), ('NA', 'N/A')], max_length=10, verbose_name='Arqueología polígonos/ICANH')),
                ('adecuacion_accesos', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Adecuación de accesos (km)')),
                ('accesos_intervenidos', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Accesos intervenidos (km)')),
                ('avance_rescate', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Avance del rescate (%)')),
                ('liberacion_pdo', models.BooleanField(blank=True, null=True, verbose_name='Liberación predial PDO')),
                ('aprov_vano', models.BooleanField(blank=True, null=True, verbose_name='Aprov. forestal vano')),
                ('rescate_arqueologico', models.BooleanField(blank=True, null=True, verbose_name='Rescate arqueológico')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('torre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ambiental', to='ingenieria.torrecontrato', verbose_name='Torre')),
            ],
            options={
                'db_table': 'preliminares_ambiental',
            },
        ),
    ]
