# Generated by Django 5.1.15 on 2026-05-07 14:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0003_contrato_numero_torres'),
    ]

    operations = [
        migrations.CreateModel(
            name='TorreContrato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre de torre')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torres', to='contratos.contrato', verbose_name='Contrato')),
            ],
            options={
                'db_table': 'ingenieria_torres',
                'ordering': ['orden', 'nombre'],
                'unique_together': {('contrato', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='IngenieriaEstado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('categoria', models.CharField(choices=[('CIVIL', 'Civil'), ('MONTAJE', 'Montaje'), ('TENDIDO', 'Tendido')], max_length=10, verbose_name='Categoría')),
                ('documento_codigo', models.CharField(max_length=50, verbose_name='Código documento')),
                ('estado', models.CharField(blank=True, choices=[('CUMPLE', 'Cumple'), ('NO_CUMPLE', 'No Cumple'), ('NO_APLICA', 'No Aplica')], max_length=10, null=True, verbose_name='Estado')),
                ('torre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='ingenieria.torrecontrato', verbose_name='Torre')),
            ],
            options={
                'db_table': 'ingenieria_estados',
                'unique_together': {('torre', 'categoria', 'documento_codigo')},
            },
        ),
    ]
