# Generated by Django 5.1.15 on 2026-05-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingenieriaestado',
            name='observacion',
            field=models.TextField(blank=True, default='', verbose_name='Observación'),
        ),
    ]
