# Generated by Django 5.1.15 on 2026-06-21 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona', models.CharField(choices=[('JURIDICA', 'Persona Juridica'), ('NATURAL', 'Persona Natural')], max_length=10, verbose_name='Tipo de persona')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razon social / Nombre')),
                ('tipo_identificacion', models.CharField(choices=[('NIT', 'NIT'), ('CC', 'Cedula de Ciudadania'), ('CE', 'Cedula de Extranjeria')], max_length=5, verbose_name='Tipo de identificacion')),
                ('numero_identificacion', models.CharField(max_length=20, verbose_name='Numero de identificacion')),
                ('dv', models.CharField(blank=True, max_length=1, verbose_name='Digito de verificacion')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de facturacion')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('regimen', models.CharField(choices=[('COMMON_REGIME', 'Regimen Comun'), ('SIMPLIFIED_REGIME', 'Regimen Simplificado')], default='COMMON_REGIME', max_length=20, verbose_name='Regimen')),
                ('alegra_contacto_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Contacto Alegra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Datos de Facturacion',
                'verbose_name_plural': 'Datos de Facturacion',
            },
        ),
        migrations.CreateModel(
            name='PlanServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Plan')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Mensual (COP)')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan de Servicio',
                'verbose_name_plural': 'Planes de Servicio',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('PENDIENTE', 'Pendiente de Pago'), ('SUSPENDIDA', 'Suspendida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_inicio', models.DateField(auto_now_add=True, verbose_name='Fecha de Inicio')),
                ('fecha_proximo_pago', models.DateField(blank=True, null=True, verbose_name='Proximo Pago')),
                ('wompi_payment_source_id', models.CharField(blank=True, max_length=100, verbose_name='WOMPI Payment Source ID')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('datos_facturacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suscripciones', to='pagos.datosfacturacion', verbose_name='Datos de facturacion')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagos.planservicio', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Suscripcion',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto (COP)')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('ERROR', 'Error'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('wompi_transaction_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='WOMPI Transaction ID')),
                ('wompi_reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia WOMPI')),
                ('metodo_pago', models.CharField(blank=True, max_length=50, verbose_name='Metodo de Pago')),
                ('detalle_respuesta', models.JSONField(blank=True, default=dict, verbose_name='Detalle Respuesta WOMPI')),
                ('alegra_invoice_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Factura Alegra')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='pagos.suscripcion', verbose_name='Suscripcion')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
