# Generated by Django 5.1.15 on 2026-07-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.UniqueConstraint(condition=models.Q(('wompi_reference', ''), _negated=True), fields=('wompi_reference',), name='uniq_wompi_reference_no_vacio'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.UniqueConstraint(condition=models.Q(('wompi_transaction_id', ''), _negated=True), fields=('wompi_transaction_id',), name='uniq_wompi_transaction_id_no_vacio'),
        ),
    ]
