# Generated by Django 5.1.15 on 2026-07-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_pago_uniq_wompi_reference_no_vacio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='n_meses',
            field=models.PositiveSmallIntegerField(default=1, help_text='Calculado con calcular_n_meses(monto, plan.precio) al crear el pago (issue #199).', verbose_name='Numero de meses cubiertos'),
        ),
    ]
