# Generated by Django 5.1.15 on 2026-04-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='salario_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Salario mensual del trabajador', max_digits=12, null=True, verbose_name='Salario mensual'),
        ),
    ]
