# Generated by Django 5.1.15 on 2026-07-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rbac_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='area',
            field=models.CharField(blank=True, choices=[('CONSTRUCCION', 'Construcción'), ('MANTENIMIENTO', 'Mantenimiento'), ('FINANCIERO', 'Financiero')], default='', help_text='Área de la persona (Construcción/Mantenimiento/Financiero) -- issue #186 (186-M4). Filtro DE VISTA en el listado de Usuarios de Parametrización: el listado completo sigue existiendo sin filtrar, esto no segmenta la BD. blank/default vacío para no romper usuarios legacy sin área asignada.', max_length=20, verbose_name='Área'),
        ),
    ]
