# Generated by Django 5.1.15 on 2026-02-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0005_checklist_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='costo_ambientales',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costos ambientales (permisos, gestión, compensación)', max_digits=14, verbose_name='Costo ambiental'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='costo_garantia',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costos de garantía y pólizas', max_digits=14, verbose_name='Costo garantía'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='costo_herramientas',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo de herramientas y equipos menores', max_digits=14, verbose_name='Costo herramientas'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='costo_materiales',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costos de materiales e insumos', max_digits=14, verbose_name='Costo materiales'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='costo_subcontratistas',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costos de subcontratistas y terceros', max_digits=14, verbose_name='Costo subcontratistas'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='costo_transporte',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costos de transporte adicional (combustible, peajes, etc.)', max_digits=14, verbose_name='Costo transporte'),
        ),
    ]
