# Generated by Django 5.1.15 on 2026-02-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0006_add_budget_pillars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costorecurso',
            name='tipo',
            field=models.CharField(choices=[('DIA_HOMBRE', 'Día Hombre'), ('VEHICULO', 'Vehículo'), ('VIATICO', 'Viático'), ('HERRAMIENTA', 'Herramienta'), ('MATERIAL', 'Material'), ('TRANSPORTE', 'Transporte'), ('COMBUSTIBLE', 'Combustible'), ('PEAJE', 'Peaje'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de recurso'),
        ),
        migrations.AlterField(
            model_name='ejecucioncosto',
            name='tipo_recurso',
            field=models.CharField(choices=[('DIA_HOMBRE', 'Día Hombre'), ('VEHICULO', 'Vehículo'), ('VIATICO', 'Viático'), ('HERRAMIENTA', 'Herramienta'), ('MATERIAL', 'Material'), ('TRANSPORTE', 'Transporte'), ('COMBUSTIBLE', 'Combustible'), ('PEAJE', 'Peaje'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de recurso'),
        ),
    ]
