# Generated by Django 5.1.15 on 2026-02-25 19:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0007_add_transport_cost_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoDetallado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('tipo', models.CharField(choices=[('PLANEADO', 'Planeado'), ('REAL', 'Real')], max_length=10, verbose_name='Tipo')),
                ('datos', models.JSONField(default=dict, help_text='Estructura completa de costos con valores mensuales', verbose_name='Datos')),
            ],
            options={
                'verbose_name': 'Presupuesto Detallado',
                'verbose_name_plural': 'Presupuestos Detallados',
                'db_table': 'presupuestos_detallados',
                'ordering': ['-anio'],
                'unique_together': {('anio', 'tipo')},
            },
        ),
    ]
