# Generated by Django 5.1.15 on 2026-03-05 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        ('financiero', '0008_presupuesto_detallado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presupuestodetallado',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='presupuestodetallado',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos_detallados', to='contratos.contrato', verbose_name='Contrato'),
        ),
        migrations.AlterUniqueTogether(
            name='presupuestodetallado',
            unique_together={('anio', 'tipo', 'contrato')},
        ),
    ]
