# Generated by Django 5.1.15 on 2026-03-05 22:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        ('financiero', '0009_alter_presupuestodetallado_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalAdministrativo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('documento', models.CharField(blank=True, max_length=30, verbose_name='Documento')),
                ('cargo', models.CharField(choices=[('ADMINISTRADOR_OBRA', 'Administrador de Obra'), ('PROFESIONAL_SST', 'Profesional SST'), ('ING_RESIDENTE', 'Ingeniero Residente'), ('SERVICIO_GENERAL', 'Servicio General'), ('ALMACENISTA', 'Almacenista'), ('DIRECTOR_PROYECTO', 'Director de Proyecto'), ('COORDINADOR', 'Coordinador'), ('CONTADOR', 'Contador'), ('AUXILIAR_ADMIN', 'Auxiliar Administrativo'), ('OTRO', 'Otro')], default='OTRO', max_length=30, verbose_name='Cargo')),
                ('salario_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salario mensual')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_administrativo', to='contratos.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Personal Administrativo',
                'verbose_name_plural': 'Personal Administrativo',
                'db_table': 'personal_administrativo',
                'ordering': ['cargo', 'nombre'],
            },
        ),
    ]
