# Generated by Django 5.1 — S1 (#246, #247).

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_acta_voltaje_circuitos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financiero', '0011_mapeo_cta_rubro'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomologacionProjectsContable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('grupo', models.CharField(blank=True, max_length=255, verbose_name='Grupo')),
                ('concepto', models.CharField(max_length=255, verbose_name='Concepto')),
                ('rubro', models.CharField(blank=True, max_length=255, verbose_name='Rubro')),
                ('codigo_contable', models.CharField(max_length=50, verbose_name='Código contable')),
                ('centro_costo', models.CharField(blank=True, max_length=100, verbose_name='Centro de costo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Homologación Projects → Contabilidad',
                'verbose_name_plural': 'Homologaciones Projects → Contabilidad',
                'db_table': 'financiero_homologacion_projects_contable',
                'ordering': ['tipo', 'grupo', 'concepto', 'rubro'],
            },
        ),
        migrations.CreateModel(
            name='CargaFinanciera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('mes', models.PositiveSmallIntegerField(verbose_name='Mes')),
                ('estado', models.CharField(choices=[('VALIDADA', 'Validada'), ('PROCESADA', 'Procesada'), ('ERROR', 'Error')], default='VALIDADA', max_length=15, verbose_name='Estado')),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, verbose_name='Archivo de origen')),
                ('resumen', models.JSONField(blank=True, default=dict, verbose_name='Resumen de carga')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas_financieras', to='contratos.contrato', verbose_name='Proyecto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas_financieras', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Carga financiera',
                'verbose_name_plural': 'Cargas financieras',
                'db_table': 'financiero_carga_financiera',
                'ordering': ['-anio', '-mes', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LineaCargaFinanciera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('tipo', models.CharField(choices=[('REAL', 'Real'), ('PRESUPUESTO', 'Presupuesto')], max_length=15, verbose_name='Tipo')),
                ('grupo', models.CharField(blank=True, max_length=255, verbose_name='Grupo')),
                ('concepto', models.CharField(max_length=255, verbose_name='Concepto')),
                ('rubro', models.CharField(blank=True, max_length=255, verbose_name='Rubro')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor')),
                ('referencia', models.CharField(blank=True, max_length=255, verbose_name='Referencia')),
                ('fila_origen', models.PositiveIntegerField(blank=True, null=True, verbose_name='Fila de origen')),
                ('datos_origen', models.JSONField(blank=True, default=dict, verbose_name='Datos de origen')),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='financiero.cargafinanciera', verbose_name='Carga financiera')),
                ('homologacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineas_cargadas', to='financiero.homologacionprojectscontable', verbose_name='Homologación contable')),
            ],
            options={
                'verbose_name': 'Línea de carga financiera',
                'verbose_name_plural': 'Líneas de carga financiera',
                'db_table': 'financiero_linea_carga_financiera',
                'ordering': ['carga', 'tipo', 'fila_origen', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='homologacionprojectscontable',
            constraint=models.UniqueConstraint(fields=('tipo', 'grupo', 'concepto', 'rubro'), name='uq_finv2_homologacion_origen'),
        ),
        migrations.AddIndex(
            model_name='cargafinanciera',
            index=models.Index(fields=['proyecto', 'anio', 'mes'], name='idx_finv2_carga_periodo'),
        ),
        migrations.AddIndex(
            model_name='lineacargafinanciera',
            index=models.Index(fields=['carga', 'tipo'], name='idx_finv2_linea_carga_tipo'),
        ),
        migrations.AddIndex(
            model_name='lineacargafinanciera',
            index=models.Index(fields=['homologacion'], name='idx_finv2_linea_homolog'),
        ),
    ]
