# Generated by Django 6.0.7 on 2026-09-08 13:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_acta_voltaje_circuitos'),
        ('financiero', '0012_financiero_carga_y_homologacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'db_table': 'financiero_bancos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre o razón social')),
                ('nit', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='NIT')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'db_table': 'financiero_clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'db_table': 'financiero_metodos_pago',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre o razón social')),
                ('nit', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='NIT')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'db_table': 'financiero_proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='ciclofacturacion',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='IVA'),
        ),
        migrations.AddField(
            model_name='ciclofacturacion',
            name='numero_secuencial',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Número secuencial'),
        ),
        migrations.AddField(
            model_name='ciclofacturacion',
            name='plazo_pago_dias',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Plazo de pago (días)'),
        ),
        migrations.AddField(
            model_name='ciclofacturacion',
            name='referencia_cobro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Referencia de cobro'),
        ),
        migrations.AddField(
            model_name='ciclofacturacion',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='ciclofacturacion',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='ciclofacturacion',
            name='banco_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ciclos_facturacion_pagados', to='financiero.banco'),
        ),
        migrations.AddField(
            model_name='ciclofacturacion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ciclos_facturacion', to='financiero.cliente'),
        ),
        migrations.CreateModel(
            name='LineaFacturaIngreso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Cantidad')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor unitario')),
                ('total', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Total')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_factura', to='financiero.ciclofacturacion')),
            ],
            options={
                'db_table': 'financiero_lineas_factura_ingreso',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacturaGasto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('numero_documento', models.CharField(max_length=100, verbose_name='Número de documento')),
                ('documento', models.FileField(blank=True, upload_to='financiero/facturas_gasto/', verbose_name='Documento')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('concepto', models.CharField(max_length=255, verbose_name='Concepto')),
                ('categoria', models.CharField(max_length=255, verbose_name='Categoría')),
                ('centro_costo', models.CharField(blank=True, max_length=100, verbose_name='Centro de costo')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Total')),
                ('estado', models.CharField(choices=[('PENDIENTE_APROBACION', 'Pendiente de aprobación'), ('PENDIENTE_PAGO', 'Pendiente de pago'), ('RECHAZADA', 'Rechazada'), ('PAGADA', 'Pagada')], default='PENDIENTE_PAGO', max_length=25)),
                ('comentario_decision', models.TextField(blank=True, verbose_name='Comentario de aprobación')),
                ('referencia_pago', models.CharField(blank=True, max_length=100, verbose_name='Referencia de pago')),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_gasto', to='financiero.banco')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_gasto', to='contratos.contrato')),
                ('homologacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_gasto', to='financiero.homologacionprojectscontable')),
                ('presupuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_gasto', to='financiero.presupuesto')),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_gasto', to='financiero.metodopago')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_gasto', to='financiero.proveedor')),
            ],
            options={
                'db_table': 'financiero_facturas_gasto',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PagoFacturaGasto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto')),
                ('referencia', models.CharField(max_length=100, verbose_name='Referencia')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financiero.banco')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='financiero.facturagasto')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financiero.metodopago')),
            ],
            options={
                'db_table': 'financiero_pagos_factura_gasto',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PagoFacturaIngreso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto')),
                ('referencia', models.CharField(max_length=100, verbose_name='Referencia')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financiero.banco')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_factura', to='financiero.ciclofacturacion')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financiero.metodopago')),
            ],
            options={
                'db_table': 'financiero_pagos_factura_ingreso',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='facturagasto',
            constraint=models.UniqueConstraint(fields=('proveedor', 'numero_documento'), name='uq_finv2_gasto_proveedor_doc'),
        ),
    ]
