# Generated by Django 6.0.7 on 2026-09-08 16:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_acta_voltaje_circuitos'),
        ('financiero', '0013_finv2_facturas_maestros'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaProyecto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Caja hoy')),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caja_proyectada', to='contratos.contrato')),
            ],
            options={
                'db_table': 'financiero_cajas_proyecto',
                'ordering': ['contrato__codigo'],
            },
        ),
        migrations.CreateModel(
            name='EgresoFijoProyecto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto')),
                ('frecuencia', models.CharField(choices=[('MENSUAL', 'Mensual')], default='MENSUAL', max_length=15)),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egresos_fijos', to='contratos.contrato')),
            ],
            options={
                'db_table': 'financiero_egresos_fijos_proyecto',
                'ordering': ['contrato__codigo', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoBancario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha', models.DateField(verbose_name='Fecha del movimiento')),
                ('referencia', models.CharField(max_length=100, verbose_name='Referencia')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto')),
                ('tipo', models.CharField(choices=[('DEPOSITO', 'Depósito'), ('TRANSFERENCIA', 'Transferencia')], max_length=20)),
                ('origen_importacion', models.CharField(blank=True, max_length=255, verbose_name='Archivo de origen')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='financiero.banco')),
            ],
            options={
                'db_table': 'financiero_movimientos_bancarios',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConciliacionBancaria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONCILIADA', 'Conciliada'), ('DIFERENCIA', 'Con diferencia')], default='PENDIENTE', max_length=15)),
                ('monto_documento', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Monto del documento')),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Diferencia')),
                ('es_override', models.BooleanField(default=False, verbose_name='Es override manual')),
                ('motivo_override', models.TextField(blank=True, verbose_name='Motivo del override')),
                ('fecha_override', models.DateTimeField(blank=True, null=True, verbose_name='Fecha del override')),
                ('ciclo_ingreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conciliaciones', to='financiero.ciclofacturacion')),
                ('factura_gasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conciliaciones', to='financiero.facturagasto')),
                ('usuario_override', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciliaciones_override', to=settings.AUTH_USER_MODEL)),
                ('movimiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conciliacion', to='financiero.movimientobancario')),
            ],
            options={
                'db_table': 'financiero_conciliaciones_bancarias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='movimientobancario',
            index=models.Index(fields=['banco', 'fecha'], name='idx_finv2_mov_banco_fecha'),
        ),
        migrations.AddIndex(
            model_name='movimientobancario',
            index=models.Index(fields=['referencia'], name='idx_finv2_mov_referencia'),
        ),
        migrations.AddConstraint(
            model_name='movimientobancario',
            constraint=models.UniqueConstraint(fields=('banco', 'fecha', 'referencia', 'monto', 'tipo'), name='uq_finv2_movimiento_bancario_importado'),
        ),
        migrations.AddConstraint(
            model_name='conciliacionbancaria',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('factura_gasto__isnull', False), ('ciclo_ingreso__isnull', True)), models.Q(('factura_gasto__isnull', True), ('ciclo_ingreso__isnull', False)), models.Q(('factura_gasto__isnull', True), ('ciclo_ingreso__isnull', True)), _connector='OR'), name='ck_finv2_conciliacion_un_documento'),
        ),
    ]
