# Generated by Django 6.0.7 on 2026-09-14 23:14

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0014_finv2_tesoreria_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaTercero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('tercero_tipo', models.CharField(choices=[('CLIENTE', 'Cliente'), ('PROVEEDOR', 'Proveedor')], max_length=12)),
                ('tercero_id', models.UUIDField()),
                ('campo', models.CharField(max_length=80)),
                ('valor_anterior', models.TextField(blank=True)),
                ('valor_nuevo', models.TextField(blank=True)),
                ('usuario', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'db_table': 'financiero_auditoria_terceros',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CargaTerceros',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('tercero_tipo', models.CharField(choices=[('CLIENTE', 'Cliente'), ('PROVEEDOR', 'Proveedor')], max_length=12)),
                ('archivo_nombre', models.CharField(max_length=255)),
                ('usuario', models.CharField(blank=True, max_length=150)),
                ('filas_total', models.PositiveIntegerField(default=0)),
                ('filas_validas', models.PositiveIntegerField(default=0)),
                ('filas_error', models.PositiveIntegerField(default=0)),
                ('resultado', models.CharField(choices=[('PREVIEW', 'Vista previa'), ('CONFIRMADA', 'Confirmada'), ('RECHAZADA', 'Rechazada')], max_length=20)),
                ('detalle_errores', models.JSONField(blank=True, default=list)),
            ],
            options={'db_table': 'financiero_cargas_terceros', 'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_fin_contrato',
            field=models.DateField(blank=True, null=True, verbose_name='Fin contractual'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_inicio_contrato',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio contractual'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='inactivo_desde',
            field=models.DateField(blank=True, null=True, verbose_name='Inactivo desde'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='industria',
            field=models.CharField(blank=True, max_length=120, verbose_name='Industria'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='motivo_inactivacion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Motivo de inactivación'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='plazo_pago_dias',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Plazo de pago (días)'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fecha_fin_contrato',
            field=models.DateField(blank=True, null=True, verbose_name='Fin contractual'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fecha_inicio_contrato',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio contractual'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='inactivo_desde',
            field=models.DateField(blank=True, null=True, verbose_name='Inactivo desde'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='motivo_inactivacion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Motivo de inactivación'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='plazo_pago_dias',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Plazo de pago (días)'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo_servicio',
            field=models.CharField(blank=True, max_length=120, verbose_name='Tipo de servicio'),
        ),
    ]
