# Generated by Django 6.0.7 on 2026-09-15 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_acta_voltaje_circuitos'),
        ('financiero', '0015_maestros_clientes_proveedores'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclofacturacion',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_ingreso', to='contratos.contrato', verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos', to='financiero.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos_facturacion', to='contratos.contrato', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='ciclofacturacion',
            name='presupuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciclos_facturacion', to='financiero.presupuesto', verbose_name='Presupuesto'),
        ),
    ]
