# Generated by Django 6.0.7 on 2026-09-15 03:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0016_ingreso_contextual_249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='plazo_pago_dias',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Plazo de pago (días)'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='plazo_pago_dias',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Plazo de pago (días)'),
        ),
    ]
