# Generated by Django 6.0.7 on 2026-09-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0017_plazo_pago_dias_max_120'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineacargafinanciera',
            name='tipo_operacional',
            field=models.CharField(default='sin_clasificar', help_text='Clasificación operativa o valor Tipo original del presupuesto.', max_length=50, verbose_name='Tipo operacional'),
        ),
    ]
