# Generated by Django 6.0.7 on 2026-09-15 16:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0018_tipo_operacional_linea_carga'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionHomologacionProjectsContable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('numero', models.PositiveIntegerField(unique=True, verbose_name='Número de versión')),
                ('origen', models.CharField(default='IMPORTACION', max_length=20, verbose_name='Origen')),
                ('diff', models.JSONField(blank=True, default=dict, verbose_name='Diferencias con versión anterior')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_homologacion_projects', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Versión de tabla maestra',
                'verbose_name_plural': 'Versiones de tabla maestra',
                'db_table': 'financiero_version_homologacion_projects',
                'ordering': ['-numero'],
            },
        ),
        migrations.AddField(
            model_name='homologacionprojectscontable',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='homologaciones', to='financiero.versionhomologacionprojectscontable', verbose_name='Versión de catálogo'),
        ),
    ]
