# Generated by Django 6.0.7 on 2026-09-15 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_acta_voltaje_circuitos'),
        ('financiero', '0018_tipo_operacional_linea_carga'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cargafinanciera',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Versión'),
        ),
        migrations.AddField(
            model_name='cargafinanciera',
            name='vigente',
            field=models.BooleanField(default=True, verbose_name='Vigente'),
        ),
        migrations.AddField(
            model_name='lineacargafinanciera',
            name='cdec_equiv',
            field=models.CharField(blank=True, max_length=100, verbose_name='CdeC equivalente'),
        ),
        migrations.AddField(
            model_name='lineacargafinanciera',
            name='centro_costo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Centro de costo origen'),
        ),
        migrations.AddField(
            model_name='lineacargafinanciera',
            name='periodo',
            field=models.PositiveIntegerField(default=0, verbose_name='Período YYYYMM'),
        ),
        migrations.AddIndex(
            model_name='cargafinanciera',
            index=models.Index(fields=['proyecto', 'anio', 'mes', 'vigente'], name='idx_finv2_carga_vigente'),
        ),
        migrations.AddIndex(
            model_name='lineacargafinanciera',
            index=models.Index(fields=['periodo', 'tipo_operacional', 'centro_costo'], name='idx_finv2_linea_filtros'),
        ),
        migrations.AddConstraint(
            model_name='cargafinanciera',
            constraint=models.UniqueConstraint(condition=models.Q(('vigente', True)), fields=('proyecto', 'anio', 'mes'), name='uq_finv2_carga_periodo_vigente'),
        ),
    ]
