# Generated by Django 6.0.7 on 2026-09-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0019_homologacion_versionada_247'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='homologacionprojectscontable',
            name='uq_finv2_homologacion_origen',
        ),
        migrations.AddConstraint(
            model_name='homologacionprojectscontable',
            constraint=models.UniqueConstraint(fields=('version', 'tipo', 'grupo', 'concepto', 'rubro'), name='uq_finv2_homologacion_version_origen'),
        ),
    ]
