# Generated by Django 6.0.7 on 2026-09-15 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0019_finv2_versionado_y_filtros'),
        ('financiero', '0020_version_unica_247'),
    ]

    operations = [
    ]
