# Generated by Django 6.0.7 on 2026-09-16 03:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financiero", "0021_merge_20260915_1345"),
    ]

    operations = [
        migrations.CreateModel(
            name="CargaFacturasIngreso",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Fecha de actualización"),
                ),
                ("archivo_nombre", models.CharField(max_length=255)),
                ("usuario", models.CharField(blank=True, max_length=150)),
                ("filas_total", models.PositiveIntegerField(default=0)),
                ("filas_validas", models.PositiveIntegerField(default=0)),
                ("filas_error", models.PositiveIntegerField(default=0)),
                ("filas_creadas", models.PositiveIntegerField(default=0)),
                ("filas_actualizadas", models.PositiveIntegerField(default=0)),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("PREVIEW", "Vista previa"),
                            ("CONFIRMADA", "Confirmada"),
                            ("RECHAZADA", "Rechazada"),
                        ],
                        max_length=20,
                    ),
                ),
                ("detalle_errores", models.JSONField(blank=True, default=list)),
            ],
            options={
                "db_table": "financiero_cargas_facturas_ingreso",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="ciclofacturacion",
            name="creado_por",
            field=models.CharField(blank=True, max_length=150, verbose_name="Emitida por"),
        ),
        migrations.AddField(
            model_name="pagofacturaingreso",
            name="registrado_por",
            field=models.CharField(blank=True, max_length=150, verbose_name="Registrado por"),
        ),
        migrations.CreateModel(
            name="AuditoriaFacturaIngreso",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Fecha de actualización"),
                ),
                ("campo", models.CharField(max_length=80)),
                ("valor_anterior", models.TextField(blank=True)),
                ("valor_nuevo", models.TextField(blank=True)),
                ("usuario", models.CharField(blank=True, max_length=150)),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auditoria_factura",
                        to="financiero.ciclofacturacion",
                    ),
                ),
            ],
            options={
                "db_table": "financiero_auditoria_facturas_ingreso",
                "ordering": ["-created_at"],
            },
        ),
    ]
