# Generated by Django 6.0.7 on 2026-09-22 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0023_carga_auditoria_facturas_gasto_248'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineacargafinanciera',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Proveedor asociado a la línea, para filtrar/mostrar/enlazar sin parsear datos_origen.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineas_carga_financiera', to='financiero.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddIndex(
            model_name='lineacargafinanciera',
            index=models.Index(fields=['proveedor'], name='idx_finv2_linea_proveedor'),
        ),
    ]
