# Generated by Django 5.2.9 on 2026-01-04 23:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("actividades", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroCampo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(verbose_name="Fecha/hora inicio"),
                ),
                (
                    "fecha_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha/hora fin"
                    ),
                ),
                (
                    "latitud_inicio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=10,
                        null=True,
                        verbose_name="Latitud inicio",
                    ),
                ),
                (
                    "longitud_inicio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=11,
                        null=True,
                        verbose_name="Longitud inicio",
                    ),
                ),
                (
                    "latitud_fin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=10,
                        null=True,
                        verbose_name="Latitud fin",
                    ),
                ),
                (
                    "longitud_fin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=11,
                        null=True,
                        verbose_name="Longitud fin",
                    ),
                ),
                (
                    "dentro_poligono",
                    models.BooleanField(
                        blank=True,
                        help_text="Indica si el registro se hizo dentro del área de servidumbre",
                        null=True,
                        verbose_name="Dentro del polígono",
                    ),
                ),
                (
                    "datos_formulario",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Datos capturados según el tipo de actividad",
                        verbose_name="Datos del formulario",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "observaciones_audio_url",
                    models.URLField(
                        blank=True,
                        help_text="Grabación de voz transcrita",
                        verbose_name="URL audio observaciones",
                    ),
                ),
                (
                    "firma_responsable_url",
                    models.URLField(blank=True, verbose_name="URL firma responsable"),
                ),
                (
                    "sincronizado",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si los datos fueron sincronizados desde el móvil",
                        verbose_name="Sincronizado",
                    ),
                ),
                (
                    "fecha_sincronizacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha sincronización"
                    ),
                ),
                (
                    "actividad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_campo",
                        to="actividades.actividad",
                        verbose_name="Actividad",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros_campo",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Campo",
                "verbose_name_plural": "Registros de Campo",
                "db_table": "registros_campo",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Evidencia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ANTES", "Antes"),
                            ("DURANTE", "Durante"),
                            ("DESPUES", "Después"),
                        ],
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                ("url_original", models.URLField(verbose_name="URL imagen original")),
                (
                    "url_thumbnail",
                    models.URLField(blank=True, verbose_name="URL thumbnail"),
                ),
                (
                    "url_estampada",
                    models.URLField(
                        blank=True,
                        help_text="Imagen con fecha, hora y coordenadas estampadas",
                        verbose_name="URL imagen estampada",
                    ),
                ),
                (
                    "latitud",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=10,
                        null=True,
                        verbose_name="Latitud",
                    ),
                ),
                (
                    "longitud",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=11,
                        null=True,
                        verbose_name="Longitud",
                    ),
                ),
                (
                    "fecha_captura",
                    models.DateTimeField(verbose_name="Fecha de captura"),
                ),
                (
                    "validacion_ia",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Resultado de validación: nitidez, iluminación, válida",
                        verbose_name="Validación IA",
                    ),
                ),
                (
                    "metadata_exif",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadata EXIF"
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Descripción"
                    ),
                ),
                (
                    "registro_campo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidencias",
                        to="campo.registrocampo",
                        verbose_name="Registro de campo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evidencia",
                "verbose_name_plural": "Evidencias",
                "db_table": "evidencias",
                "ordering": ["tipo", "fecha_captura"],
            },
        ),
    ]
