# Generated by Django 5.2.11 on 2026-02-20 19:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0004_alter_evidencia_metadata_exif_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteDano',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('descripcion', models.TextField(help_text='Descripción detallada del daño encontrado', verbose_name='Descripción del daño')),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitud')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_dano', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
            ],
            options={
                'verbose_name': 'Reporte de Daño',
                'verbose_name_plural': 'Reportes de Daño',
                'db_table': 'reportes_dano',
                'ordering': ['-created_at'],
            },
        ),
    ]
