# Generated by Django 5.1.15 on 2026-02-25 15:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0006_procedimiento'),
        ('lineas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedano',
            name='linea',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='reportes_dano',
                to='lineas.linea',
                verbose_name='Línea',
            ),
        ),
        migrations.AddField(
            model_name='reportedano',
            name='torre',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='reportes_dano',
                to='lineas.torre',
                verbose_name='Torre',
            ),
        ),
        migrations.AddField(
            model_name='reportedano',
            name='tipo_dano',
            field=models.CharField(
                choices=[
                    ('ESTRUCTURAL', 'Daño estructural'),
                    ('ELECTRICO', 'Daño eléctrico'),
                    ('AMBIENTAL', 'Daño ambiental'),
                    ('VANDALISMO', 'Vandalismo'),
                    ('CLIMATICO', 'Daño por clima'),
                    ('DESGASTE', 'Desgaste natural'),
                    ('OTRO', 'Otro'),
                ],
                default='OTRO',
                max_length=20,
                verbose_name='Tipo de daño',
            ),
        ),
        migrations.AddField(
            model_name='reportedano',
            name='severidad',
            field=models.CharField(
                choices=[
                    ('BAJA', 'Baja'),
                    ('MEDIA', 'Media'),
                    ('ALTA', 'Alta'),
                    ('CRITICA', 'Crítica'),
                ],
                default='MEDIA',
                max_length=10,
                verbose_name='Severidad',
            ),
        ),
        migrations.CreateModel(
            name='FotoDano',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('imagen', models.ImageField(upload_to='campo/danos/', verbose_name='Imagen')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('reporte', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='fotos',
                    to='campo.reportedano',
                    verbose_name='Reporte de daño',
                )),
            ],
            options={
                'db_table': 'fotos_dano',
                'verbose_name': 'Foto de Daño',
                'verbose_name_plural': 'Fotos de Daño',
                'ordering': ['created_at'],
            },
        ),
    ]
