# Generated by Django 5.1.15 on 2026-04-01 17:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0007_populate_cuadrillas_m2m'),
        ('campo', '0007_enhance_reporte_dano'),
        ('cuadrillas', '0010_add_personal_cuadrilla_and_attendance_options'),
        ('lineas', '0005_linea_cantidad_postes_linea_cantidad_torres_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotodano',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='AvanceVano',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('numero_vano', models.PositiveIntegerField(help_text='Número secuencial del vano en la actividad', verbose_name='Número de vano')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('ejecutado', 'Ejecutado'), ('sin_permiso', 'Sin Permiso'), ('no_ejecutado', 'No Ejecutado'), ('en_espera', 'En Espera')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_marcado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha marcado')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha revisión')),
                ('aprobado', models.BooleanField(default=False, help_text='Indica si el supervisor aprobó este vano', verbose_name='Aprobado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances_vanos', to='actividades.actividad', verbose_name='Actividad')),
                ('cuadrilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances_vanos', to='cuadrillas.cuadrilla', verbose_name='Cuadrilla asignada')),
                ('cuadrilla_asignada_original', models.ForeignKey(blank=True, help_text='Cuadrilla a la que se asignó originalmente este vano', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vanos_originales', to='cuadrillas.cuadrilla', verbose_name='Cuadrilla asignada originalmente')),
                ('marcado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vanos_marcados', to=settings.AUTH_USER_MODEL, verbose_name='Marcado por')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vanos_revisados', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('torre_fin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances_fin', to='lineas.torre', verbose_name='Torre fin')),
                ('torre_inicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances_inicio', to='lineas.torre', verbose_name='Torre inicio')),
            ],
            options={
                'verbose_name': 'Avance de Vano',
                'verbose_name_plural': 'Avances de Vanos',
                'db_table': 'avances_vanos',
                'ordering': ['actividad', 'numero_vano'],
                'indexes': [models.Index(fields=['actividad', 'cuadrilla'], name='avances_van_activid_7e293d_idx'), models.Index(fields=['estado'], name='avances_van_estado_381102_idx'), models.Index(fields=['cuadrilla', 'fecha_marcado'], name='avances_van_cuadril_62b929_idx')],
                'unique_together': {('actividad', 'numero_vano')},
            },
        ),
    ]
