# Generated by Django 5.1.15 on 2026-04-13 23:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0008_alter_fotodano_id_avancevano'),
        ('cuadrillas', '0010_add_personal_cuadrilla_and_attendance_options'),
        ('lineas', '0005_linea_cantidad_postes_linea_cantidad_torres_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAvance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('tipo_avance', models.CharField(choices=[('completo', 'Avance Completo'), ('parcial', 'Avance Parcial'), ('sin_avance', 'Sin Avance'), ('no_ejecutable', 'No Ejecutable')], default='completo', max_length=20, verbose_name='Tipo de avance')),
                ('fecha_avance', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del avance')),
                ('observaciones', models.TextField(blank=True, help_text='Detalles del trabajo realizado, pendientes, etc.', verbose_name='Observaciones')),
                ('porcentaje', models.PositiveIntegerField(default=100, help_text='Porcentaje completado en esta torre (0-100)', verbose_name='Porcentaje de avance')),
                ('cuadrilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_avance', to='cuadrillas.cuadrilla', verbose_name='Cuadrilla')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_avance', to='lineas.linea', verbose_name='Línea')),
                ('torre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_avance', to='lineas.torre', verbose_name='Torre')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_avance', to=settings.AUTH_USER_MODEL, verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Registro de Avance',
                'verbose_name_plural': 'Registros de Avance',
                'db_table': 'registros_avance',
                'ordering': ['-fecha_avance'],
                'indexes': [models.Index(fields=['usuario', 'fecha_avance'], name='registros_a_usuario_25a379_idx'), models.Index(fields=['cuadrilla', 'fecha_avance'], name='registros_a_cuadril_3b303e_idx'), models.Index(fields=['linea', 'fecha_avance'], name='registros_a_linea_i_77c1a3_idx'), models.Index(fields=['torre', 'fecha_avance'], name='registros_a_torre_i_10ebf5_idx')],
            },
        ),
    ]
