# Generated by Django 5.1.15 on 2026-05-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0010_registrocampo_severidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimiento',
            name='tipo_archivo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Tipo de archivo'),
        ),
    ]
