# Generated by Django 5.1.15 on 2026-06-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0012_procedimiento_blob_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avancevano',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('ejecutado', 'Ejecutado'), ('sin_permiso', 'Sin Permiso'), ('no_ejecutado', 'No Ejecutado'), ('en_espera', 'Parcial')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
