# Generated by Django 5.1.15 on 2026-07-31 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0013_avancevano_estado_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimiento',
            name='categoria',
            field=models.CharField(choices=[('guia_mantenimiento', 'Guía de Mantenimiento'), ('ficha_tecnica', 'Ficha Técnica')], default='guia_mantenimiento', help_text='Guía de Mantenimiento (paso a paso) o Ficha Técnica (hoja de vida de un elemento).', max_length=30, verbose_name='Categoría'),
        ),
    ]
