# Generated by Django 5.1.15 on 2026-03-05 12:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('unidad_negocio', models.CharField(choices=[('MANTENIMIENTO', 'Mantenimiento de Líneas'), ('CONSTRUCCION', 'Construcción de Líneas')], max_length=20, verbose_name='Unidad de negocio')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre del contrato')),
                ('cliente', models.CharField(blank=True, max_length=200, verbose_name='Cliente')),
                ('objeto', models.TextField(blank=True, verbose_name='Objeto del contrato')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Valor del contrato')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'contratos',
                'ordering': ['unidad_negocio', 'codigo'],
            },
        ),
    ]
