# Generated by Django 5.1.15 on 2026-05-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='acta_inicio',
            field=models.FileField(blank=True, null=True, upload_to='contratos/actas/', verbose_name='Acta de inicio'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='longitud_linea',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Longitud de la línea (km)'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='plazo_ejecucion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Plazo de ejecución (días)'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.CharField(blank=True, choices=[('LLAVE_EN_MANO', 'Llave en Mano'), ('SUMA_GLOBAL', 'Suma Global'), ('ADMINISTRACION', 'Por Administración'), ('PRECIOS_UNITARIOS', 'Precios Unitarios')], max_length=30, verbose_name='Tipo de contrato'),
        ),
    ]
