# Generated by Django 5.1.15 on 2026-05-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_contrato_acta_inicio_contrato_longitud_linea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='numero_torres',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de torres'),
        ),
    ]
