# Generated by Django 5.2.9 on 2026-01-04 23:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cuadrillas", "0001_initial"),
        ("lineas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoActividad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=20, unique=True, verbose_name="Código"),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("PODA", "Poda de Vegetación"),
                            ("HERRAJES", "Cambio de Herrajes"),
                            ("AISLADORES", "Cambio de Aisladores"),
                            ("INSPECCION", "Inspección"),
                            ("LIMPIEZA", "Limpieza"),
                            ("SEÑALIZACION", "Señalización"),
                            ("MEDICION", "Medición"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "requiere_fotos_antes",
                    models.BooleanField(
                        default=True, verbose_name="Requiere fotos ANTES"
                    ),
                ),
                (
                    "requiere_fotos_durante",
                    models.BooleanField(
                        default=True, verbose_name="Requiere fotos DURANTE"
                    ),
                ),
                (
                    "requiere_fotos_despues",
                    models.BooleanField(
                        default=True, verbose_name="Requiere fotos DESPUÉS"
                    ),
                ),
                (
                    "min_fotos",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Mínimo de fotos"
                    ),
                ),
                (
                    "campos_formulario",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Configuración de campos dinámicos en formato JSON",
                        verbose_name="Campos del formulario",
                    ),
                ),
                (
                    "tiempo_estimado_horas",
                    models.DecimalField(
                        decimal_places=2,
                        default=2,
                        max_digits=4,
                        verbose_name="Tiempo estimado (horas)",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Tipo de Actividad",
                "verbose_name_plural": "Tipos de Actividad",
                "db_table": "tipos_actividad",
                "ordering": ["categoria", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="ProgramacionMensual",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                ("anio", models.PositiveIntegerField(verbose_name="Año")),
                ("mes", models.PositiveIntegerField(verbose_name="Mes")),
                (
                    "archivo_origen",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="programacion/excel/",
                        verbose_name="Archivo Excel origen",
                    ),
                ),
                (
                    "datos_importados",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Datos importados"
                    ),
                ),
                (
                    "total_actividades",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total actividades"
                    ),
                ),
                (
                    "aprobado",
                    models.BooleanField(default=False, verbose_name="Aprobado"),
                ),
                (
                    "fecha_aprobacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de aprobación"
                    ),
                ),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="programaciones_aprobadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobado por",
                    ),
                ),
                (
                    "linea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programaciones",
                        to="lineas.linea",
                        verbose_name="Línea",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programación Mensual",
                "verbose_name_plural": "Programaciones Mensuales",
                "db_table": "programacion_mensual",
                "ordering": ["-anio", "-mes", "linea"],
                "unique_together": {("anio", "mes", "linea")},
            },
        ),
        migrations.CreateModel(
            name="Actividad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                ("fecha_programada", models.DateField(verbose_name="Fecha programada")),
                (
                    "fecha_reprogramada",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha reprogramada"
                    ),
                ),
                (
                    "hora_inicio_estimada",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora inicio estimada"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("PROGRAMADA", "Programada"),
                            ("EN_CURSO", "En Curso"),
                            ("COMPLETADA", "Completada"),
                            ("CANCELADA", "Cancelada"),
                            ("REPROGRAMADA", "Reprogramada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("BAJA", "Baja"),
                            ("NORMAL", "Normal"),
                            ("ALTA", "Alta"),
                            ("URGENTE", "Urgente"),
                        ],
                        default="NORMAL",
                        max_length=10,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "observaciones_programacion",
                    models.TextField(
                        blank=True, verbose_name="Observaciones de programación"
                    ),
                ),
                (
                    "motivo_reprogramacion",
                    models.TextField(
                        blank=True, verbose_name="Motivo de reprogramación"
                    ),
                ),
                (
                    "motivo_cancelacion",
                    models.TextField(blank=True, verbose_name="Motivo de cancelación"),
                ),
                (
                    "cuadrilla",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actividades",
                        to="cuadrillas.cuadrilla",
                        verbose_name="Cuadrilla asignada",
                    ),
                ),
                (
                    "linea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades",
                        to="lineas.linea",
                        verbose_name="Línea",
                    ),
                ),
                (
                    "torre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades",
                        to="lineas.torre",
                        verbose_name="Torre",
                    ),
                ),
                (
                    "programacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actividades",
                        to="actividades.programacionmensual",
                        verbose_name="Programación mensual",
                    ),
                ),
                (
                    "tipo_actividad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actividades",
                        to="actividades.tipoactividad",
                        verbose_name="Tipo de actividad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad",
                "verbose_name_plural": "Actividades",
                "db_table": "actividades",
                "ordering": ["-fecha_programada", "prioridad", "linea", "torre"],
                "indexes": [
                    models.Index(
                        fields=["fecha_programada", "estado"],
                        name="actividades_fecha_p_cdd070_idx",
                    ),
                    models.Index(
                        fields=["cuadrilla", "fecha_programada"],
                        name="actividades_cuadril_471afb_idx",
                    ),
                    models.Index(
                        fields=["linea", "fecha_programada"],
                        name="actividades_linea_i_2195bc_idx",
                    ),
                ],
            },
        ),
    ]
