# Generated by Django 5.1.15 on 2026-02-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_remove_informediario_unique_informe_fecha_cuadrilla_and_more'),
        ('cuadrillas', '0009_add_conductor_interno'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='cuadrillas',
            field=models.ManyToManyField(blank=True, help_text='Permite asignar multiples cuadrillas a un aviso', related_name='actividades_asignadas', to='cuadrillas.cuadrilla', verbose_name='Cuadrillas asignadas'),
        ),
    ]
