# Generated by Django 5.1.15 on 2026-02-25 14:08

from django.db import migrations


def populate_cuadrillas_m2m(apps, schema_editor):
    """Copy existing cuadrilla FK values to the new M2M cuadrillas field."""
    Actividad = apps.get_model('actividades', 'Actividad')
    for actividad in Actividad.objects.filter(cuadrilla__isnull=False).iterator():
        actividad.cuadrillas.add(actividad.cuadrilla)


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0006_add_cuadrillas_m2m'),
    ]

    operations = [
        migrations.RunPython(populate_cuadrillas_m2m, migrations.RunPython.noop),
    ]
