# Generated by Django 5.1.15 on 2026-04-01 17:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0007_populate_cuadrillas_m2m'),
        ('campo', '0008_alter_fotodano_id_avancevano'),
        ('cuadrillas', '0010_add_personal_cuadrilla_and_attendance_options'),
        ('lineas', '0005_linea_cantidad_postes_linea_cantidad_torres_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialIntervencion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha_intervencion', models.DateTimeField(help_text='Fecha y hora en que se realizó la intervención', verbose_name='Fecha de intervención')),
                ('tipo_intervencion', models.CharField(help_text='Tipo de actividad realizada', max_length=100, verbose_name='Tipo de intervención')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_intervenciones', to='actividades.actividad', verbose_name='Actividad')),
                ('cuadrilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_intervenciones', to='cuadrillas.cuadrilla', verbose_name='Cuadrilla')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_intervenciones', to='lineas.linea', verbose_name='Línea')),
                ('registro_campo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_intervenciones', to='campo.registrocampo', verbose_name='Registro de campo')),
                ('torre_fin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervenciones_fin', to='lineas.torre', verbose_name='Torre fin')),
                ('torre_inicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervenciones_inicio', to='lineas.torre', verbose_name='Torre inicio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_intervenciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Intervención',
                'verbose_name_plural': 'Historial de Intervenciones',
                'db_table': 'historial_intervenciones',
                'ordering': ['-fecha_intervencion'],
                'indexes': [models.Index(fields=['linea', 'fecha_intervencion'], name='historial_i_linea_i_7223df_idx'), models.Index(fields=['cuadrilla', 'fecha_intervencion'], name='historial_i_cuadril_6e9573_idx'), models.Index(fields=['actividad'], name='historial_i_activid_6278b7_idx')],
            },
        ),
    ]
