# Generated by Django 5.1.15 on 2026-08-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0009_costos_presupuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='aviso_sap',
            field=models.CharField(blank=True, help_text='Número de aviso en el sistema SAP de Transelca', max_length=50, verbose_name='Número Aviso SAP'),
        ),
    ]
